export default {
  "Index": {
    "listInformation": "List information",
    "byInvoice": "By invoice",
    "byStatement": "By statement",
    "byBill": "By bill",
    "byWorkOrder": "By work order",
    "byCost": "By cost",
    "statusList": "Status list",
    "chongHong": "Red flush",
    "registerInvoice": "Register invoice",
    "summaryBilling": "Summary Invoicing",
    "detailedInvoice": "Detailed Invoicing",
    "alreadySelected": "Only charges of the same type ({val1}) can be added when there are already selected charges",
    "amountInOriginalCurrency": "Amount in original currency: {val1}",
    "equivalentStandard": "Amount in functional currency:",
    "ofPer": "There are {val1} in total, and {val2} on each page",
    "writeOffDate": "Write off date",
    "billingDate": "Billing date",
    "auditDate": "Audit date",
    "actualReconciliation": "Actual reconciliation date",
    "reconciliationDate": "Reconciliation date ",
    "billConfirmation": "Bill confirmation date",
    "feeCreation": "Expense creation date",
    "jobNo": "Work order No. / bill No. / reconciliation No. / Invoice No",
    "redInkInvoice": "Red ink invoice",
    "billingMethod": "Billing method",
    "theLatestTicket": "Latest ticket date",
    "dateOfNotice": "Notice date",
    "invoiceNo": "Invoice No. / Invoice No. / original invoice No. / bill No. / reconciliation No. / Order No. / bill of lading No",
    "paymentTerm": "Terms of payment",
    "departureDate": "Departure date",
    "reconciliationNo": "Reconciliation No. / Order No. / bill of lading No. / bill No. / Invoice No",
    "statementDate": "statement date ",
    "arrivalDate": "Arrival date",
    "sendingTime": "Sending time",
    "orderNoWithdrawal": "Order No. / bill of lading No. / bill No. / Invoice No",
    "dateOfReceipt": "Receipt date",
    "statementNo": "Bill No. / reconciliation No. / Invoice No. / Order No. / bill of lading No",
    "selfSolicitation": "Self solicitation"
  }
}