export default {
  "Index": {
    "verificationFailed": "Verification failed, please modify the red data in the list",
    "atLeastOne": "At least one box type and volume record",
    "changeBoxType": "Change box type and volume",
    "viewBoxType": "View box type and volume",
    "detailed": "detailed",
    "cancel": "cancel",
    "noInfoCtn": "Import without assignment",
    "infoCtn": "Assignment container",
    "determine": "determine",
    "okToDelete": "Are you sure to delete?",
    "containerCapacity": "Box quantity",
    "boxQuantityIsRequired": "Box quantity is required",
    "boxType": "Box type",
    "boxTypeIsRequired": "Box type is required",
    "boxTypeAndQuantity": "Box type and volume",
    "addSpecification": "+Add specification",
    "containerNo": "No more than 250 containers",
    "batchAdd": "Batch add",
    "repeat": "{val1} repeat!",
    "caseNo": "Case No.: ({val1})",
    "atMost": "You can only add up to 20 specifications",
    "boxEast": "Box East",
    "boxEastIsRequired": "Ctnr master is required is required",
    "boxRequirements": "Box requirements",
    "sealLength": "The seal length cannot exceed 30. You can only enter English, numbers and English characters",
    "title": "title",
    "boxNumberFormat": "Case number format does not meet the specification!",
    "caseNoCanOnly": "The case number can only be entered in English, numbers and English characters",
    "caseNumber": "Case number",
    "boxTypeIsRequired2": "Box type is required and cannot be Chinese",
    "fullName": "Full name",
    "code": "code"
  }
}