export default {
  "HeaderInfo": {
    "bookingStatus": "Booking status",
    "services": "Service items:",
    "exit": "Exit",
    "importAndExport": "Inlet / outlet",
    "lclSubList": "LCL sub list",
    "lclMasterList": "LCL master order"
  },
  "HeaderMenu": {
    "changeOrder": "Change order"
  },
  "OrderRefuse": {
    "refuseTo": "Refuse to",
    "refuseSuccess": "Reject successful"
  },
  "BusinessMenuConstants": {
    "logisticsTracking": "Logistics tracking",
    "changeOrderAndAllocation": "Change order and configuration",
    "fileManagement": "file management",
    "requestInformation": "Book information",
    "recordSnapshot": "Recording snapshot",
    "firstInstanceSnapshot": "First instance snapshot",
    "firstInstance": "first instance",
    "recordingDetails": "Record details",
    "documents": "Documents",
    "manifest": "Manifest",
    "interiorDecoration": "Built in",
    "operationDetails": "Operation details"
  },
  "Constants": {
    "semilunarKnot": "Semilunar knot",
    "zhouJie": "Zhou Jie",
    "recEditFinish": "A / R entry completed",
    "payEditFinish": "A / P entry completed",
    "check": "check",
    "notSubmitted": "Not submitted",
    "shanghaiHuanshi": "Shanghai Huanshi MRT Logistics Co., Ltd. Foshan branch",
    "shanghaiHuanshi2": "Shanghai Huanshi MRT Logistics Co., Ltd. Guangzhou Branch",
    "shanghaiHuanshi3": "Shanghai Huanshi MRT Logistics Co., Ltd. Shenzhen Branch",
    "passedTheInternalAudit": "Internal audit passed",
    "passedTheFirstInstance": "Passed in the first instance",
    "approved": "Approved documents",
    "pendingFirstInstance": "Pending first instance",
    "draft": "draft",
    "lockOrderTaken": "Lock order cancelled",
    "lockedOrder": "Locked order",
    "newBillOfLading": "New bill of lading",
    "independentSettlement": "Independent settlement",
    "addedConnected": "Add received",
    "modifyReceived": "Modify received",
    "cancelReceived": "Cancel received",
    "newRejected": "New rejected",
    "modificationRejected": "Modification rejected",
    "cancelRejected": "Cancel rejected",
    "newIssued": "New sent",
    "modifyIssued": "Modify sent",
    "cancelSent": "Cancel sent",
    "seaSpellCanBeSigned": "Signature form for overseas shopping",
    "warehoused": "Warehoused",
    "warehouseReceipt": "Warehouse receipt"
  },
  "Documents": {
    "sendOut": "Send AMS",
    "notSaved": "Not saved",
    "status": "Status:",
    "confirm": "Are you sure to delete the selected AMS?",
    "cancelDeletion": "Cancel deletion",
    "pleaseSelect": "Please select type of entry",
    "detailedInformation": "Detail column 3",
    "stateAndOperation": "Status and operation",
    "sendingForm": "Sending form",
    "itCanOnlyBeDoneByBigCompanies": "It can only consist of capital letters and numbers",
    "theLengthCannotBeChanged": "Length cannot be greater than 10",
    "lengthCannot": "The length cannot exceed {val1}. You can only enter numbers, English and special characters",
    "maximumLength": "The maximum length cannot exceed 1500 characters",
    "serviceSelection": "Service selection",
    "pleaseInput": "Please enter commodity",
    "serviceSelection2": "Service selection content",
    "detailedInformation2": "Detail column 2",
    "detailedInformation3": "The second column of details",
    "detailedInformation4": "Detail first column",
    "onlyInput": "You can only enter up to 4 uppercase English characters",
    "cannotInput": "Chinese characters cannot be entered",
    "required": "Required item. Only numbers less than 7 characters can be entered",
    "consignees": "Consignee's U.S. return number",
    "canadian": "Type of entry into Canada:",
    "splittingStatus": "Splitting status",
    "lockOrderStatus": "Lock order status",
    "hasBeenConsolidated": "The order has been consolidated, unable to cancel all the split orders!",
    "pleaseEnterTheLatest": "Please enter up to 200 non Chinese characters",
    "onlyInput2": "You can only enter up to 10 uppercase English characters",
    "confirmThatItWillComeOff": "Are you sure that {val1} will be separated from the current bill of lading?",
    "currentBillOfLading": "The current bill of lading has been",
    "onlinePassengers": "[online customer initiated consolidation],",
    "consolidationPlease": "And single, please know.",
    "billingInformation": "The matching degree between the billing information and the details of the bill of lading is:",
    "overwrite": "Do you want to overwrite the contents of the receipt / delivery through print order?",
    "thisTransceiver": "This transceiving content format can be used for EDI sending, and it is not recommended to overwrite it",
    "minimumCharacters": "Minimum 3 characters, maximum 26 characters, no numbers, Chinese and special characters",
    "companyAddress": "Company address 2",
    "formatIs": "CA format: LNL, NLN, n is number, l is letter",
    "formatIs1": "Us format: nnnnn, nnnnnnnnn, or nnnnn-nnnn, n is a number and l is a letter",
    "formatIsOr": "The US format is nnnnn, nnnnnnnnn, or nnnnn-nnnn. N is a number and l is a letter",
    "notPerLine": "Each line must not exceed {val1} characters!",
    "maximumInput": "Enter {val1} lines at most!",
    "customerBillOfLading": "Customer / supplier bill of lading information",
    "codePublic": "Code, company English name, contact English name, contact English address, billing content",
    "matchingDegree": "Matching degree",
    "total": "Total {val1}",
    "saveAndSelect": "Save and select",
    "billOfLadingAddress": "Bill of lading address"
  }
}