export default {
  "DetailForm": {
    "offlineConfirmation": "Offline confirmation",
    "wenRayModel": "Offline confirmation is not allowed in wenrao 4PL mode",
    "pleaseSaveItFirst": "Please save the confirmation form first",
    "sent": "Sent, operation not allowed",
    "currentTariff": "Current tariff item:",
    "remove": "Remove",
    "electronicInvoice": "Electronic invoice",
    "moveIn": "Move in（",
    "invoiceType": "Invoice type",
    "transferableCapital": "Transferable tariff items:",
    "pleaseSelectThe": "Please select the expense to be moved in",
    "nonElectronicHair": "In case of non electronic invoice, the recipient address in the invoice sending address is required. Please maintain it first",
    "mailingAddress": "Ticket address",
    "cellPhoneNumber": "Mobile number: {val1}",
    "mailbox": "Email: {val1}",
    "telephone": "Tel: {val1}",
    "addressee": "To: {val1}",
    "address": "Address: {val1}",
    "provinceAndCity": "Province and city: {val1} / {val2} / {val3}",
    "corporateName": "Company name: {val1}",
    "ticketAddress": "Does the ticket address exist",
    "cellPhoneNumber2": "Mobile number: {val1}",
    "mailbox2": "Email: {val1}",
    "telephone2": "Tel: {val1}",
    "addressee2": "To: {val1}",
    "address2": "Address: {val1}",
    "provinceAndCity2": "Province and city: {val1} / {val2} / {val3}",
    "corporateName2": "Company name: {val1}",
    "customerConfirmation": "Customer confirmer",
    "pleaseSelectOr": "Please select or enter customer confirmer",
    "selectCustomer": "Select customer confirmer",
    "collectionAccountNumber": "Collection account number",
    "settlementEntity": "Settlement entity",
    "companyTitle": "Company head",
    "explain": "explain",
    "checkCollection": "Check collection and payment on behalf. After this confirmation is saved, the actual settlement company will be backfilled to the expense details",
    "pleaseInputOn": "Please enter billing description",
    "customerBilling": "Customer billing header",
    "pleaseEnterTheKnot": "Please enter settlement information",
    "customerConfirmed": "Customer confirmed",
    "bill": "Bill (BMS)",
    "invoiceApplication": "Invoicing requisition",
    "pattern": "pattern",
    "pushPortal": "Push portal confirmation",
    "confirmationNumber": "Confirmation No",
    "pleaseSelectFirst": "Please select the billing header first and click Modify",
    "pleaseSelectAKnot": "Please select a settlement company!",
    "pleaseConfirmTheJump": "Please confirm that the expense confirmation has been saved before jump!",
    "pleaseSelectAGuest": "Please select customer confirmer",
    "pleaseSelectSend": "Please check send confirmation form or check offline confirmation",
    "wenRayConfirmed": "After Wen Lei confirms that the document is sent online, it cannot be confirmed manually",
    "pleaseChooseToSend": "Please select sending mode",
    "saveAndMake": "Save and use",
    "editNew": "{val1} billing information",
    "newSuccessfully": "New successfully",
    "domesticMerchants": "No blank space is allowed in the invoice header of domestic customer / supplier, please check",
    "outOfService": "Deactivate",
    "default": "default",
    "recipientHand": "The recipient's mobile phone is no longer than 30 characters",
    "recipientHand2": "Recipient mobile phone",
    "recipientCall": "The recipient's phone length does not exceed 30 characters",
    "addresseesTelegram": "Recipient phone",
    "recipientPlace": "The recipient address is no longer than 100 characters",
    "addresseesAddress": "Recipient address",
    "recipientLength": "The recipient length does not exceed 100 characters",
    "addressee3": "addressee",
    "ticketAddress2": "The length of the ticket address shall not exceed 100 characters",
    "pleaseEnterTheLocation": "Please enter an address with a length of no more than 100 characters",
    "pleaseEnterYourEmailAddress": "Please enter the invoice header with a length of no more than 100 characters",
    "invoiceTitle": "Invoice header",
    "pleaseEnterNa": "Please enter the taxpayer identification number and the length shall not exceed 100 characters",
    "taxpayerAwareness": "Taxpayer identification number",
    "pleaseEnterSilver": "Please enter a bank account no longer than 100 characters",
    "bankAccount": "bank account",
    "pleaseEnterSilver2": "Please enter a bank name with a length of no more than 100 characters",
    "bankName": "Bank name",
    "telephoneLength": "The phone length does not exceed 30 characters",
    "generalTaxation": "General taxpayer",
    "billingType": "Billing type "
  },
  "ExpressModal": {
    "sendEveryone": "Expressmodal sender's mobile number",
    "sendingStaff": "Sender mobile number",
    "recipientHand": "Recipient mobile number",
    "recipientHand2": "Expressmodal recipient mobile number",
    "maintain": "maintain",
    "clickTheButton": "Expressmodal click button",
    "button": "Expressmodal button",
    "success": "success",
    "contactAddress": "Contact address",
    "backfillContent": "Backfill content",
    "backFillingToCustomer": "Backfill to customer",
    "pleaseEnterBit": "Please enter an 11 digit mobile phone number",
    "sendersTelegram": "Sender phone",
    "from": "Sender",
    "from2": "Sender address",
    "sender": "Sender company",
    "recipientMail": "Recipient mailbox",
    "destination": "Recipient address",
    "provinceAndCity": "Provincial and urban areas",
    "receivingParty": "Recipient company",
    "sendersLetter": "Sender information",
    "thirdPartyPayment": "Third party payment",
    "paidByTheReceiver": "Receiver's payment",
    "recipientsLetter": "Recipient information",
    "senderPays": "Sender's payment",
    "pleaseChooseCustomers": "Please select a customer / supplier",
    "expressCategory": "Express category",
    "courierNumber": "courier number",
    "expressDeliveryType": "Express type"
  },
  "Index": {
    "newConfirmation": "Add confirmation",
    "pleaseEnterItFirst": "Please enter the tariff item first",
    "expenseConfirmation": "Expense confirmation list",
    "pleaseTransferInCapital": "Please move in the tariff item!"
  },
  "Utils": {
    "wenRayConfirmed": "Wen Lei confirmed the results",
    "wenRayConfirmed2": "Wen ray confirmation status",
    "invoiceStatus": "Invoice status",
    "invoiceNo": "Invoice No",
    "billingStatus": "Billing status",
    "billNo": "Bill No",
    "customerConfirmation": "Customer confirmation date",
    "customerConfirmation2": "Customer confirmation",
    "confirmSingleIssue": "Confirmation sheet sending date",
    "confirmSingleIssue2": "Confirmation sheet sending",
    "expenseConfirmation": "Expense confirmation No",
    "wenRaySettlement": "Wenlei settlement unit",
    "orgName": "Clearing Company",
    "currencySystem": "Currency system",
    "company": "Company",
    "collect": "collect",
    "pay": "pay",
    "yes": "yes",
    "no": "no",
    "reversal": "Righting",
    "paymentType": "Receipt / payment type",
    "generated": "Generated",
    "partialGeneration": "Partial generation",
    "notGenerated": "Not generated",
    "unconfirmed": "Unconfirmed",
    "billingCompleted": "Billing completed",
    "partialBilling": "Partial Invoicing",
    "applied": "Applied",
    "partialApplication": "Partial application",
    "notApplied": "Not applied",
    "open": "yes",
    "close": "no"
  }
}