export default {
  "BusinessTypes": {
    "airExport": "Air export",
    "shippingOrder": "Shipping order",
    "collectionAndPayment": "Collection and payment",
    "costSynergy": "Cost collaboration",
    "exportRebate": "Export tax rebate",
    "airCargoHold": "Air hold",
    "holdOrder": "Occupancy Commission",
    "importByAir": "Air import ticket booking",
    "railwayTransportation": "Railway transportation import",
    "exportBySea": "Ocean export LCL",
    "airTicketing": "Air ticket",
    "lclBySea": "LCL master list",
    "railwayTransportation2": "Railway transportation export",
    "importDeclaration": "Import declaration",
    "exportDeclaration": "Export declaration",
    "landTransportation": "Land transportation import",
    "landTransportation2": "Land transportation export",
    "importByAir2": "Air import",
    "oceanFreightImport": "Ocean Freight-Import ",
    "exportBySea2": "Ocean export FCL",
    "miscellaneousShippingItems": "Sea cargo"
  },
  "FeeConstants": {
    "skateInShanghai": "Shanghai Wenlei Supply Chain Technology Co., Ltd"
  },
  "CrmConstant": {
    "everyYear": "End of each year",
    "everyEleven": "Every eleven months",
    "everyTenMonths": "Every ten months",
    "everyNineMonths": "Every nine months",
    "everyEightMonths": "Every eight months",
    "everySevenMonths": "Every seven months",
    "everySixMonths": "Every six months",
    "everyFiveMonths": "Every five months",
    "everyFourMonths": "Every four months",
    "everyThreeMonths": "Every three months",
    "everyTwoMonths": "Every two months",
    "everyMonth": "Every month",
    "excess": "excess",
    "normal": "normal",
    "overdue": "overdue",
    "businessDate": "Business date",
    "frozen": "frozen",
    "remind": "remind",
    "byBusinessCategory": "By business type",
    "byCustomer": "By customer / supplier",
    "payment": "payment",
    "collection": "Collection",
    "notInForce": "Not effective",
    "suspension": "suspension",
    "invalid": "invalid",
    "takeEffect": "take effect",
    "inquiryAndQuotation": "Inquiry and quotation",
    "goingOut": "Out activities",
    "businessCatering": "Business catering",
    "visitReception": "Visiting reception",
    "callOnSb": "call on sb.",
    "otherLinks": "Other Contacts ",
    "businessCritical": "Business key person",
    "schedule": "schedule",
    "contractInformation": "Contract information",
    "settlementInformation": "Settlement information",
    "contactInformation": "contact information",
    "bankAccount": "Bank account and billing information",
    "transmitAndReceiveTrain": "Transceiver list",
    "contactColumn": "contact list ",
    "firstKnotThenComeOut": "Knot first and then go out",
    "firstOutThenEnd": "First out and then knot",
    "letterOfCredit": "letter of credit",
    "dA": "D / A",
    "dP": "D / P",
    "draft": "Bill",
    "telegraphicTransfer": "Wire transfer",
    "mailTransfer": "Mail transfer",
    "acceptanceBill": "Acceptance bill",
    "check": "Check",
    "cash": "cash",
    "proformaInvoice": "Proforma invoice",
    "noInvoice": "No Invoicing",
    "valueAddedTax": "VAT special invoice",
    "vatGeneral": "VAT ordinary invoice",
    "fieldDelivery": "Field delivery / collection",
    "express": "express",
    "internalAccount": "Internal account",
    "externalAccount": "External account",
    "boardCompany": "Board company",
    "portAgent": "Port agent",
    "freightStation": "Freight station",
    "insuranceCompany": "insurance company",
    "courierServicesCompany": "Courier Services Company",
    "yard": "yard ",
    "inspectionCompany": "Inspection application company",
    "airlineCompany": "airline company",
    "businessUnit": "Business unit",
    "internationalProcurement": "International purchaser",
    "client": "Entrusted customer",
    "preTakeOffKnot": "Pre departure settlement",
    "peers": "Peer",
    "directCustomer": "Direct guest",
    "companyGoods": "Company goods",
    "selfEmployment": "Self employment",
    "appoint": "appoint",
    "private": "private",
    "threeCapital": "Three capital",
    "pool": "pool",
    "collective": "collective",
    "stateOwned": "state-owned",
    "internationalOrganization": "international organization",
    "publicAdministration": "Public administration, social security and social organizations",
    "cultureAndSports": "Culture, sports and entertainment",
    "healthAndSocialSecurity": "Health and social work",
    "education": "education",
    "residentServices": "Residential services, repair and other services",
    "waterConservancyAndEnvironmentalProtection": "Water conservancy, environment and public facilities management",
    "scientificResearch": "Scientific research and technology services",
    "leasingAndBusiness": "Leasing and business services",
    "realEstate": "real estate",
    "finance": "finance",
    "informationTransmission": "Information transmission, software and information technology services",
    "accommodationAndMeals": "Accommodation and catering",
    "transportation": "Transportation, storage and postal services",
    "wholesaleAndRetail": "Wholesale and retail",
    "construction": "construction",
    "electricityHeat": "Electricity, heat, gas and water production and supply",
    "manufacturing": "manufacturing",
    "mining": "Mining",
    "agricultureForestry": "Agriculture, forestry, animal husbandry and fishery",
    "railwayTransportation": "railway transportation",
    "importLandTransportation": "Imported land transportation",
    "exportLandTransportation": "Export land transportation",
    "allBusiness": "All business"
  },
  "ExpressConstants": {
    "portalArchiving": "Portal archiving",
    "file": "BMS archiving",
    "manualFiling": "Manual archiving",
    "systemArchiving": "System archiving",
    "itWillArriveOnTheFourth": "Four days",
    "everyOtherDay": "Arrive the next day",
    "itsComing": "Arrive today",
    "expressDelivery": "Express delivery",
    "specialDelivery": "Special delivery",
    "expressExpress": "Express Express",
    "hongshunExpress": "Hongshun Express",
    "lifeExpress": "Life express",
    "anjieExpress": "Anjie Express",
    "yuanZhijiecheng": "Yuan zhijiecheng",
    "speed": "D speed",
    "huitongExpress": "Huitong Express",
    "expressEveryDay": "Daily Express",
    "zhongtongExpress": "Zhongtong Express",
    "yundaExpress": "Yunda Express",
    "homeExpress": "House Express",
    "yuantongExpress": "Yuantong Express",
    "postOffice": "Postal EMS",
    "shentongExpress": "Shentong express",
    "jingdongExpress": "Jingdong Express",
    "sfExpress": "SF Express",
    "internationalPieces": "International pieces",
    "domestic": "Domestic parts",
    "orderSent": "Mailed bill",
    "unsentOrder": "Unsent bill"
  }
}