export default {
  "Routes": {
    "trailerScheduling": "Trailer scheduling list",
    "oneMomentPlease": "One moment please",
    "frontEndTransfer": "Front end transfer page",
    "mailTest": "Mail test",
    "settlementDocumentFee": "Settlement document - expense",
    "detailedStatement": "Statement - details",
    "orderNo": "Order No",
    "shipownerBusiness": "Shipowner business",
    "marineExport": "Marine export import",
    "marineExport1": "Export by sea",
    "marineExport2": "Details of shipping export full container change order and allocation",
    "marineExport3": "Application for modification of shipping export full container",
    "costAdjustment": "Expense adjustment submission pop-up box",
    "marineExport4": "Shipping export full container change order and allocation",
    "marineExport5": "Shipping export FCL bkg details",
    "marineExport6": "Shipping export FCL document",
    "marineExport7": "Template selection of full container rate for sea freight export",
    "marineExport8": "Confirmation form of shipping export full container cost",
    "marineExport9": "Shipping export FCL manifest",
    "marineExport10": "Shipping export full container booking",
    "marineExport11": "Shipping export full container cost",
    "railwayDomesticTrade": "Railway domestic trade",
    "railwayImport": "Railway import",
    "railwayExport": "Railway export",
    "marineMiscellaneous": "Domestic trade of sea cargo",
    "marineMiscellaneous1": "Import of sea cargo",
    "marineMiscellaneous2": "Sea cargo export",
    "groundService": "Ground service domestic trade",
    "groundService1": "Ground service exit",
    "selfAssemblyBySea": "Export by sea",
    "oceanFullContainer": "Full container domestic trade by sea",
    "oceanFullContainer1": "Ocean full container import",
    "marineExport12": "Full container customs declaration for sea export",
    "marineExport13": "Shipping export full container yard packing",
    "marineExport14": "Marine export full container trailer"
  }
}