export default {
  "BnCustomEntrustedDetail": {
    "declarationList": "Customs declaration list",
    "modeOfTrade": "Trade mode",
    "customsDeclarationDetails": "Customs declaration details",
    "collectionAndExemption": "Exemption",
    "totalPrice": "Total price",
    "legalQuantity": "Legal quantity",
    "finalPurpose": "Final destination country (region)",
    "quantityAndList": "Quantity and unit",
    "tradeName": "Commodity name, specification and model",
    "commodityNumber": "Item number",
    "revisionTime": "Modification time",
    "reviser": "Modified by",
    "creationTime": "Creation time",
    "declarationRemarks": "Customs declaration remarks",
    "customsBroker": "Customs broker",
    "dateOfCommission": "Date of entrustment",
    "customsDeclarationCommission": "Customs declaration entrustment No",
    "customsDeclarationCommission2": "Customs declaration entrustment details",
    "lengthCannot": "The length cannot exceed 500 characters",
    "lengthCannot2": "The length cannot exceed 20 characters",
    "cannotBeEmpty": "Cannot be empty, length cannot exceed 100 characters"
  },
  "BnCustomList": {
    "customsDeclarationCommission": "Customs declaration entrustment No",
    "number": "So no",
    "ofPer": "There are {val1} articles in total, 3 articles per page"
  },
  "BnCustomsDetail": {
    "pleaseSelectOne": "Please select a {val1} record"
  },
  "BnCustomsEntrustedList": {
    "customsDeclarationCommission": "Customs declaration entrustment list",
    "noDelivery": "No dispatch",
    "customsDeclarationStatus": "EDI customs declaration status",
    "completed": "Completed",
    "entrusted": "Entrusted",
    "noCommission": "Not entrusted",
    "delegationStatus": "Delegate status",
    "actualCustomsDeclaration": "Actual customs declaration date",
    "actualInspection": "Actual inspection application date",
    "markFinished": "Marking completed",
    "markCommissioned": "Mark delegated",
    "markNotCommissioned": "Mark not delegated",
    "declareAtCustoms": "EDI customs declaration",
    "placeAnOrder": "place an order",
    "atMost": "At most one customs declaration entrustment record can be selected",
    "pleaseChooseOne": "Please select a customs declaration entrustment record",
    "statusChange": "Status changed successfully!",
    "pleaseSelectTo": "Please select at least one customs declaration entrustment record",
    "deletionFailed": "Deletion failed, please try again later!",
    "successfullyDeleted": "Delete succeeded!",
    "systemDetection": "The system has detected that all customs declarations of your customs declaration plan {val1} have been uploaded with attachments. Is the customs declaration plan marked [completed]?",
    "ofPer": "There are {val1} articles in total, 3 articles per page"
  },
  "Config": {
    "taxCollection": "Tax collection",
    "markCode": "Shipping Marks & Remarks ",
    "manufacturer": "Manufacturer",
    "containerNumber": "Container number",
    "packageType": "Packing type",
    "netWeight": "Net weight (kgs)",
    "contractAgreement": "Contract agreement No",
    "incidental": "incidental",
    "premium": "premium ",
    "transactionMethod": "Transaction method",
    "approvalNumber": "Approval number",
    "domesticSourceOfGoods": "Domestic source of goods",
    "portOfDestination": "Port of destination",
    "arrivalCountry": "Country of arrival",
    "licenseKey": "license key",
    "exceptionalRelief": "Exceptional relief",
    "internalTentative": "Internal tentative",
    "freeTradeAgreement": "Free trade agreement",
    "nationalApprovalExemption": "National grant reduction",
    "airMaterialExemption": "Aviation material reduction",
    "charityForPovertyAlleviation": "Poverty alleviation charity",
    "disasterReliefDonation": "Disaster relief donation",
    "ownFunds": "Own funds",
    "incentivePrograms": "Encouraging projects",
    "commonwealCollection": "Public Welfare Collection",
    "winningTheLoan": "Loan winning",
    "loanProject": "Loan project",
    "onshoreOil": "Onshore oil",
    "offshoreOil": "Offshore oil",
    "explorationAndDevelopment": "exploration and development",
    "foreignEnterprise": "foreign enterprise",
    "sinoForeignCooperation": "Sino foreign cooperation",
    "sinoForeignJointVenture": "Sino foreign joint venture",
    "hongKongAndMacao": "Hong Kong and Macao OPA",
    "borderSmallAmount": "Border small",
    "feedProcessing": "Feed processing",
    "processingWithSuppliedMaterials": "Incoming processing",
    "processingEquipment": "Processing equipment",
    "product": "ITA products",
    "newDisplay": "New display device",
    "integratedCircuit": "Integrated circuit",
    "domesticEquipment": "Domestic equipment",
    "oceanGoingShip": "Ocean going ship",
    "vehicleCharacteristics": "Vehicle characteristics",
    "localization": "Localization",
    "pelagicFishery": "Pelagic fishery",
    "disabled": "Disabled",
    "infrastructure": "infrastructure",
    "majorTechnology": "Major technical equipment",
    "majorProjects": "Major projects",
    "technicalTransformation": "Technical transformation",
    "scienceAndEducationSupplies": "Science and education supplies",
    "otherRegions": "Other regions",
    "bondedArea": "bonded area",
    "specificArea": "Specific area",
    "otherStatutory": "Other statutory",
    "gratuitousAid": "Gratuitous assistance",
    "partsLevy": "Parts tax",
    "vehicleTax": "Vehicle tax",
    "generalTaxation": "General taxation",
    "natureOfTaxExemption": "Nature of levy and exemption",
    "formOfSettlementOfExchange": "form of settlement of exchange",
    "deliveryNumbers": "Delivery Numbers ",
    "meansOfTransport": "Name of means of transport",
    "exportProcessing": "Export processing zone",
    "bondedPortArea": "Bonded port area",
    "logisticsPark": "Logistics Park",
    "logisticsCentre": "Logistics Centre",
    "specialBorder": "Border special customs operation area",
    "fullTransport": "All modes of transportation",
    "otherTransportation": "Other transportation",
    "bondedWarehouse": "Bonded warehouse",
    "mailTransportation": "Mail transportation",
    "transportAviation": "transport aviation",
    "roadTransport": "road transport",
    "waterTransportation": "Waterway transportation",
    "superviseWarehouse": "Supervised warehouse",
    "nonBondedZone": "Non bonded area",
    "typeOfShipping": "type of shipping",
    "declarationDate": "Declaration date",
    "exportDate": "Export date",
    "recordNumber": "Record No",
    "exportPort": "Export port",
    "preRecorded": "Pre entry No",
    "postcode": "Zip code",
    "unitAddress": "Unit address",
    "dateOfCompletion": "Filling date",
    "entryUnit": "Entry unit",
    "entryClerk": "Entry Clerk",
    "maximumBitSize": "Up to 3 decimal places"
  },
  "Constants": {
    "toBeReceived": "To be received",
    "received": "Received"
  }
}