export default {
  "CtnListInfo": {
    "woodenPacking": "Wood packaging details",
    "maximumBitSize": "Up to 3 decimal places",
    "onlyInput": "Only numbers up to 10 digits can be entered",
    "onlyInput2": "Only numbers up to 12 digits can be entered",
    "onlyInput3": "You can only enter positive integers with no more than 10 characters",
    "onlyInput4": "Only numbers up to 16 characters can be entered",
    "required": "Required item. Only English, numbers and English symbols can be entered. The length cannot exceed 1000 characters",
    "cargoDetails": "HS code of goods details",
    "noOperation": "No operation permission",
    "containerization": "Container loading information",
    "bromide": "Bromide",
    "synchronousContainerization": "Synchronous container",
    "dielectric": "dielectric",
    "suchAsProcessing": "Such as processing and reinforcement",
    "suchAsFumigation": "Such as fumigation and quarantine",
    "onlyInput5": "You can only enter no more than 200 characters",
    "notPerLine": "No more than 5 characters per line!",
    "maximumInput": "Enter up to 50 lines!",
    "onlyInput6": "You can only enter up to 10000 characters",
    "synchronousMemory": "There are containers with the same seal number and different container type in synchronization!",
    "export": "export",
    "generateByBox": "Generate goods details by box",
    "fromContainer": "Synchronize from container",
    "singleContainer": "Maintain the shipping mark according to the single container",
    "containerLetter": "Container information",
    "suchAsCurrentGoods": "If there is a value in the current goods details, it will be overwritten",
    "confirmBySet": "Are you sure to generate cargo details by container?",
    "containerTrain": "Container list",
    "onlyInput7": "You can only enter no more than 5000 English characters",
    "lengthNotAllowed": "Length cannot exceed 2000 characters",
    "required2": "Required item, up to 3 decimal places",
    "required3": "Required item. Only 10 digits or less can be entered",
    "required4": "Required item. Only 12 digits or less can be entered",
    "requiredItem": "Required item. Please enter a legal packaging unit",
    "requiredItem2": "Required item. Please enter the legal number of pieces",
    "cargoDetails2": "Cargo details"
  },
  "CtnListInfoForAI": {
    "manufacturers": "Name and address of manufacturer",
    "onlyInput": "You can only enter numbers up to 7 digits, up to 2 decimal places",
    "englishName": "English name",
    "onlyInput2": "Only numbers up to 3 digits can be entered",
    "maximumBitSize": "Up to 2 decimal places",
    "onlyInput3": "You can only enter no more than 180 English characters",
    "required": "Required item. You can only enter numbers with 6-10 characters",
    "onlyInput4": "You can only enter numbers of 6-10 characters",
    "atLeastOne": "There is at least one loading message!",
    "required2": "Required item. You can only enter a number of 6 characters",
    "information": "Item information:",
    "shippingMark": "Shipping mark:",
    "fromSynchronization": "Sync from Si",
    "youWillSync": "You will synchronize the container and rough body information of the corresponding Si. If you have maintained the cargo details of the container on the current page, it will also be cleared. Please know",
    "fromSyncSet": "Synchronize container information from Si",
    "information2": "Item information",
    "shippingMark2": "Tracing mark",
    "pleaseEnterBit": "Please enter 2-15 letters or numbers",
    "notDetected": "No data detected, please check the data and try again.",
    "byMaintenance": "Maintain by item",
    "unifiedMaintenance": "Unified maintenance",
    "caseByCaseMaintenance": "Maintenance by box",
    "yiYi": "[a-za-z I - ()+",
    "volume": "Volume (CBM)",
    "grossWeight": "Gross weight (kgs)",
    "synchronization": "Synchronous Si"
  },
  "DocumentsTipModal": {
    "thereIsAlready": "If there is a bill of lading with [locked document], click [know and process] to unlock it automatically.",
    "andComparison": "Comparison with HBL Si:",
    "andComparison2": "Comparison with MBL Si:",
    "latestChanges": "Latest change time:",
    "knowAndPunish": "Know and handle",
    "synchronizationSucceeded": "Synchronization succeeded",
    "gotIt": "got it",
    "informationChange": "Information change prompt",
    "afterChange": "After change",
    "beforeChange": "Before change",
    "orderInformation": "Order information",
    "fieldName": "Field name",
    "handler": "Handler"
  },
  "ISF": {
    "timeGrid": "In case of passport - the format is xxxxxxxxxxxxxxxxx (15 digits), and XX is capital English letters or numbers",
    "theFormatIs": "In SCAC, the format is xxxx (must be 4 digits), and X is a capital English letter",
    "theFormatIs2": "When SSN, the format is nnn-nn-nnnn (3 bits - 2 bits - 4 bits), and N is a number",
    "theFormatIs3": "In CBP, the format is nnnn-nnnnn (6-5 bits), and N is a number",
    "theFormatIs4": "The format of EIN is nn-nnnnnnnxx (2-9 digits), n is a number, and XX is a capital letter or number. If there is no suffix, use \"00\" in the last two \"XX\" characters",
    "viewReceipt": "View receipt",
    "customs": "customs:",
    "sendOut": "send out",
    "receiptStatus": "Receipt status:",
    "toSend": "To send:",
    "noMoreThanMinutes": "No feedback received for more than 30 minutes",
    "warning": "Warning",
    "thereIsAMistake": "There are errors",
    "receiving": "Receiving",
    "toBeSent": "To be sent",
    "timedOut": "Timed out",
    "bitWordRequired": "Must be 4 characters (alphanumeric)",
    "upstreamFreightForwarder": "Carrier code number of the upstream freight forwarder (to be filled in when the freight forwarder type includes the colorator scenario)",
    "upstreamFreightForwarder2": "Upstream freight forwarder doc No. (it needs to be filled in when the freight forwarder type includes the colorator scenario)",
    "freightForwardingOrderType": "Freight forwarding document type:",
    "nvocc": "NVOCC (freight forwarder) code, self declaration number",
    "containerCargo": "Container cargo",
    "onlyInput": "Only more than 7 digits can be entered",
    "containerInformation": "Container information",
    "containerInformation2": "Container information",
    "shipCode": "Ship code (i.e. the identification number of the ship registered in the international maritime organization, IMO is the abbreviation of the International Maritime Organization)",
    "lengthLimit": "The length is limited to 2-10 characters",
    "lengthLimit2": "The length is limited to 2-5 characters",
    "shipownersOrderNo": "Shipowner's number (SCAC number needs to be removed)",
    "forwarderNo": "Freight forwarder No. (SCAC No. needs to be removed)",
    "essentialInformation": "Basic information - content",
    "mostSupported": "Supports up to 10 uppercase English characters",
    "detailedInformation": "Details - fourth column",
    "detailedInformation2": "Details column 4",
    "detailedInformation3": "detailed information",
    "supportNumbers": "Support digital input",
    "detailedInformation4": "Details - third column",
    "detailedInformation5": "Details column 3",
    "detailedInformation6": "Details - second column",
    "transceiverSection": "Transceiver - second column",
    "detailedInformation7": "Details - first column",
    "transceiverSection2": "Transceiver - first column",
    "singleInformation": "H order information",
    "underSingleInformation": "H order information - next",
    "singleInformation2": "H order information - up",
    "maximumInput": "Enter up to 60 digits",
    "insuranceCompany": "DEPOSIT No. of insurance company",
    "maximumInput2": "Enter up to 3 digits",
    "insuranceCompany2": "Insurance company code",
    "marginHolding": "Type of margin holder:",
    "marginCategory": "Deposit type:",
    "identityInformation": "ISF identity - last line",
    "identityInformation2": "ISF identity - last line",
    "marginHolding2": "Certificate No. of deposit holder",
    "marginHolding3": "Certificate type of deposit holder:",
    "identityInformation3": "ISF identity - fourth column",
    "identityInformation4": "ISF identity - fourth column",
    "passportCountry": "Passport country",
    "consignees": "Name and address of consignee",
    "consignees2": "Consignee's U.S. return number type:",
    "identityInformation5": "ISF identity - third column",
    "identityInformation6": "ISF identity - third column",
    "identityInformation7": "#ISF identity - third column",
    "identityInformation8": "#ISF identity - second column",
    "importers": "Importer of record number ",
    "importers2": "Importer's customs registration number type:",
    "identityInformation9": "ISF identity - second column",
    "identityInformation10": "ISF identity - second column",
    "importerSafety": "Customs registration number of importer's security declaration",
    "importerAn": "Type of customs registration number for Importer's security declaration:",
    "identityInformation11": "ISF identity - first column",
    "identityInformation12": "ISF identity - first column",
    "unconventionalGoods": "Unconventional cargo subcategory",
    "transitNumber": "Transit number",
    "transitCountries": "transit countries ",
    "typeOfGoods": "Type of goods:",
    "identityInformation13": "ISF identity - first line",
    "identityInformation14": "ISF identity - first line",
    "identityInformation15": "ISF identity information",
    "identityInformation16": "ISF identity information",
    "bookingAgent": "Name and address of booking agent",
    "sellersName": "Name and address of the seller",
    "buyersName": "Name and address of the buyer",
    "packingAddress": "Packing address",
    "lclCompany": "Name and address of LCL company",
    "locationOfDelivery": "Name and address of the place of delivery",
    "deliveryOfGoods": "Name and address of the party delivering the goods",
    "placeOfDelivery": "Name and address of the place of delivery / name and address of the party to whom the goods are delivered",
    "notifiers": "Name and address of the notifier",
    "shippers": "Name and address of shipper",
    "informationFirst": "Parties information - first column",
    "information": "Parties information",
    "information2": "Parts information",
    "locationOfDischarge": "Customs clearance location code at the place of discharge",
    "portOfDestination": "Customs clearance location code of destination port",
    "portInformation": "Port information - column 3",
    "portInformation2": "Contents of the fourth column of port information",
    "port": "Port container",
    "afterArrivingInTheUnitedStates": "Estimated arrival time of the first port of call after arriving in the United States",
    "theLastOne": "Estimated sailing time of the last non-U.S. port of call",
    "locationOfDischarge2": "Estimated time of arrival at the place of discharge",
    "portOfDestination2": "Estimated time of arrival at the port of destination",
    "portOfDeparture": "Estimated sailing time at the port of departure",
    "locationOfReceivingPlace": "Estimated sailing time at the receiving place",
    "portInformation3": "Port information - second column",
    "nonAmerican": "Non US port of discharge",
    "afterArrivingInTheUnitedStates2": "The first port of call after arriving in the United States",
    "theLastOne2": "The last non-U.S. port of call",
    "placeOfDischarge": "Place of delivery in the bill of lading",
    "portInformation4": "Port information - first column",
    "portInformation5": "The third column of port information",
    "portInformation6": "Port information",
    "maximumBitWord": "Up to 4 characters!",
    "sendingForm": "ISF sending form",
    "checkInformation": "Tick information - second line",
    "checkInformation2": "Check message - sending form",
    "usEntry": "Type of entry into the United States:",
    "checkInformation3": "Tick Info - isftoe",
    "canadian": "Type of entry into Canada:",
    "checkInformation4": "Tick Info - acitoe",
    "checkInformation5": "Tick info amstoe",
    "checkInformation6": "Tick information - first line",
    "checkInformation7": "Tick Info - ISF",
    "checkInformation8": "Tick Info - ACI",
    "checkInformation9": "Tick information AMS",
    "sendOverseas": "Send overseas agent status:",
    "messageStatus": "Message status:",
    "sendOverseas2": "Send overseas agent",
    "operationFailed": "Operation failed. ISF must be checked for sending overseas agent",
    "sorryWhen": "Sorry, the current overseas operation agent does not support sending",
    "operationFailed2": "Operation failed, check at least one anti-terrorism manifest",
    "modifyMessage": "Modify message",
    "pleaseCorrectItFirst": "Please correct the current page data first",
    "sendOverseas3": "Sending overseas agent succeeded",
    "confirm": "Are you sure to delete?",
    "deleteCounterTerrorism": "Delete counter terrorism manifest",
    "failInSend": "fail in send",
    "sending": "Sending"
  },
  "MergeOrderButton": {
    "orderNoWithdrawal": "Order No. / bill of lading No",
    "selectAll": "Select all",
    "fieldVerification": "Field verification consistent",
    "unopenedOrder": "Unopened order",
    "unlimited": "unlimited",
    "hasItBeenRemoved": "Split order",
    "isItLocked": "Has the order been locked",
    "customerConsolidation": "Customer consolidation",
    "agentConsolidation": "Agent consolidation",
    "largeAgentAnd": "Large agent consolidation",
    "consolidationScenario": "Consolidation scenario",
    "toBeCombinedAndListedSeparately": "List of documents to be consolidated",
    "consolidation": "Consolidation",
    "confirmationAndOrderConsolidation": "Confirmation and order consolidation",
    "selectConsolidation": "Select consolidation order",
    "pleaseChoose": "Please select bill of lading",
    "screen": "screen",
    "pleaseBookTheSpaceFirst": "Please confirm the booking first",
    "rpaError": "There is robot replenishment, and consolidation is not allowed",
    "jiyidaSystem": "After the synchronization of Jiyida voucher preparation, it is unable to split and consolidate the voucher"
  },
  "Receipt": {
    "customsReceipt": "Customs receipt details",
    "noDataAvailable": "&nbsp; No data",
    "scheme": "Scheme:",
    "stateDescription": "Status description or reason:",
    "receiptTime": "Receipt time:",
    "close": "close",
    "receiptCode": "Receipt code:",
    "viewSend": "View sent message",
    "receiptType": "Receipt type:",
    "detailedInformation": "Details Code:",
    "receiptDetails": "Tradetech receipt details",
    "see": "see",
    "specificFields": "Specific field description",
    "receivingStatus": "Receiving status"
  },
  "Si": {
    "robotCompensation": "Robot compensation",
    "appendix": "appendix",
    "lockList": "Lock list",
    "unlocking": "Unlock",
    "onlineFeeding": "#Online feeding",
    "unlockPortal": "Unlock portal Si",
    "confirm": "Are you sure to delete this consolidated bill of lading? After confirmation, the consolidation relationship of all consolidated bills of lading will be unbound",
    "confirmDeletion": "Are you sure to delete this document?",
    "saveRelease": "Successfully saved release notes",
    "cannotBeEmpty": "HBL no cannot be empty",
    "essentialInformation": "Basic information container",
    "essentialInformation2": "Basic information component",
    "essentialInformation3": "Basic information split line",
    "onlyInput": "You can only enter no more than 50 characters",
    "onlyInput2": "Only English characters can be entered",
    "essentialInformation4": "Basic information second column container",
    "essentialInformation5": "Basic information under the second column",
    "essentialInformation6": "Basic information on the second column",
    "essentialInformation7": "Basic information first column",
    "pleaseEnterTo": "Please enter up to 3 decimal places",
    "pleaseEnterTheNumber": "Please enter a number. The maximum number cannot exceed 12 digits",
    "pleaseEnterAnInteger": "Please enter an integer with a maximum of 10 digits",
    "containerInformation": "Contents of container information",
    "releaseNotes": "Release note container",
    "releaseNotes2": "Remarks on release",
    "noRelease": "No release",
    "releaseNotes3": "Release notes",
    "issuingInformation": "Issuing information",
    "issuingInformation2": "Issuing information container",
    "shipInformation": "Ship information content",
    "shipInformationContent": "Ship information container",
    "partyInfo2": "Party information",
    "partyInfo": "Party information content",
    "partyInfoContent": "Party information container",
    "onlyInput3": "You can only enter integers from 0 to 10",
    "gateway": "Portal Si hscode",
    "twoWayShip": "(name of the second ship / voyage)",
    "bookingVessel": "(name of booking vessel / internal voyage)",
    "bookingVessel2": "(name of booking vessel / external voyage)",
    "issuingInformation3": "Content of issuing information",
    "issuingInformation6": "Issuing information column 2",
    "fromSingleSynchronization": "Single synchronization from H",
    "onYourPage": "There are content modifications on your page, please save before synchronizing!",
    "totalAll": "Total all h documents",
    "totalAll2": "Total h documents of all sub documents",
    "selectSynchronization": "Select synchronization source:",
    "youWillSync": "You will synchronize the following information in the H bill of lading of the order: description, shipping mark and remarks",
    "sendingOrder": "Send m single AMS",
    "sendOut": "Send EDI",
    "internalPrinting": "{val1}: the similarity between the company name in the billing content and the company name in the transceiver details is too low",
    "continue": "Continue sending",
    "pushSucceeded": "Push succeeded",
    "supplementaryFields": "Supplementary fields",
    "cannotBeEmpty2": "MBL no cannot be empty",
    "essentialInformation8": "Under basic information",
    "essentialInformation9": "2 in the second column of basic information",
    "essentialInformation10": "Basic information - split line",
    "onlyInput4": "You can only enter no more than 100 characters",
    "open": "yes",
    "close": "no",
    "hasPlanFee": "Display freight",
    "applicableOnly": "SCAC code (hsdg only)",
    "essentialInformation11": "1 in the second column of basic information",
    "essentialInformation12": "Basic information in the second column",
    "onlyInput6": "You can only enter no more than 60 characters",
    "essentialInformation13": "Basic information container",
    "sameAsSlaveRecord": "Synchronous sending and receiving from recording",
    "containerInformation2": "Container information container",
    "referenceResources": "Reference bkg",
    "shipInformation2": "Ship information",
    "applicableOnly2": "SCAC code (hsdg only):",
    "receivingTime": "Draft receiving time:",
    "theComparisonIsConsistent": "Consistent comparison",
    "thereAreDifferences": "There are inconsistencies",
    "comparison": "MBL draft comparison",
    "cabinet": "(cabinet)",
    "alreadyEquipped": "(equipped)",
    "splitTheBill": "Split order",
    "rpaSplitError": "Splitting is not allowed if there is robot replenishment",
    "pleaseInputTheBox": "Please enter the box number to query",
    "pleaseSaveItFirst": "Please save the bill of lading first!",
    "cancelAll": "Cancel all split orders",
    "withdrawPressCabinet": "Withdrawal of order for cabinet disassembly",
    "orderByCabinet": "According to cabinet disassembly order",
    "splitOrderRetention": "Keep origin number for splitting",
    "subtotal": "Subtotal:",
    "confirmThatItWillComeOff": "Are you sure that {val1} will be separated from the current bill of lading?",
    "state": "EDI status",
    "billOfLadingNo": "Bill of lading No",
    "receiptDetails": "Si receipt details",
    "ourCompanyCutOffTheBill": "Our cut-off time:",
    "appendixInformation": "Appendix information",
    "releaseDetails": "Release details",
    "releaseStatus": "Release status",
    "cancelDeletion": "Cancel (delete)",
    "sentSuccessfully": "Sent successfully",
    "theBillOfLadingIsIssued": "The bill of lading is issued in sea way. Please release the bill first",
    "passed": "Passed",
    "onYourPage2": "There are content modifications on your page, please save before sending",
    "pleaseSaveItFirst2": "Please save before sending",
    "exportSucceeded": "Export succeeded",
    "onYourPage3": "The content on your page has been modified. Please save it before exporting",
    "pleaseSaveItFirst3": "Please save before exporting",
    "portalUnlocking": "Portal unlocked successfully",
    "withdrawalSuccessful": "Withdrawal succeeded",
    "unlockingSucceeded": "Unlock succeeded",
    "orderLockedSuccessfully": "Order locking succeeded!",
    "youWillSync1": "You will synchronize the following information in the H order: cargo description, shipping mark, total gross body and packaging, container list and cargo details",
    "fromBeingMerged": "Synchronize from the H order of the merged order",
    "chineseSymbols": "Unbound",
    "afterSeparation": "After leaving, remember to check the container name and shipping mark information of the current consolidated bill of lading.",
    "breakAwayFromTheCurrent": "Break away from the current bill of lading?",
    "confirmWill": "Confirm will",
    "lockInformation": "Lock information",
    "releaseInformation": "Unlock information",
    "thisIsASinglePhase": "The bill of lading related information has been locked",
    "thisBillOfLadingLetter": "The bill of lading information has been unlocked",
    "current": "(current)",
    "unbound": "Unbound",
    "cancellationAndConsolidation": "Successfully unbind the consolidation order",
    "confirmRelease": "Are you sure to cancel all consolidation relationships?",
    "recoveryAndConsolidation": "Recovery and consolidation",
    "noSingleBinding": "There is no consolidated single binding relationship. Please restore the consolidated single binding relationship first",
    "of": "&nbsp;  & nbsp;",
    "currentBillOfLading": "The current bill of lading has been consolidated into the order & nbsp;",
    "billOfLading1": "Bill of lading",
    "chuansiyueNo": "Chuansiyue No",
    "historicalConsolidation": "Historical consolidation relationship",
    "currentBillOfLading1": "There is no consolidation relationship record in the current bill of lading. If there is no need, you can delete it manually.",
    "jiyidaSystem": "Jiyida voucher preparation synchronization",
    "jiyidaSycn": "Jiyida voucher preparation synchronization",
    "currentPage": "There are unsaved changes on the current page. Please save before the current operation.",
    "pleaseBookTheSpaceFirst": "Please book the space first",
    "operationSuccessful": "Operation succeeded"
  },
  "Root": {
    "counterTerrorismManifest": "Counter terrorism manifest / security declaration",
    "orderInformation": "Please pay attention to the order information change prompt",
    "allIn": "All sub orders in MBL Si have been assigned the reserved MBL no at the same time. Please check whether it needs to be modified"
  }
}