export default {
  "Order_record": {
    "chineseSymbols": "{val1}/order/delete？ casenumbers={val2}",
    "paymentStatus": "Payment status",
    "expenseType": "Expense type",
    "modifyPayment": "Modify payment status",
    "onlyInput": "You can only enter no more than 2000 characters",
    "heapFreeDays": "Heap free days",
    "freeDays": "Free days",
    "operationAgent": "Operation agent is required",
    "onlyInput2": "You can only enter no more than 120 characters",
    "bookingInformation": "Booking information",
    "bookingPackage": "Booking module",
    "customerType": "Customer type",
    "placeOfInvoice": "Invoice address",
    "mailingAddress": "Mailing address",
    "essentialInformation": "Basic information - below",
    "code": "MD5 code",
    "totalAmount": "Total amount",
    "bookingPayment": "Booking - place of payment",
    "otherInformation": "Other information",
    "cargoInformation": "Cargo information",
    "serviceLetter": "Service item information",
    "bookingOutOrder": "Booking - order issuing method",
    "delegatedIssue": "Delegation - issuing method",
    "billOfLadingInformation": "Bill of lading information",
    "billOfLadingComponents": "Bill of lading component",
    "portComponents": "Port components",
    "routeInformation": "Route information - second column",
    "routeInformation2": "Route information - first column",
    "routeInformation3": "Route information",
    "chineseSymbols2": "{val1}/order/delete？ casenumbers={val2}",
    "bookingInformation2": "Booking information - booking information",
    "bookingModule": "Booking assembly - right",
    "bookingModule2": "Booking assembly - left",
    "chineseSymbols3": "{val1}/order/delete？ casenumbers={val2}",
    "chineseSymbols4": "{val1}/order/delete？ casenumbers={val2}",
    "onlyInput3": "You can only enter no more than 50 non Chinese characters"
  },
  "Booking_info": {
    "shippingAgentStatus": "Shipyard EDI status",
    "settlementAgent": "Settlement agent EDI status",
    "shippingCompanyForm": "EDI status of shipping company",
    "bookingSnapshot": "Booking snapshot",
    "selectTheMeter": "Select the plan",
    "goToBookTheCabin": "To book a cabin",
    "otherPlans": "Other plans",
    "onlineBooking": "Online booking",
    "bookingPlan": "Booking Plan No",
    "bargeInformation": "Barge information - container",
    "bargeInformation2": "Barge information",
    "bookingInformation": "Booking information - booking confirmation information",
    "bookingConfirmation": "Booking confirmation information",
    "containerBooking": "Container - booking information",
    "bookingInformation2": "Booking information - cargo information",
    "bookingRemarks": 'Booking remarks (internal)',
    "bookingInstructions":'Booking instructions (output)',
    "bookingInformation3": "Booking information selection",
    "remarksComponent": "Remarks component",
    "containerBooking2": "Container - booking information - first",
    "containerBooking3": "Container - booking information - third",
    "bookingInformation4": "Booking information - Bill of lading information",
    "bookingInformation5": "Booking information - barge information",
    "bookingInformation6": "Booking information - port information",
    "sendingAndReceivingCommunication": "Transceiver information",
    "bookingInformation7": "Booking information - transceiver information",
    "transceiverGroup": "Transceiver assembly",
    "airlineInformation": "Aviation company information",
    "bookingInformation8": "Booking information - airline information",
    "bookingInformation9": "Booking information - bkg container",
    "bookingInformation10": "Booking information - bkg",
    "bookingInformation11": "Booking information - booking information selection",
    "shipNameCode": "Ship name code",
    "shipNameExternal": "Vessel name / external voyage / internal voyage",
    "cargoInformation": "Cargo information component",
    "boxTypeAndQuantity": "Box volume assembly",
    "bookingAndReservation": "Booking time",
    "motherShipAgency": "Mother ship agent",
    "bookingConfirmation2": "Booking confirmation information component right",
    "shipownersReference": "Owner's reference number",
    "bookingConfirmation3": "Booking confirmation information component left",
    "youAreNotAllowedToLose": "Chinese is not allowed",
    "aviationCompanyInformation": "Airline information - address of the Contracting Party",
    "pleasePayAttentionToTheFoundation": "Please maintain it in the master data shipping schedule",
    "lengthCannot": "The length cannot exceed 35 characters",
    "contractingParty": "Contract party code",
    "bookingInformation12": "Booking information - Remarks",
    "onlyInputAllowed": "Only 3-bit positive integers are allowed",
    "voyage": "voyage",
    "sendOut": "EDI send",
    "sendElectronics": "Send electronic packing list",
    "sendBooking": "Send booking EDI"
  },
  "Operate_record": {
    "mailTitle": "Mail title",
    "solicitationAgent": "Solicitation agent contact",
    "number": "HBL No",
    "number2": "MBL No",
    "expectedPacking": "Estimated packing time",
    "secondPass": "Two way ATD",
    "packingArea": "Packing area",
    "secondPass2": "Two way ETD",
    "nameOfTwoWayShip": "Name of second voyage / voyage",
    "changjiangLand": "(special for Yangtze River area)",
    "shippingDateInformation": "Shipping date information 2 empty",
    "bargeInformation": "Barge information and shipping date",
    "shippingInformation": "Shipping schedule information 2",
    "nameOfBarge": "Barge Name Voyage",
    "bargeInformation2": "Barge information service item linkage",
    "boxNo": "Bkg box",
    "cargoInformation": "Cargo information - cargo information",
    "orderSupplement": "Order supplementary entry component",
    "informationOnTheRight": "Under right information",
    "pickUpInformation": "Pick up information component",
    "informationOnTheRight2": "Right information",
    "informationOnTheRight3": "On the right information",
    "informationOnTheRight4": "Right information upper right",
    "informationOnTheRight5": "Right information upper left",
    "bookingInformation": "Booking information 2",
    "bookingInformation2": "Booking information shipping company information",
    "billOfLadingInformation": "Bill of lading information 2",
    "portInformation": "Port information 2",
    "shippingInformation2": "Shipping company information",
    "stationContact": "Station contact"
  },
  "Audit_record": {
    "bookingRequirements": "Booking requirements - Bill of lading information",
    "containerBooking": "Container - booking requirements",
    "bookingRequirements2": "Booking demand - port information - service item linkage",
    "portInformation": "Tab port information & Barge Information & bill of lading information",
    "bookingRequirements3": "Booking demand - port information",
    "portInformation2": "Tab port information",
    "containerCargo": "Container cargo information",
    "bookingRequirements4": "Booking requirements - airline information",
    "bookingRequirements5": "Booking demand - next",
    "bookingRequirements6": "Booking requirements - upper",
    "bookingRequirements7": "Booking requirements - upper - Components",
    "billOfLadingInformation": "Tab - Bill of lading information",
    "billOfLadingComponents": "Tab bill of lading component",
    "bargeInformation": "Tab barge information",
    "bargeAssembly": "Tab barge components",
    "bookingRequirements8": "Booking demand - sending and receiving information",
    "secondaryInformation": "Secondary information",
    "mainInformation": "Main information",
    "portComponents": "Tab port components",
    "bookingPlan": "Tab - booking plan",
    "sendingAndReceivingCommunication": "Tab - send and receive messages",
    "transceiverGroup": "Tab transceiver component",
    "bookingAndSending": "Booking EDI sender (special for South China)",
    "aviationCompanyInformation": "Tab - airline company information & Review Notes",
    "aviationDivisionComponents": "Tab - Aviation Division components"
  },
  "Audit_record_snapshot": {
    "secondaryInformation": "Secondary information",
    "mainInformation": "Main information"
  }
}