export default {
  "CopyFeeModal": {
    "list": "{val1} list",
    "confirmReplication": "Confirm replication",
    "updateHeader": "Update header - entrusted customer",
    "originalValueIntroduction": "Original value introduction",
    "pleaseSelectAReference": "Please select the import method",
    "introductionMode": "Introduction mode",
    "historicalOrders": "Historical order number",
    "pleaseSelectCalendar": "Please select historical order",
    "planToDealWith": "Planned payable",
    "planReceivable": "Planned receivable"
  },
  "FeeDetail": {
    "methodShould": "Dodel method, payable expenses, freight",
    "methodShould2": "Dodel method, payable expenses, cost",
    "methodShould3": "Dodel method, payable expenses",
    "methodReceivable": "Dodel method, charges receivable",
    "requestInterface": "Request interface",
    "afterModification": "Prompt to save after modification",
    "entryCompleted": "Input completion button",
    "testAdd": "Test the new interface onaddfeerow",
    "feeDeletion": "Expense deletion",
    "zigongCity": "Zigong Tianli tools and materials Co., Ltd",
    "zhouTeng": "Zhou Teng",
    "changeOrder": "Change order",
    "towardsTheFuture": "Filling the future",
    "shenzhenCity": "Shenzhen chongxiang Future Technology Co., Ltd",
    "tianjinTianyou": "Tianjin Tianli Co., Ltd. (hereinafter referred to as)",
    "tianjinTianyou2": "Tianjin Tianli Technology Co., Ltd",
    "freightForwardingOperation": "Freight forwarder operating system 1 Group Corporation (hereinafter referred to as) 1",
    "airFreight": "Air freight",
    "testSelection": "Test selection fee name logic",
    "theEditorCalled": "The returned charges have been edited. Please resubmit or refresh the page first!",
    "feeDetails": "Cost details",
    "pleaseChooseOne": "Please select an expense data to copy!",
    "existingInsured": "There are saved expenses. Are you sure you want to delete them?",
    "existingIssued": "There are sent charges, which cannot be deleted",
    "includeLock": "The locked charges cannot be deleted",
    "pleaseSelectAtLeast": "Please select at least one {val1} expense to delete!"
  },
  "FeeDetailDrawer": {
    "listOfDocuments": "Document list",
    "creationDate": "Creation date",
    "relatedAmount": "Related amount",
    "documentStatus": "Document Status ",
    "documentNumber": "Document No",
    "documentType": "Document type",
    "operationDepartment": "Operation Department",
    "salesDepartment": "Sales Department",
    "masterOrderNo": "Main doc No",
    "businessOrderNo": "Business order No"
  },
  "FeeDetailModel": {
    "equivalentStandard": "Converted into functional currency"
  },
  "FeeDetailPresenter": {
    "independentSettlement": "Internal settlement cannot be checked for independent settlement"
  },
  "FeeDetailService": {
    "testReplication": "Test copies shall be received and payable",
    "testInterface": "Testing the copyplanpaylist interface",
    "pleaseCheckTheWords": "Please check the fields",
    "testInterface2": "Testing the copypaylist interface",
    "testInterface3": "Test copyreclist interface",
    "yeQichen": "Ye Qichen"
  },
  "FeeHeadInfo": {
    "displayAdjustment": "Display adjustment cost",
    "displayReversal": "Righting",
    "displayNormal": "ordinary",
    "adjustedGross": "Adjusted gross profit",
    "equivalent": "[equivalent {val1}: -]",
    "totalGrossProfit": "Total gross profit",
    "noDataAvailable": "No data yet!",
    "chineseSymbols": "【{val1}: -】",
    "chineseSymbols2": "【",
    "equivalent2": "Equivalent to USD",
    "equivalent3": "Equivalent",
    "displayTariff": "Display tariff:"
  },
  "FeeOperations": {
    "synchronizationPlan": "Synchronization plan cost",
    "reasonsForLoss": "Reasons for loss",
    "reasonsForLossInfo": "Description of loss classification",
    "close": "close",
    "shortcutOperation": "Shortcut operation",
    "adjustWenRay": "Adjust the settlement unit of Wenlei",
    "adjustmentSettlement": "Adjust settlement unit",
    "rectification": "Righting",
    "batchChangeTax": "batchChangeTax",
    "select": "Please select",
    "input": "Please enter loss description"
  },
  "FunctionButton": {
    "paymentApplication": "Payment application",
    "pleaseCheckNone": "Please check the expense operation without payment request",
    "checkedFee": "The checked expense {val1} has been requested. Please check it",
    "currentPage": "The current page has been modified. Please save it first",
    "isThePopUpWindowCorrect": "Does the pop-up window exist",
    "nothing": "Nothing",
    "fastInternalKnot": "Quick knot button",
    "settlementUnit": "The settlement company is the same before and after adjustment, and cannot be adjusted",
    "modifyRemarks": "Modify comments",
    "feeOfChoice": "The selected expense contains adjustment temporary expense, unable to operate",
    "includeSubOrders": "It includes sub doc expenses and cannot be reversed. Please go to the sub doc for operation",
    "selectedFees": "The selected expense contains reversal expense and cannot be operated",
    "positiveOnly": "Reversal is only applicable to locked expenses. Please check again",
    "adjustmentSettlement": "Adjustment settlement company is only applicable to non locked expenses. Please check again",
    "internalKnotAutomatic": "This function cannot be used for sub charges generated automatically by internal settlement",
    "pleaseDontTalkToMe": "Please do not check both internally settled and non internally settled expenses",
    "enterFinanceFlow": "The charges that have entered the financial process cannot be reversed. Please solve the negative charges",
    "chooseAndMention": "Select and submit",
    "requiredTips": "Required prompt",
    "cancelPopUp": "Cancel pop-up",
    "iChoseToGoInside": "Internal knot item selected",
    "lockSelected": "Locked charges selected",
    "noteHealth": "Note: after a / R is generated, please pay attention to whether the A / R invoice type needs to be adjusted",
    "generateAR": "Generate a / R internal settlement",
    "modifiedSuccessfully": "Modification succeeded!",
    "unselected": "Unapproved order is checked",
    "checkFee": "Check that the expense has been approved. There is no need to repeat the operation",
    "checkedChecked": "Checked approved order",
    "tickPrompt": "Tick prompt",
    "saveTips": "Save prompt",
    "revokeApproval": "Cancel approval button",
    "checkFee2": "Check that the expense is not approved. There is no need to repeat the operation!",
    "cancellationOfAudit": "Revoke approval",
    "confirmAll": "Recognize all charges receivable",
    "expenseConfirmation": "Expense confirmation button",
    "wenLeiExpenses": "Wen Lei expense confirmation button",
    "generativeRay": "Generate document confirmation form",
    "operationSucceeded": "The operation is successful, and {val1} confirmations have been generated. Doc No.: {val2}",
    "noCompliance": "No eligible expenses, no operation required",
    "generateConfirmation": "Generate confirmation sheet",
    "confirmOperation": "Confirm the operation agent fee",
    "confirmationOfEntrustment": "Confirm the client's expenses",
    "completionOfInternalAudit": "Internal audit completion button",
    "thereIsAnErrorItem": "There are error items, unable to complete internal audit, please modify",
    "internalAudit": "Internal audit",
    "internalAuditCompleted": "Completion of internal audit",
    "continueInternalAudit": "Continue internal audit",
    "requiredBeforeInternalAudit": "Before internal audit, please complete the operation first!",
    "auditOpinion": "Review comments",
    "internalAuditRejection":'InternalAudit Rejection',
    "submittedSuccessfully": "Submitted successfully!",
    "international": "International business",
    "fastInternalFixation": "Fast internal knot",
    "isItNecessary": "Is it necessary for ATC to enter sea freight?",
    "unwanted": "No, the entry has been completed",
    "yesYes": "Notify ATC if necessary",
    "costEntry": "Cost entry completed",
    "entered": "Entered",
    "inputCompleted": "Entry completed",
    "operationTime": "Operation time:",
    "operator": "Operator:",
    "notificationSucceeded": "Notification succeeded",
    "requestSucceeded": "Request succeeded",
    "includeCost": "Include costtab",
    "includingFreight": "Include freight tab",
    "includingFreight2": "Include freight and costtab",
    "principalSubSimpleInterest": "Profit of master sub order",
    "simpleInterestOfWork": "Work order profit",
    "untaxedProfit": "Profit before tax",
    "noTaxPayable": "Unpaid tax payable",
    "nonTaxableReceivables": "Tax receivable",
    "untaxedProfitWithoutTax": "Profit before tax (excluding tax)",
    "noTaxPayableWithoutTax": "Tax payable (excluding tax)",
    "nonTaxableReceivablesWithoutTax": "Tax receivable (excluding tax)",
    "wuYuchao": "Wycsh (Wu Yuchao)",
    "wuYuchao2": "Wycjt (Wu Yuchao JT)",
    "generalElectronics": "Ordinary electronic invoice",
    "profitView": "Profit view",
    "insurance": "Insurance",
    "universalRapidTransit": "Universal Rapid Transit",
    "shanghaiHuanshi": "Shanghai Huanshi MRT Logistics Co., Ltd",
    "annualInspection": "5-year annual inspection",
    "shanghaiHuanshi2": "Shanghai Huanshi logistics (Group) Co., Ltd",
    "baseCurrency": "Functional currency ({val1})",
    "portalOverseas": "Portal overseas agent test 1",
    "wenhuiTechnology": "Wenhui Technology Co., Ltd",
    "operationFee": "Operation fee",
    "generalTicket": "General ticket",
    "vatGeneral": "VAT ordinary invoice 0%",
    "profitSharing": "Profit sharing profit",
    "byCompany": "Statistics by company",
    "statisticalProfit": "The statistical profit includes BC single expense and multi tax rate split sub single profit",
    "statisticalProfit2": "The statistical profit includes multi tax rate split document profit",
    "statisticsByTicket": "Statistics by ticket",
    "sendCheck": "Send check notification",
    "sendOut": "SA send",
    "theUserIsNot": "This user has not configured mailbox to send information. Please go to user information - mail configuration to configure",
    "continue": "continue",
    "pleaseOpenItFirst": "Please open the confirmation form details first",
    "splitButton": "Split button to verify service items",
    "splitButton2": "Split button, select sub doc",
    "splitButton3": "Split button with freight selected",
    "splitButton4": "Split button to select an expense",
    "splitButton5": "Split button, error reported before modification",
    "taxPayable": "Tax payable",
    "taxRateReceivable": "Tax rate receivable",
    "services": "Del service item",
    "services2": "Por service items",
    "workOrder": "Work order",
    "joinTo": "Add to split order",
    "newOrder": "New order",
    "splitMode": "Split mode",
    "splitCosts": "Split expense order",
    "pleaseSelectAtLeast": "Please select at least one sub order",
    "pleaseChooseAtLeast": "Please select at least one service item!",
    "beforeSplitting": "Before splitting",
    "taxRate": "tax rate",
    "invoiceType": "Invoice type",
    "batchChangeTax": "Batch modify tax rate",
    "cannotExist": "There are charges that cannot use the current tax rate",
    "chineseSymbols": "、",
    "chapterIiBankAssets": "The tariff in line {val1} is not applicable to the current tax rate, please select again",
    "notSelectable": "You cannot select locked charges. Please unlock them first",
    "pleaseSelectFirst": "Please select the settlement company and service phase of the selected expense first",
    "notAtTheSameTime": "A / R and a / P cannot be selected at the same time for batch modification of tax rate",
    "pleaseSelectFee": "Please select expense to modify tax rate in batch"
  },
  "MergeFeeBtn": {
    "syncToMeter": "Sync to schedule",
    "planningCosts": "Plan cost",
    "actualCost": "Actual cost",
    "costItems": "Expense item",
    "associationStatus": "Association status",
    "currentPageLetter": "The current page information has been modified, please save it first!",
    "notAssociated": "Not associated",
    "associated": "Associated"
  },
  "TableComponents": {
    "equivalentTo": "Equivalent:",
    "subtotalOriginal": "Subtotal: original currency:",
    "totalOriginal": "Total: original currency:",
    "allSettlement": "All settlement companies"
  },
  "TagTabs": {
    "wenRayExpenses": "Wen Lei expense confirmation form",
    "expenseConfirmation": "Expense confirmation",
    "feeList": "Expense list"
  },
  "__tests__": {
    "fastTest": "Test whether the quick inner knot button exists",
    "fastTesting": "Test quick knot button",
    "splitButton": "Split Button",
    "testWhether": "Test whether selectedkeys is cleared"
  },
  "Constants": {
    "pleaseDontTick": "Please do not check the internal settlement fee!",
    "pleaseDontTick2": "Please do not check the lock fee!",
    "pleaseSaveFirst": "Please save the fee first!",
    "pleaseDontTick3": "Please do not check the sub order!",
    "pleaseDontTick4": "Please do not check freight!",
    "pleaseCheckShould": "Please check a / R, cost or freight!",
    "pleaseCheckTheBox": "Please check the freight!",
    "pleaseCheckAs": "Please check the cost!",
    "pleaseCheckShould2": "Please check a / R and cost!",
    "profitSharing": "Profit sharing",
    "newCollection": "New solicitation agency fee",
    "newOperation": "New operation agent fee",
    "newTrailer": "Cost of newly added towing company",
    "newBoatman": "Additional shipping company expenses",
    "newStorage": "New storage company expenses",
    "newCustomsDeclaration": "Expenses of new customs broker",
    "already": "already",
    "stay": "stay",
    "ministry": "Department",
    "not": "not",
    "writeOffCompleted": "Write off completed",
    "partialWriteOff": "Partial write off",
    "notWrittenOff": "Not written off",
    "approved": "Approved",
    "partialApproval": "Partial approval",
    "partialSettlement": "Partial settlement",
    "settled": "Settled",
    "uncleared": "uncleared ",
    "partialRegistration": "Partial registration",
    "registered": "Registered",
    "unregistered": "unregistered",
    "invoiced": "Invoiced ",
    "notInvoiced": "Not invoiced",
    "notified": "Notified",
    "noNotice": "Not notified",
    "reconciled": "Reconciled",
    "noReconciliation": "Unreconciled",
    "reviewed": "Reviewed",
    "notReviewed": "Not approved",
    "existingAudited": "Approved expense exists, cannot be",
    "existingDisassembled": "There are split expenses, cannot",
    "theExistenceIsConfirmed": "There are confirmed expenses, which cannot be",
    "existenceHasEntered": "There are expenses that have entered the financial process and cannot be deleted",
    "split": "split"
  },
  "FeeEditStrategy": {
    "pleaseSelect": "Please select payable fee!",
    "editedTheTune": "You have edited and adjusted the returned expenses. Please refresh the page or resubmit before operation",
    "ningboInternational": "Ningbo 125 International Logistics Co., Ltd",
    "includeSettlement": "Wydcfeeeditstrategy addrec contains settlement units",
    "includeSettlement2": "Wyfeeeditstrategy addrec contains the settlement unit",
    "includeSettlement3": "Defaultfeeeditstrategy addrec contains the settlement unit",
    "logistics": "XXX Logistics",
    "newName": "G1000073 new name",
    "includeSettlement4": "Wydcfeeeditstrategy addtemplatefee contains settlement units",
    "includeSettlement5": "Wyfeeeditstrategy addtemplatefee contains settlement units",
    "includeSettlement6": "Defaultfeeeditstrategy addtemplatefee contains settlement units",
    "asianShipping": "Asian shipping",
    "shanghaiWenlei": "Shanghai Wenlei",
    "cost": "{val1} cost",
    "notApplicableTo": "{val1} is not applicable to the business type of the current business order. Please uncheck the corresponding expense and click OK",
    "pleaseSelectShould": "Please select an expense receivable!"
  },
  "Rule": {
    "subSingleLocking": "Sub single locking",
    "serverLock": "Server lock",
    "thePrevious": "the previous",
    "differentBusiness": "Locking of different business entities",
    "newSettlement": "Add - settlement company",
    "allowEditing": "Allow editing",
    "matchField": "Match field",
    "matchingRules": "Matching rules",
    "expenseEditing": "Expense editing rules",
    "locking": "locking",
    "innerKnotGeneration": "Cost generated by internal settlement",
    "notLocked": "Not locked",
    "costAllocation": "Cost allocation",
    "savedSuccessfully": "Saved successfully!",
    "whole": "whole",
    "unknownGauge": "Unknown rule",
    "pairNotFound": "The corresponding editing rule was not found, please contact the administrator",
    "customerCare": "Customer care"
  },
  "Store": {
    "fastInternalFixation": "Quick internal knot action",
    "onlySelected": "Has only selected freight",
    "onlySelected2": "Has only selected cost",
    "xiaXiaoShanghai": "Shanghai Xia Xiaofeng",
    "wenhuiTechnology": "Wenhui Technology",
    "oceanFreight": "Sea freight",
    "lockButton": "Lock button"
  },
  "TableRender": {
    "nonTaxExempt": "Non tax exempt",
    "dutyFree": "duty-free",
    "taxExemptNonExempt": "{val1}",
    "income": "income",
    "pleaseCheckTheWord": "Please check the field editing rules",
    "quantityCannot": "Quantity cannot be 0",
    "noMoney": "Currency cannot be empty",
    "settlementUnit": "Settlement company cannot be blank",
    "invoiceType2": "Invoice type cannot be blank",
    "actionBar": "action bar",
    "clearingCompany": "Settlement company cannot be blank",
    "unitPriceCannot": "Unit price cannot be 0",
    "unitPriceCannot2": "Unit price cannot be blank",
    "serviceLink": "Service phase cannot be empty",
    "billingUnit2": "Billing unit cannot be blank",
    "expenseName": "Tablerenderhelper fee item name",
    "invoiceType": "Tablerenderhelper invoicetypeid invoice type",
    "operation": "Tablerenderhelper opfixedright operation",
    "billingUnit": "Tablerenderhelper unit",
    "taxRate": "Tax rate readonly additionalrate",
    "taxRate1": "Tax rate input additionalrate",
    "quantity": "Quantity readonly count",
    "quantity1": "Quantity input count",
    "currency": "Currency readonly ctnno",
    "currency1": "Currency input ctnno",
    "currency2": "Currency readonly currency",
    "currency3": "Currency input currency",
    "settlementUnit1": "Settlement unit input customername",
    "expenseName1": "Fee name render form",
    "expenseName2": "Expense name render readonly",
    "invoiceType1": "Invoice type internal settlement only displays invoices with the same rate",
    "clearingCompany1": "Settlement company input orgname",
    "unitPrice": "Unit price readonly price",
    "unitPrice1": "Unit price input price",
    "quantity2": "Quantity readonly remark",
    "quantityPoint": "Quantity input remark, click to switch",
    "quantity4": "Quantity input remark",
    "serviceLink1": "Service link render readonly",
    "actualSettlement": "Actual settlement company readonly settlementorgname",
    "actualSettlement1": "Actual settlement company input settlementorgname",
    "billingUnit1": "Billing unit readonly unitname",
    "settlementUnit2": "Settlement unit: readonly wycustomername",
    "settlementUnit3": "Settlement unit: input wycustomername"
  },
  "Tables": {
    "newExpenses": "Additional expenses",
    "copyToShould": "Copy to a / R",
    "copyHistory": "Copy history cost",
    "addFees": "Charge added successfully",
    "clearSort": "Clear sort",
    "clearFilter": "Clear filter",
    "partialConfirmation": "Partial confirmation",
    "copyToShould2": "Copy to a / P",
    "copyToProfit": "Copy to profit share",
    "copyToShipment": "Copy to freight",
    "copyToAssembly": "Copy to cost",
    "line": "{val1} line {val2}: {val3}",
    "quantityCannot": "Quantity cannot be empty or 0. It has been set to the default value of 1",
    "pairNotFound": "Corresponding charge not found"
  },
  "Util": {
    "confirmExpenses": "Confirm {val1} {val2} expenses",
    "unknown": "unknown",
    "grossProfitRate": "Gross margin",
    "equivalent": "Equivalent to {val1}"
  },
  "Utils": {
    "fixedValue": "Fixed value",
    "testLock": "Test lock",
    "subOrderFee": "Sub order expense",
    "nonCurrentFee": "Business entity of non current expense creation",
    "exchangeRateCannot": "Exchange rate cannot be blank",
    "feeName": "Expense name cannot be empty"
  },
  "FeeAddForCustomer": {
    "freightCharges": "Freight expense addition",
    "costExpense": "New cost",
    "expensesReceivable": "New expense receivable"
  },
  "FeeClientLock": {
    "current": "Business entity of current stakeholder"
  },
  "FieldEdit": {
    "feeUnlocked": "Charge not locked",
    "costLocking": "Cost locking",
    "internalSettlementFee": "Internal sub expense is editable",
    "noEditing": "No edit permission"
  },
  "TableRenderHelper": {
    "expenseTaxRate": "Expense tax rate",
    "readOnlyInvoice": "Read only invoice type",
    "invoiceStatus": "Tablerenderhelper invoicestatus invoice status",
    "invoiceNo": "Tablerenderhelper invoicestatus invoice number",
    "settlementUnit": "Tablerenderhelper shortname short name of settlement unit"
  }
}