export default {
  "FilterService": {
    "directCustomers": "Direct customers",
    "chinaDay": "CNJ (China / Japan route)",
    "commonGoods": "Common goods",
    "juhanEnterprise": "Juhan enterprise",
    "export": "Export",
    "fclBySea": "Ocean full container",
    "tradeTerms": "Trade terms",
    "consignee": "consignee",
    "shipper": "consignor",
    "shipside": "wharf",
    "solicitationMethod": "Solicitation method",
    "country": "country",
    "advancePayment": "MBL advance payment: fresh advance",
    "routeMedium": "Route: CNJ (China / Japan route)",
    "billingUnit": "Billing unit: 20gp",
    "validFrom": "Period of validity: natural day -- July 8, 2021",
    "portOfDeparture": "Port of departure",
    "generalGoods": "Category: general goods",
    "validityAdvance": "Period of validity: expected departure date -- July 31, 2021",
    "validityAdvance2": "Validity period: expected arrival date -- July 31, 2021",
    "portOfDestination": "Port of destination: Tokyo",
    "entrustedUnit": "Client: Juhan enterprise",
    "carrier": "carrier",
    "importAndExportStandard": "Import and export identification",
    "businessType": "Business type: full container shipping",
    "termOfValidity": "Validity: {val1} -- {val2}",
    "arrivalDay": "Arrival day",
    "customsBroker": "Customs broker",
    "expectedArrival": "Expected arrival date",
    "fleet": "fleet",
    "expectedDeparture": "Estimated departure date",
    "warehouse": "Warehouse",
    "naturalDay": "Natural day",
    "station": "Station",
    "actualDeparture": "Actual departure date",
    "terminal": "terminal ",
    "wharf": "wharf",
    "shippingAgent": "Shipping agent",
    "overseasAgency": "Overseas agent",
    "bookingAgent": "Booking Agent ",
    "forwardingUnit": "forwarding unit",
    "ctnNo": "Case number",
    "sealNo": "title",
    "ctnType": "Box type",
    "vgm": "Hair body",
    "existContainer": "Container data matching"
  },
  "Index": {
    "rateTemplate": "Rate template selection",
    "expensesPayable": "Expense payable scheme",
    "expensesReceivable": "Expense receivable scheme",
    "pleaseSaveItFirst": "Please save the business order first",
    "chooseOther": "Choose another option",
    "quickIntroduction": "Quick introduction scheme",
    "currentBusiness": "The current business only matches one expense scheme. Do you want to import it directly?",
    "tips": "Tips"
  },
  "Utils": {
    "shippingAgent": "Shipping agent",
    "overseasAgency": "Overseas agent",
    "bookingAgent": "Booking Agent ",
    "forwardingUnit": "forwarding unit",
    "chinaUniversity": "CJR (Chinese mainland Yangtze River domestic trade route)",
    "domesticTrade": "Domestic trade",
    "piece": "piece",
    "generalChemicalIndustry": "General chemicals",
    "fee": "F fee 1",
    "individualLevel": "Individual level",
    "departmentLevel": "Department level",
    "companyLevel": "Company level"
  }
}