export default {
  "BnFileBatchAdd": {
    "pleaseInputText": "Please enter the file number",
    "documentNumber": "The file number character is too long",
    "pleaseSelectTheText": "Please select a file type",
    "selectFile": "Select File:",
    "batchAddition": "Batch add files",
    "chineseSymbols": "MB。",
    "onAFile": "File upload, single file maximum",
    "singleMost": "At most one selection is supported at a time",
    "fileUpload": "{val1} file upload failed!",
    "single": "H single",
    "single2": "M single",
    "fileType": "File type cannot be empty!",
    "mustUpload": "Files must be uploaded"
  },
  "BnFileHistoryList": {
    "historicalVersion": "Historical version",
    "download": "download",
    "filingTime": "Filing time",
    "filer": "Filed by",
    "sourceOfDocuments": "Document source",
    "fileSize": "file size",
    "fileType": "file type",
    "fileName": "File name",
    "total": "Total {val1}"
  },
  "BnFileLayout": {
    "filingOfDocuments": "File archiving"
  },
  "BnFileList": {
    "noteText": "Note: the positions for which the file is visible need to be configured in the master data of the file type",
    "documentNumber": "Document number",
    "fileName": "File name",
    "filerOnly": "Only the filer can modify or delete files",
    "fileCannot": "No more than 50 files",
    "pleaseSelectOne": "Please select a file",
    "addFile": "Add file",
    "batchAddition": "Batch add",
    "pushToTheDoor": "Push to portal",
    "batchDownload": "Batch download",
    "filingOfDocuments": "File archive list",
    "total": "Total {val1}"
  },
  "BnFileTrackList": {
    "trackingSteps": "Tracking steps",
    "documentFollowUp": "Document follow up list",
    "onYourPage": "There are content modifications on your page. Are you sure you want to switch to other files?",
    "sendABill": "Send a bill",
    "operatingInstructions": "Operating instructions",
    "completionStatus": "Completion status",
    "pedagogicalOperation": "pedagogical operation",
    "operationSteps": "Operation steps",
    "fileStatus": "File status",
    "mailingTask": "Order sending task No",
    "sendGet": "Send / get object",
    "documentNumber": "Document number",
    "filerOnly": "Only filers can delete files",
    "operationFailed": "Operation failed. The document has been sent and cannot be deleted",
    "atLeast": "At least one document posting needs to be selected",
    "youCanOnlyChoose": "Only documents that have not been mailed can be selected",
    "total": "Total {val1}"
  },
  "BnFileUpload": {
    "chineseSymbols": "/  : * \" < > | ？",
    "onlyUpper": "Only PDF, word, Excel, pictures, mail file types and compressed files can be uploaded.",
    "selectFile": "Select file",
    "modificationOfDocuments": "Modify file",
    "fileUpload": "File upload failed!"
  },
  "EFile": {
    "toAdd": "To add",
    "noDataAvailable": "No data",
    "singleAgency": "M single agent",
    "pleaseSaveFirst": "Please save the current content before operation!",
    "documentFollowUp": "Document follow-up",
    "noteOfMailing": "Note of mailing",
    "deliveryTime": "Delivery time",
    "mailingInformation": "Mailing information container",
    "mailingInformation2": "Mailing information",
    "mailingStatus": "Mailing status",
    "releaseRejection": "Release rejection time",
    "releasePass": "Pass time of bill release",
    "rejectComments": "Reject comments",
    "throughRemarks": "Through remarks",
    "releaseApproval": "Release approver",
    "applicationRemarks": "Application remarks",
    "applicationTime": "Application time",
    "applicant": "applicant",
    "releaseInformation": "Release information container",
    "releaseInformation2": "Release information",
    "orderTakingTime": "Order taking time",
    "noBill": "No order taken",
    "fetchedOrder": "Fetched order",
    "orderFetchingStatus": "Order fetching status",
    "retrievalInformation": "Retrieval information container",
    "retrievalInformation2": "Retrieval information",
    "documentComments": "Document comments",
    "relatedBillOfLading": "Related bill of lading No",
    "fileInformation": "File information container",
    "fileInformation2": "file information",
    "releasedOrder": "Released order",
    "notReleased": "Not released",
    "chineseSymbols": "Mailing details"
  },
  "ExpressModal": {
    "spellIn": "Spell in",
    "fileList": "File list",
    "printing": "Print",
    "electronicMailingList": "Electronic mail order",
    "mailingStatus": "Mailing status:",
    "mailingTask": "Order sending task No.:",
    "pleaseFillInTheReceipt": "Please fill in the recipient's email!",
    "atLeastAdd": "Add at least one file!"
  }
}