export default {
  "Container_dynamics": {
    "tare": "tare:",
    "number": "number:",
    "boxType": "Box type:",
    "driversPhone": "Driver's telephone:",
    "driver": "driver:",
    "licensePlateNumber": "license plate number:",
    "processingTime": "Eir processing time",
    "emptyLocation": "Eir empty location:",
    "actualShort": "Actual empty location:",
    "emptyContainer": "Empty container time:",
    "emptyTheBox": "Emptying / emptying",
    "leaveTheDoorPoint": "Departure time:",
    "packingCompleted": "Packing completion time:",
    "startOfPacking": "Packing start time",
    "reachTheGatePoint": "Time to gate",
    "doorPointPacking": "Door point packing",
    "actualOutOfWarehouse": "Actual delivery time:",
    "actualWarehousing": "Actual warehousing time",
    "departurePortWarehouse": "Port of departure - warehouse",
    "confirmationTime": "VGM confirmation time",
    "declarationTime": "VGM declaration time",
    "actualArrival": "Del actual arrival time",
    "arrivalInformation": "Arrival information",
    "tallyRelease": "Tally release",
    "nationalInspectionRelease": "National inspection release",
    "dockRelease": "Terminal release time:",
    "customsClearance": "Customs clearance time",
    "customsInspection": "Customs inspection time",
    "customsDeclaration": "Customs declaration time",
    "departurePortRelease": "Port of departure - release information",
    "actualSailing": "Actual sailing time",
    "shipmentTime": "Shipment time:",
    "loadingAndSailing": "Pol loading / sailing",
    "transshipmentShipment": "Transshipment loading / sailing",
    "vesselNameAndVoyage": "Ship name / voyage:",
    "timeOfShipment": "Shipment time",
    "unloadingTime": "Pod unloading time",
    "arrivalTime": "Arrival time",
    "transitPort": "Transit port:",
    "portOfDestinationRelease": "Port of destination - release information",
    "returnTime": "Return time",
    "actualReceipt": "Actual signing time:",
    "actualDeparture": "Del actual departure time",
    "pickUpTime": "Del pick up time",
    "actualArrival2": "Actual arrival time of pod",
    "unloadingTime2": "Unloading time",
    "descendingOrder": "Descending order",
    "ascendingOrder": "Ascending order",
    "actualSignIn": "Actual signing time",
    "actualDelivery": "Actual out of warehouse time",
    "terminalRelease": "Terminal release time",
    "actualArrival3": "Actual arrival time",
    "leaveTheGate": "Departure time",
    "packingComplete": "Packing completion time",
    "whenEmpty": "Empty container time",
    "sortingDimension": "Sorting dimension",
    "shipment": "-Loading",
    "portToBeTransferred": "To be unloaded at the transfer port",
    "shipUnloading": "-Ship unloading",
    "boxReturned": "Returned",
    "returnBox": "Return box",
    "delivered": "Delivered",
    "toBeServed": "To be delivered",
    "outOfPort": "Out of port",
    "waitingForDeparture": "Waiting for departure",
    "unloadingAtDestinationPort": "Unloading at the port of destination",
    "portOfDestination": "To be unloaded at the port of destination",
    "transshipmentPortLoading": "Transshipment port - loading",
    "waitingPort": "To be loaded at transit port",
    "shipped": "Shipped",
    "toBeShipped": "To be shipped",
    "customsReleased": "Customs clearance",
    "customsToBeReleased": "Customs to be released",
    "customsHaveChecked": "The Customs has checked",
    "customsToBeInvestigated": "Customs to be inspected",
    "confirmed": "VGM confirmed",
    "toBeConfirmed": "VGM to be confirmed",
    "alreadyInPort": "Entered port",
    "waitingForArrival": "Waiting to enter the port",
    "getToTheGate": "Reach the gate point",
    "whenWeGetToTheFactory": "Stay at the factory",
    "emptyContainer2": "Empty box",
    "caseToBePickedUp": "Suitcase"
  },
  "Index": {
    "boxDynamics": "Box dynamics",
    "shippingInformation": "Shipping date information"
  },
  "Logistics_info": {
    "boxReturned": "Returned",
    "returnBox": "Return box",
    "signedIn": "Signed in",
    "toBeSigned": "To be signed",
    "outOfPort": "Out of port",
    "waitingForDeparture": "Waiting for departure",
    "arrivedInHongKong": "Arrived at port",
    "expectedArrival": "Expected arrival",
    "sld": "sld ",
    "expectedToSail": "Expected sailing",
    "customsClearance": "Customs clearance",
    "customsToBeReleased": "Customs to be released",
    "alreadyInPort": "Entered port",
    "waitingForArrival": "Waiting to enter the port",
    "boxed": "boxed ",
    "toBeBoxed": "To be packed",
    "emptyContainer": "Empty box",
    "caseToBePickedUp": "Suitcase",
    "gatePoint": "Gate point",
    "customs": "customs",
    "logisticsTracking": "Logistics tracking progress"
  },
  "Order_tracking": {
    "single": "M order:",
    "single2": "H order:"
  },
  "Sailing_info": {
    "placeOfReturn": "Place of return:",
    "emptyLocation": "Empty location:",
    "closingTime": "Closing time:",
    "cutOffTime": "VGM cut-off time:",
    "cutOffTime2": "Cut off time:",
    "closingTime2": "Port cut-off time:",
    "openingTime": "Departure time:",
    "shippingAgency": "Shipping agent:",
    "nameAndVoyage": "Name of vessel voyage:",
    "shippingCompany": "Shipping company:",
    "actualDeparture": "Actual departure time:",
    "actualBerthing": "Actual berthing time:",
    "plannedDeparture": "Planned departure time:",
    "plannedBerthing": "Planned berthing time:",
    "nameOfDepartingVessel": "Name of departure vessel voyage:",
    "portOfCall": "Port of call:",
    "berthingWharf": "Berthing wharf:",
    "fromHongkongPost": "Port of departure information:",
    "chineseSymbols": "ETA：",
    "chineseSymbols2": "ATA：",
    "portOfCall2": "Port of call",
    "chineseSymbols3": "ETD：",
    "chineseSymbols4": "ATD："
  }
}