export default {
  "ApplyButton": {
    "apply": "apply",
    "missingPacking": "Missing installation",
    "modification": "Modification"
  },
  "ModifyCheckList": {
    "number": "number",
    "pleaseSelectThe": "Please select the task to delete!"
  },
  "ModifyItemTable": {
    "originalValue": "Original value",
    "changeItem": "Change item"
  },
  "ModifyOrderDetail": {
    "approvalTime": "Approval time",
    "approvedBy": "Approver",
    "systemReasons": "System reason: association approval rejected",
    "systemReject": "System reject",
    "levelApproval": "{val1} level approval",
    "five": "five",
    "four": "four",
    "three": "three",
    "two": "two",
    "one": "one",
    "revoke": "revoke",
    "refuseToApprove": "Instructions are required when rejecting approval",
    "throughSuccess": "Through success",
    "approvalNumber": "Approval No.:",
    "rescinded": "rescinded",
    "cancellationOfApplication": "Cancellation of application",
    "customerDemand": "customer demand",
    "customerDemand2": "Customer requirements - content on the right",
    "supplementaryInformation": "Supplementary information",
    "customerDemand3": "Customer demand - transceiver",
    "dischargedEquipment": "Delivered equipment handover form",
    "theContainerHasEnteredThePort": "The container has entered the port",
    "specialOffer": "Special offer",
    "pickedUpCase": "Suitcase carried",
    "remarksOfTheFirstInstance": "Remarks of first instance",
    "bookingPost": "Booking post",
    "productNameNone": "Product name (no n / a)",
    "specialOffer2": "Special customers",
    "specialOffer3": "Special offer type",
    "placeOfContractingParty": "Address of the Contracting Party",
    "contractParty": "contract party",
    "onlyInput": "You can only enter no more than 30 non Chinese characters",
    "resubmit": "Resubmit"
  },
  "ModifyOrderModal": {
    "applicationApproval": "Application for approval",
    "approvalAndSubmission": "Approval submitted successfully",
    "theContainerHasEnteredThePort": "The container has entered the port",
    "pickedUpCase": "Suitcase carried",
    "applicationForMissingPacking": "Failed to apply for missing installation",
    "ourCompany": "Our company",
    "trailerCompany": "Trailer company",
    "responsibleParty": "Responsible party",
    "changeOrderNumber": "Change order number",
    "missingType": "Missing type",
    "liabilityForExpenses": "Expense responsible party",
    "missingNumber": "Missing assembly number",
    "statusMark": "Status flag",
    "reAllocationNumber": "Distribution No",
    "reasonForApplication": "Reason for application"
  },
  "ModifyRenderItem": {
    "deliveryContact": "Delivery contact telephone",
    "deliveryContact2": "Delivery contact",
    "deliveredByConsignee": "Consignee shipping address",
    "onlyInput": "You can only enter no more than 1750 characters",
    "deliveryTime": "Delivery time",
    "packingRequired": "Required packing time",
    "packingContact": "Packing contact telephone",
    "packingContact2": "Packing contact",
    "designatedGoods": "Designated goods",
    "shippersPacking": "Shipper's packing address",
    "recipientProvince": "Consignee province and city",
    "shipperProvince": "Consignor province and city",
    "entrustedPayment": "Entrustment - place of payment",
    "onlyInput2": "You can only enter no more than 1500 English characters",
    "chineseValue": "Chinese value",
    "singleParty": "M order issuing method",
    "bookingMode": "Booking mode",
    "expectedArrival": "Estimated arrival time",
    "multiplePleaseUse": "More than 650 non Chinese characters are not allowed",
    "bookingPlan": "Booking plan booking agent",
    "actualNotice": "Actual Notifier",
    "actualReceipt": "Actual consignee",
    "actualDelivery": "Actual shipper",
    "onlyInput3": "You can only enter up to 500 characters",
    "multiplePleaseUse2": "More than 250 non Chinese characters are not allowed",
    "onlyInput4": "You can only enter no more than 250 non Chinese characters",
    "agreementNo": "Agreement No",
    "entrustedPayment2": "Entrustment - payment method",
    "entrustedTransportation": "Consignment - Transportation clause",
    "bookingPlan2": "Booking plan Notifier",
    "bookingPlan3": "Booking plan consignee",
    "bookingPlan4": "Booking plan shipper",
    "onlyInput5": "You can only enter no more than 30 English characters",
    "onlyInput6": "You can only enter no more than 50 English characters",
    "packingMethod": "Packing method"
  },
  "ReadonlyModifyItem": {
    "recipientProvince": "Consignee province and city",
    "shipperProvince": "Consignor province and city",
    "packingContact": "Packing contact",
    "shippersPacking": "Shipper's packing address",
    "actualNotice": "Actual Notifier",
    "actualReceipt": "Actual consignee",
    "actualDelivery": "Actual shipper",
    "bookingPlan": "Booking plan Notifier",
    "bookingPlan2": "Booking plan consignee",
    "bookingPlan3": "Booking plan shipper",
    "entrustedPayment": "Entrustment - place of payment",
    "singleParty": "M order issuing method",
    "bookingPlan4": "Booking plan booking agent",
    "entrustedPayment2": "Entrustment - payment method",
    "entrustedTransportation": "Consignment - Transportation clause",
    "billOfLading": "Bill of lading method",
    "bookingMode": "Booking mode",
    "expectedArrival": "Estimated arrival time",
    "descriptionOfTheGoods": "description of the goods",
    "agreementNo": "Agreement No",
    "eCommerceReference": "E-commerce reference number",
    "wyBooking": 'wyBooking',
    "noBooking": "Non contractual space",
    "customerAppointmentNumber": "Customer appointment number",
    "agencyAgreementNo": "Agency agreement No",
    "ourContractNumber": "Our appointment number"
  }
}