export default {
  "addFees": "Add charge",
  "exchangeRate": "exchange rate",
  "otherSettlement": "Other settlement units",
  "financialSubmission": "Submit financial report and write off",
  "financialSubmission2": "Financial submission",
  "addFees2": "Before adding an expense, you must select the collection document currency and settlement company",
  "addFees3": "The collection document currency must be selected before adding an expense",
  "addInternal": "Add internal transactions",
  "findSettlement": "Find settlement company",
  "privateAccount": "Private account",
  "noteOnly": "*Note: only the expenses that have been checked and the current collection amount is not 0 can be saved by association",
  "noMatch": "No matching data",
  "remittanceAccountNumber": "Remittance account number cannot be blank",
  "excludingExpenses": "Excluding expenses",
  "autoCheck": "Auto check",
  "smallChange": "Change: 0",
  "oddShortAccount": "Odd short account",
  "thisSelection": "Total of this selection:",
  "smallChange2": "Change:",
  "shortAccount": "Short account:",
  "autoCheck2": "The automatically checked amount should be greater than 0",
  "financialSubmission3": "When submitting finance or submitting finance and write off, the settlement company cannot be blank",
  "newReceipt": "Collection doc added successfully",
  "ofPer": "There are {val1} in total, and {val2} on each page",
  "refundRate": "Refund exchange rate",
  "refundFee": "Refund fee",
  "balance": "balance",
  "externalBuckle": "External buckle",
  "internalBuckle": "Inner buckle",
  "commissionDeduction": "Service charge deduction method",
  "pleaseSelectADay": "Please select a date",
  "dateOfReceiptAndPayment": "Date of receipt and payment",
  "waterBillDate": "Water bill date",
  "collectionType": "Collection type",
  "refund": "refund",
  "fullTransfer": "Full amount transfer to advance receipt",
  "writeOff": "Write off",
  "writeOffType": "Write off type",
  "otherAccounting": "Other accounting dimensions",
  "checkNumber": "Check number",
  "arrivalDate": "Date of receipt",
  "amountToBeWrittenOff": "Amount to be written off",
  "collectionAmount": "Collection amount",
  "dateOfRegistration": "Date of registration",
  "voucherNo": "Voucher No",
  "remittanceAccountNumber2": "Remittance account number",
  "receivingBank": "Receiving bank",
  "bankStatement": "bank statement",
  "registrant": "Registrant",
  "remittanceBank": "Remittance bank",
  "paymentUnit": "The length of payment unit cannot exceed 100",
  "payer": "Payment unit",
  "bankProcedures": "bank charges",
  "invoiceTitle": "Billing header",
  "receiptSlip": "Receipt memo",
  "cannotBeEmpty": "Cannot be empty and the maximum length is 30",
  "receiptNo": "Receipt No",
  "financialSubmission4": "Submit financial and write off collection doc successfully",
  "financialSubmission5": "Financial submission succeeded",
  "receiptInsurance": "Collection doc saved successfully"
}