export default {
  "BasicDataConstant": {
    "summaryReconciliation": "Summary statement",
    "detailedReconciliation": "Detailed statement",
    "bill": "bill",
    "boxGuarantee": "Box guarantee",
    "releaseApplication": "Release application",
    "telexReleaseGuarantee": "Discharge guarantee",
    "multipleVotes": "Multiple votes",
    "singleTicket": "Single ticket",
    "declarationForm": "Customs declaration",
    "customsDeclarationCommission": "Customs declaration entrustment",
    "packingRecord": "Packing record",
    "outOfWarehouseVerification": "Warehouse out verification sheet",
    "outOfWarehouseNotice": "Withdrawal notice",
    "warehouseEntryVerification": "Warehouse entry verification sheet",
    "warehouseEntryNotice": "Warehouse entry notice",
    "packingCommission": "Packing power of attorney",
    "deliveryNotice": "Delivery notice",
    "dispatchList": "Dispatch list",
    "cupboardPaper": "Cabinet paper",
    "heavyCabinetPaper": "Heavy cabinet paper",
    "packingList": "Packing list",
    "shipCertificate": "HBL certificate",
    "shipCertificateTradePromotion": "Additional signature of HBL China Council for the promotion of international trade",
    "certificateOfOrigin": "Certificate of origin",
    "freightInsurance": "Reverse signed letter of guarantee for freight insurance business",
    "insurancePolicy": "Insurance policy",
    "otherGuarantees": "Other guarantees",
    "noBoardingPass": "Certificate of non boarding",
    "letterOfGuarantee": "Sea waybill guarantee",
    "missingLetterOfGuarantee": "Missing letter of guarantee",
    "separateAndMergeOrders": "Separate and consolidated guarantee",
    "changeOfBillOfLading": "Bill of lading amendment guarantee",
    "billOfLading": "Copy of bill of lading",
    "confirmationPiece": "MBL confirmation",
    "confirmationPiece2": "HBL confirmation",
    "shippingCompany": "Shipping company booking",
    "peers": "Peer Booking",
    "bookingGuarantee": "Booking guarantee",
    "trustLetter": "Book entrustment"
  },
  "OutPutDialog": {
    "output": "output"
  }
}