export default {
  "PageInfo": {
    "hasBeenSent": "has been sent",
    "notSent": "Not sent",
    "issuedByAirTrafficExchange": "ATD sending record of air exchange",
    "issuedByAirTrafficExchange2": "ETD sending record of air exchange",
    "mainShippingMark": "Main shipping mark",
    "wyTelexReleaseEmail": "Email address of Wenlei radio",
    "entrustedVolume": "Entrusted volume",
    "entrustedGrossWeight": "Entrusted gross weight",
    "numberOfConsignments": "Number of entrusted pieces",
    "actualVolume": "Actual volume",
    "actualGrossWeight": "Actual gross weight",
    "actualPackaging": "Actual packaging",
    "actualNumberOfPieces": "Actual number of pieces",
    "natureOfGoods": "Nature of goods",
    "number": "Bkg No",
    "booking": "Booking por",
    "entrust": "Delegate del",
    "entrust2": "Delegation por",
    "bookingPayment": "Booking place of payment",
    "bookingPayment2": "Booking payment method",
    "bookingTransportation": "Booking shipping terms",
    "commissionPayment": "Place of entrusted payment",
    "commissionPayment2": "Entrusted payment method",
    "consignmentTransportation": "Consignment clause",
    "amount": "TEU quantity",
    "course": "course",
    "passedTheInternalAudit": "Internal audit pass time",
    "theOperationIsComplete": "Operation completion time",
    "bookingConfirmation": "Booking confirmation time",
    "passedTheFirstInstance": "Passing time of first instance",
    "orderCreation": "Order creation time",
    "founder": "Creator",
    "operationAgent": "Operation agent",
    "solicitingAgent": "Solicitation agent",
    "customerContract": "Customer contract No",
    "proxyReference": "Agent reference number",
    "generalInformationOfBooking": "General booking status",
    "orderStatus": "Order status",
    "packingMethod": "Packing method",
    "services": "Service item",
    "seaWaybill": "Sea waybill"
  }
}