export default {
  "BatchUpdatePackinggate": {
    "customsSupervision": "Customs supervision vehicle",
    "detailedTime": "Detailed time supplement",
    "time": "{val1} time",
    "contactNumber": "{val1} contact phone",
    "contacts": "{val1} contact",
    "gatePoint": "{val1} gate point",
    "detailedAddress": "Detailed address",
    "deliveryAddress": "Delivery address",
    "fileUpload": "File upload",
    "selectFile": "Select file",
    "deliveryContact": "Delivery contact",
    "deliveryContactTel": 'Delivery contact telephone',
    "addFile": "Add file",
    "provincialCities": "Province / city / district / county",
    "place": "{val1} location",
    "deliverGoods": "deliver goods",
    "receivingGoods": "Receiving",
    "delivery": "Delivery",
    "deliveryReceipt": "{val1} unit",
    "batchMaintenance": "Batch maintenance {val1} gate point",
    "packing": "Packing"
  },
  "BnMultiTruckpaAreaDialog": {
    "gatePointList": "{val1} door point list",
    "delivery": "Delivery",
    "packing": "Packing",
    "unpacking": "Unpacking",
    "remove": "remove",
    "areYouSureYouWantToMove": "Are you sure you want to remove the {val1} door point?",
    "customsSupervision": "Customs supervision vehicle",
    "estimatedTime": "Estimated {val1} time",
    "contactNumber": "{val1} contact phone",
    "contacts": "{val1} contact",
    "gatePoint": "{val1} gate point",
    "detailedAddress": "Detailed address",
    "chineseSymbols": "{val1}，{val2}，{val3}",
    "place": "{val1} location",
    "receivingUnit": "Receiving unit"
  },
  "BnPackinggatepointEditList": {
    "estimatedTime": "Estimated {val1} time",
    "contactNumber": "{val1} contact phone",
    "contacts": "{val1} contact",
    "gatePoint": "{val1} gate point",
    "place": "{val1} location",
    "receivingUnit": "Receiving unit",
    "gatePointList": "Door point list"
  },
  "TruckBulkCargoPlan": {
    "requirement": "{val1} requirements",
    "plannedTime": "Planned {val1} time",
    "spot": "{val1} point",
    "teamContact": "Fleet contact number",
    "teamContact2": "Fleet contact",
    "purchaseWarehouse": "Incoming warehouse",
    "planNumber": "Plan No",
    "pleaseSelectTheOneYouWant": "Please select the data to operate!",
    "noCarWasSent": "The car dispatch cannot be cancelled because the car dispatch has not been completed!",
    "planNo": "Plan No.:",
    "pleaseSelectTheOneYouWant2": "Please select the data to delete!",
    "areYouSureYouWantToDelete": "Are you sure you want to delete the selected data?",
    "theCarHasBeenDispatched": "Dispatch completed, cannot delete!",
    "checkCarPlan": "Please check the car dispatching plan first",
    "notifyFailed": "Notification failed",
  },
  "TruckBulkCargoPlanDetailDialog": {
    "bulkCargoPlan": "Bulk cargo plan"
  },
  "TruckBulkCargoPlanEdit": {
    "provincesAndMunicipalitiesDirectlyUnderTheCentralGovernment": "Province / Municipality",
    "plannedDelivery": "Planned pick-up time",
    "pickUpTime": 'Pick up time',
    "telephone": "{val1} phone",
    "pickUpContact": "Pick up contact",
    "pickUpWarehouse": "Pick up warehouse",
    "requirement": "{val1} requirements",
    "driversPhone": "Driver telephone",
    "driver": "driver",
    "licensePlateNumber": "license plate number",
    "purchaseWarehouse": "Incoming warehouse",
    "warehousingTime": "Warehousing time",
    "fleetPhone": "Fleet telephone",
    "teamContact": "Fleet contact",
    "planNumber": "Plan No"
  },
  "TruckDetail": {
    "bulkCargoBusiness": "Bulk cargo business",
    "centralizedCardBusiness": "Centralized card business",
    "centralizedCardBusiness2": "Del truck service",
    "centralizedCardBusiness3": "Por - container truck service",
    "cancelTheDispatch": "Cancel dispatch",
    "dispatchTheCar": "Dispatch completed",
    "newPlan": "New plan",
    "synchronousScheduling": "Synchronous scheduling list",
    "containerTruckProgram": "Truck collection plan",
    "pleaseSelectAtLeast": "Please select at least one {val1}"
  },
  "TruckPlan": {
    "createANewDoor": "Create a new door point",
    "createANewDoor2": "+Create a new door point",
    "newSuccessfully": "New successfully!",
    "onlyInput": "Only positive numbers up to 10 digits can be entered",
    "maximumBitSize": "Up to 6 decimal places",
    "onlyInput2": "Only positive numbers up to 12 digits can be entered",
    "packingEstimate": "Cargo weight",
    "packingEstimate2": "Cargo weight (kgs)",
    "cargoWeight": "Cargo weight",
    "cargoWeight2": "Cargo weight (kgs)",
    "onlyInput3": "Only positive integers up to 12 characters can be entered",
    "onlyInput4": "You can only enter no more than 60 digits, English and English symbols",
    "onlyInput5": "You can only enter no more than 300 digits, English and English symbols",
    "addAuxiliaryLifting": "+Add duplicate bill of lading",
    "schedulingComplete": "Scheduling complete",
    "schedulingUnfinished": "Scheduling is not completed. Please maintain the dispatch plan first",
    "whenClickedThe": "After clicking, order operation follow-up will be notified",
    "addTemplate": "Add template",
    "forExamplePleaseMention": "For example, please carry a clean, odorless box",
    "gateNotFound": "Door point not found, please create it first!",
    "inputQuery": "Input query",
    "noMatch": "No matching template",
    "doorPointPortrait": "Door point portrait",
    "fieldCannot": "The field cannot be greater than 2000 characters",
    "notificationScheduling": "Notification scheduling",
    "informTransportationManagement": "Inform transportation management",
    "trailerDynamicQuery": "Trailer dynamic query",
    "downloadException": "File download exception",
    "confirmDeletion": "Are you sure to delete?",
    "continueSave": "Some required items are blank. Do you want to continue saving?",
    "yes": "Yes",
    "no": "No",
    "packingRemarks": "Packing remarks",
    "doorToDoorContact": "Contact number of door point",
    "pickUpPlace": "Pick up place",
    "territorialInspection": "Territorial inspection",
    "contractNo": "Contract No",
    "customerReferenceNumber": "Customer reference number",
    "doorToDoorContact2": "Gate contact",
    "packingTime": "Packing time",
    "plateNumber": "Plate number",
    "batchNumber": "Batch number",
    "materialSpecification": "Raw material specification",
    "gateName": "Door point name",
    "clientEntrustment": "Customer entrusted packing address",
    "deliveryGoodsPoint": "Delivery gate point",
    "weighingMethod": "Weighing method",
    "isTheSmallBox": "Is the small box double supported",
    "hairBodyAssembly": "Total pieces / wool / body: {val1} pieces {val2} kgs {val3} CBM",
    "multipoint": "+Multipoint",
    "packingInformation": "Packing information",
    "shippingInformation": "Shipping information",
    "newDragCabinet": "+New cabinet dragging plan",
    "currentlySaved": "There is a new plan that has not been saved. Please save and then add!",
    "doubleBracket": "Double bracket",
    "returnBoxAttached": "Lifting / returning accessories",
    "preConfigurationInformation": "Provisioning information",
    "basicInformation": "Basic information",
    "suitcaseD": "Suitcase QR code",
    "suitcaseLocation": "Suitcase location",
    "equipmentHandover": "Validity period of equipment handover form",
    "fleetLatest": "Latest box / seal time provided by the fleet",
    "boxReleaseTime": "Box release time",
    "arrivePortTime": "Actual arrival port time",
    "optionalBoxType": "Optional box type and volume:",
    "optionalBoxType2": "Optional box type and volume: None",
    "dispatchPlan": "Dispatch plan",
    "dispatcher": "Remarks of dispatcher",
    "federationOfSuppliers": "Supplier contact information",
    "federationOfSuppliers2": "Supplier Contact ",
    "dispatchMethod": "Dispatch method",
    "supplierName": "Supplier name",
    "offline": "Offline",
    "onLine": "on-line",
    "theNewChinaFederationOfConstruction": "Please create a new contact",
    "pleaseEnterOr": "Please enter or select a contact",
    "pleaseCreateANew": "Please create a new supplier",
    "pleaseEnterOr2": "Please enter or select supplier name",
    "deliveryNotes": "Delivery notes",
    "deliveryTime": "Delivery time",
    "supportUpload": "It supports uploading XLS, xlsx, Doc, docx, PDF, rar, zip, BMP, JPG, JPEG, PNG, TIF, GIF, CSV and other formats, and a single file shall not exceed 5m",
    "dragFile": "Drag the file here, or click upload",
    "enclosure": "So attachment",
    "confirmDispatch": "Confirm dispatch information",
    "schedulingList": "Scheduling list",
    "successfulDelivery": "Order distribution succeeded, please go to",
    "cannotGet": "Unable to get scheduling list!",
    "notificationFailed": "Notification failed. Please complete the information in the red box first",
    "saveFailed": "Failed to save, please maintain first",
    "saveScheduleSuccess": "Saved successfully. The dispatcher has been notified",
    "doNotClickAgain": "The notice has been sent. Please do not click again",
    "notificationSucceeded": "Notification succeeded!",
    "schedulingComplete2": "The scheduling is completed and the operation has been notified for follow-up",
    "cancelled": "Cancelled",
    "weighed": "Weighed",
    "hasLeftTheFactory": "Left the factory",
    "weHaveArrivedAtTheFactory": "Arrived at the factory",
    "deliveredCabinet": "Cupboard raised",
    "carAssigned": "Dispatched car",
    "theTeamHasPickedUp": "The team has received the order",
    "orderSent": "Dispatched order",
    "offlineDistribution": "Offline distribution",
    "waitingList": "Dispatch list",
    "pleaseInput": "Please enter {val1}",
    "enterPackingTime": "Please enter the packing time",
    "notUpdate": "The data was not updated. Please try again later",
    "updateSuccess": "Data update succeeded, please check",
    "dataLoading": "Data loading, please wait",
    "onYourPage": "There is content modification on your page. Please save it before performing this operation"
  },
  "Constants": {
    "insideTheDock": "Weighing in the wharf",
    "outsideTheFactory": "Overweight outside the factory",
    "outsideTheFactory2": "Empty weight outside the factory",
    "inTheFactory": "Factory weighing",
    "noNeedToWeigh": "No weighing required",
    "transportationCompleted": "Transportation completed",
    "theCarIsNotFinishedYet": "Vehicle dispatch not completed",
    "vehicleAssignment": "Car dispatching Commission",
    "noticeOfArrival": "Arrival notice"
  },
  "Model": {
    "china": "China",
    "operationFailed": "Operation failed, the [pre port Trailer operation] position is required!",
    "notificationFailed": "Notification failed, the [pre port Trailer operation] position is required!",
    "notificationFailed2": "Notification failed, the position of [fleet dispatcher] is required!",
    "boxTypeAndVolume": "Box type box quantity must have a box quantity greater than zero"
  },
  "RsModel": {
    "theCarHasBeenDispatched": "The car dispatch has been completed. The car dispatch cannot be completed again!"
  },
  "TrailerDynamicQuery": {
    "serialNumber": "Serial number",
    "boxType": "Box type",
    "ctnNumber": "BOx number",
    "paperStripSeal": "paper strip seal",
    "tareWeight": "Tare weight",
    "driver": "Driver",
    "carNumber": "Car number",
    "driverTel": "Driver telephone",
    "suitcasePoint": "Suitcase point",
    "suitcaseTime": "Suitcase time",
    "arrivalTime": "Arrival time",
    "departureTime": "Departure time",
    "stationName": "Station name",
    "enterStationTime": "Time of entering the station",
    "leaveStationTime": "Time of leaveing the station",
    "enclosure": "Enclosure",
    "fileName": "File name",
    "uploadTime": "Upload time",
    "download": "Download",
    "lookUp": "Look up"
  },
  "HistoryRecords": {
    "historyRecords": "Historical records",
    "updateContent": "Update content",
    "updateTime": "Update time",
    "dataSources": "Data sources",
    "change": "C"
  }
}