export default {
  Index: {
    verificationFailed: '验证未通过，请修改列表中飘红数据',
    atLeastOne: '至少有一条箱型箱量记录',
    changeBoxType: '更改箱型箱量',
    viewBoxType: '查看箱型箱量',
    detailed: '明细',
    cancel: '取消',
    noInfoCtn: '不赋值导入',
    infoCtn: '赋值集装箱',
    determine: '确定',
    okToDelete: '确定删除么?',
    containerCapacity: '箱量',
    boxQuantityIsRequired: '箱量必填',
    boxType: '箱型',
    boxTypeIsRequired: '箱型必填',
    boxTypeAndQuantity: '箱型箱量',
    addSpecification: '+ 增加规格',
    containerNo: '集装箱不能超过250个',
    batchAdd: '批量新增',
    repeat: ' {val1}重复！',
    caseNo: '箱号：({val1})',
    atMost: '最多只能添加20个规格',
    boxEast: '箱东',
    isEmptyBox:'是否空箱',
    boxEastIsRequired: '箱东必填',
    boxRequirements: '用箱要求',
    sealLength: '封号长度不能超过30',
    title: '封号',
    boxNumberFormat: '箱号格式不符合规范！',
    caseNoCanOnly: '箱号只能输入英文、数字和英文字符',
    caseNumber: '箱号',
    boxTypeIsRequired2: '箱型必填,且不能为中文',
    fullName: '全称',
    code: '代码',
  },
};
