export default {
  BKGDraggerUpload: {
    uploadFile: '上传文件失败',
    uploadSucceeded: '上传成功',
  },
  BKGTable: {
    enclosure: '附件',
    toUpdate: '更新',
    uploadAttachment: '上传附件',
    uploadFile: '上传文件失败',
    uploadFile2: '上传文件成功',
    chineseSymbols: 'M。',
    singleFile: '单个文件大小必须大于0KB，小于',
    preservation: '保存BKG',
    required: 'BKG NO必须填写',
    reAnalysis: '重新解析',
    areYouSureYouWantToPayAttention: '确定要重新解析吗？',
    abortAnalysis: '中止解析',
    areYouSureYouWantToWin: '确定要中止解析吗？',
    cancel: '取消',
    beDivorcedFrom: '脱离',
    viewDetails: '查看详情',
    areYouSureYouWantToDelete: '确定要删除吗？',
    disassociate: '取消关联BKG成功！',
    disassociate2: '解除关联BKG成功！',
    areYouSureYouWantToTurnItOff:
      '确定要{val1}关联BKG吗？{val2}后，会同时删除对应的【配舱回单】和【预配舱单】',
    areYouSureYouWantToTurnItOff2: '确定要{val1}关联BKG吗？',
    masterOrderNo: '主单号',
  },
  BKGUploadDialog: {
    uploadFile: '上传文件',
    pleaseSelect: '请选择',
    analysisTemplate: '解析模版名称',
    businessType: '业务类型',
    shippingCompany: '船公司',
    singleMaximum: '单次最多支持选择{val1}个文件上传，单个文件最大{val2}MB。',
    upload: '上传BKG',
    individual: '个',
    uploadFile2: '上传文件个数不得超过',
  },
};
