export default {
  BnContainerNotRelateListDialog: {
    associatedContainer: '关联集装箱',
    relation: '关联',
    associatedContainer2: '关联集装箱失败',
    associatedContainer3: '关联集装箱成功',
  },
  BnContainerRelationList: {
    associatedContainer: '关联集装箱',
    container: '集装箱',
    confirmDisengagement: '确认脱离？',
    breakAwayFromSuccess: '脱离成功',
  },
  BnStoreBtn: {
    areYouSureYouWantToDelete: '确定删除此内装计划',
  },
  BnStoreDetail: {
    theresNothingWrong: '暂无任何计划，点这里',
  },
  BnStoreTab: {
    interiorPlan: '内装计划',
  },
  Config: {
    encasementRequirements: '装箱要求',
    warehouseAddress: '仓库地址',
    latestArrival: '最晚进港时间',
    loadingTime: '内装时间',
    packagePlural: '包装复数',
    oddNumberOfPackages: '包装单数',
    packaging: '包装二字码',
    contactNumber: '联系电话',
    customer: '客户',
    warehouseContact: '仓库联系电话必填',
    warehouseContact2: '仓库联系电话',
    warehouseContact3: '仓库联系人必填',
    warehouseContact4: '仓库联系人',
    pleaseSelectWarehouse: '请选择仓库',
    entryCode: '进港编码',
    pleaseEnterANon: '请输入非中文字符',
    vesselNameAndVoyage: '船名/航次',
    warehousingNo: '进仓编号必填',
    warehouseEntryNumber: '进仓编号',
    warehouseEntryEditor: '进仓编辑',
  },
  BnStoreContent: {
    status: '状态：',
  },
  BnWarehousingList: {
    open: '打开',
    warehousingInformation: '入库信息',
    cargoPhotos: '货物照片',
    model: '车型',
    multipleTicketsPerCar: '一车多票',
    abnormalCondition: '异常情况',
    shippingMarkTotal: '唛头（总）',
    incomingVolume: '进仓体积（总）',
    incomingWeight: '进仓重量（总）',
    numberOfPiecesInWarehouse: '进仓件数（总）',
    registrationTime: '登记时间',
    jiYiDaJin: '集翊达进仓编号',
  },
  BnWarehousingListDialog: {
    total: '合计(Total):',
    warehousingInformation: '入库信息详情',
    shippingMark: '唛头',
    volume: '体积',
    weight: '重量',
    pieceWeight: '件重',
    number: '件数',
    packing: '包装',
    nameOfGoods: '货名',
  },
};
