export default {
  BookingDetailCtnsNoHocForm: {
    unsaved: '(未保存的数据将被忽略）',
    onYourPage: '您页面上存在内容修改，您确定要离开吗？',
    confirmDeletion: '确认删除吗？',
  },
  BoxCommonFuncs: {
    specialType: '特种',
    noUseNoHeap: '免用免堆',
    heavy: '重',
    singleContainerVolume: '单箱货量',
    actual: '实际',
    day: '天',
    outside: '场外',
    onSite: '场内',
    heapFreeApplication: 'POD免堆申请',
    applicationForExemption: 'POD免用申请',
    heapFreeApplication2: 'POL免堆申请',
    applicationForExemption2: 'POL免用申请',
  },
  BoxFreeDetailDialog: {
    noUseNoHeap: '免用免堆',
  },
  BoxSizeDetailDialog: {
    check: '校验',
    superHigh: '超高',
    high: '高(m)',
    superWide: '超宽',
    wide: '宽(m)',
    superLong: '超长',
    long: '长(m)',
  },
  Carrier: {
    cannotEnter: '不能输入中文且长度不超过30',
    contactEnglish: '联系人英文名称',
    address: '地址',
    contacts: '联系人Email',
    contactPeople: '联系人手机',
    contactNumber: '联系人电话',
    contacts2: '联系人',
    name: '名称',
  },
  CarrierWebsiteLink: {
    theShipCompany: '该船公司没有对应网站',
  },
  EfclScnChooseDialog: {
    choice: '{val1}选择',
    notifier: '通知人',
    consignee: '收货人',
    consignor: '发货人',
  },
  EfclScnDetail: {
    contactMail: '联系人邮箱',
    contactPhone: '联系人电话/传真',
    contacts: '联系人',
    code: 'AEO代码',
    companyEmail: '公司邮箱',
    telephoneFax: '电话/传真',
    codeType: '代码类型',
    countryCode: '国家代码',
    countryCode2: '国家/代码',
    provinceCode: '省份/代码',
    zipCodeCity: '邮编/城市',
    companyAddress: '公司地址',
    corporateName: '公司名称',
    enterpriseCode: '企业代码类型',
    companyCode: '公司代码',
    lengthCannot: '长度不能超过{val1},只能输入数字英文和特殊字符',
    requiredItemsOnly: '必填项只能输入',
  },
  EfclScnDetailDialog: {
    notifier: '通知人3',
    notifier2: '通知人2',
  },
  EfclScnList: {
    contactPerson: '联系人传真',
    contactEnglish: '联系人英文名字',
    contactEnglish2: '联系人英文地址',
    companyEnglish: '公司英文名称',
    total: '共 {val1} 条',
  },
  ShipperAndConsignee: {
    logisticsInformation: '物流信息(公测)',
    pleaseChooseToPay: '请选择付款依据',
    paymentBasis: '付款依据',
    isItAllowed: '是否允许付款',
    placeOfPayment: '付款地点',
    accountingPeriod: '账期',
    nonTicketSettlement: '非票结',
    paymentBeforeArrival: '到港前付款',
    ticketSettlement: '票结',
    monthlySettlement: '月结',
    settlementMethod: '结算方式',
    paymentMethod: '付款方式',
    signingTime: '签单时间',
    placeOfIssue: '签发地点',
    numberOfCopies: '副本份数',
    numberOfOriginals: '正本份数',
    signingMethod: '签单方式',
    deliveryMode: '出单方式',
    billOfLadingRequirements: '提单要求',
    logisticsInformation2: '物流信息',
    shipWithThis: '以此发货人为真实SHIPPER订舱',
    noCoverage: '不覆盖',
    cover: '覆盖',
    sendingAndReceivingInsideAndOutside:
      '里外收发通信息不一致，是否用详情信息覆盖？',
  },
};
