export default {
  BookingBasePrice: {
    cost: '成本',
    amountOfMoney: '金额',
    number: '数量',
    pleaseSelectAMeter: '请选择计费单位',
    billingUnit: '计费单位',
    pleaseSelectCurrency: '请选择币别',
    currency: '币别',
    unitPrice: '单价',
    settlementUnit: '结算单位',
    pleaseChooseToPay: '请选择付费方式',
    paymentMethod: '付费方式',
    pleaseChooseAFee: '请选择费用名称',
    feeName: '费用名称',
    floorPrice: '底价',
    chineseSymbols: '】',
    equivalent: '【折合CNY: ',
  },
  bidder: '拿价人： {val1}',
  receivable: '应收',
  chineseSymbols: '（{val1}）',
  amountOfMoney: '金额',
  number: '数量',
  pleaseSelectAMeter: '请选择计费单位',
  billingUnit: '计费单位',
  pleaseSelectCurrency: '请选择币别',
  currency: '币别',
  unitPrice: '单价',
  pleaseSelectAKnot: '请选择结算单位',
  settlementUnit: '结算单位',
  pleaseChooseToPay: '请选择付费方式',
  paymentMethod: '付费方式',
  pleaseChooseAFee: '请选择费用名称',
  BookingFeePay: {
    freight: '运费',
    referenceSuccessful: '引用成功',
    costPrice: '成本价',
  },
  feeName: '费用名称',
  Index: {
    feeInformation: '费用信息',
  },
  referenceSuccessful: '引用成功',
  offer: '报价',
  Util: {
    mustBe: '[`${k}`] 必须为array！！',
  },
};
