export default {
  HeaderInfo: {
    bookingStatus: '订舱状态',
    services: '服务项:',
    exit: '已退关',
    importAndExport: '进/出口',
    lclSubList: '拼箱子单',
    lclMasterList: '拼箱主单',
    commissionNo: '委托号',
  },
  HeaderMenu: {
    changeOrder: '改单',
    recordingSnapshot: '录单快照',
    pickUp: '提货',
    cargoInfo: '货物信息'
  },
  OrderRefuse: {
    refuseTo: '拒绝至',
    refuseSuccess: '拒绝成功',
  },
  BusinessMenuConstants: {
    logisticsTracking: '物流跟踪',
    changeOrderAndAllocation: '改单改配',
    fileManagement: '文件管理',
    requestInformation: '托书信息',
    recordSnapshot: '委托快照',
    firstInstanceSnapshot: '一审快照',
    firstInstance: '一审',
    recordingDetails: '录单详情',
    documents: '单证',
    manifest: '舱单',
    interiorDecoration: '内装',
    operationDetails: '操作详情',
  },
  Constants: {
    semilunarKnot: '半月结',
    zhouJie: '周结',
    recEditFinish: '应收录入完成',
    payEditFinish: '应付录入完成',
    check: '买单',
    notSubmitted: '未提交',
    shanghaiHuanshi: '上海环世捷运物流有限公司佛山分公司',
    shanghaiHuanshi2: '上海环世捷运物流有限公司广州分公司',
    shanghaiHuanshi3: '上海环世捷运物流有限公司深圳分公司',
    passedTheInternalAudit: '内审通过',
    passedTheFirstInstance: '一审通过',
    approved: '已审单',
    pendingFirstInstance: '待一审',
    draft: '草稿',
    lockOrderTaken: '锁单已取消',
    lockedOrder: '已锁单',
    newBillOfLading: '新提单',
    independentSettlement: '独立结算',
    addedConnected: '新增已接收',
    modifyReceived: '修改已接收',
    cancelReceived: '取消已接收',
    newRejected: '新增已拒绝',
    modificationRejected: '修改已拒绝',
    cancelRejected: '取消已拒绝',
    newIssued: '新增已发送',
    modifyIssued: '修改已发送',
    cancelSent: '取消已发送',
    seaSpellCanBeSigned: '海拼可签单',
    warehoused: '已入库',
    warehouseReceipt: '进仓单',
    refusalOfPerformance: '履约拒绝',
    entrustmentRejection: '委托拒绝',
    entrustedAcceptance: '委托受理',
    notAccepted: '未受理',
    assigned: '已分配',
    unassigned: '未分配',
    shanghaiHuanshi4: '上海环世捷运物流有限公司大连分公司',
    shanghaiHuanshi5: '上海环世捷运物流有限公司',
    shanghaiHuanshi6: '上海环世捷运物流有限公司厦门分公司',
    shanghaiHuanshi7: '上海环世捷运物流有限公司青岛分公司',
    shanghaiHuanshi8: '上海环世捷运物流有限公司福州分公司',
    shanghaiHuanshi9: '上海环世捷运物流有限公司南京分公司',
    shanghaiHuanshi10: '上海环世捷运物流有限公司宁波分公司',
    shanghaiHuanshi11: '上海环世捷运物流有限公司天津分公司',
    shanghaiHuanshi12: '上海环世捷运物流有限公司连云港分公司',
    completed: '已完成',
    toBeConfirmed: '待确认',
    identifyExceptions: '识别异常',
    toBeIdentified: '待识别',
    acceptException: '接收异常',
    toBeUploaded: '待上传',
    afterSavingYouCan: '保存后可上传文件',
  },
  Documents: {
    sendOut: '发送AMS',
    notSaved: '未保存',
    status: '状态：',
    confirm: '是否确认删除选中的AMS?',
    cancelDeletion: '取消删除',
    pleaseSelect: '请选择Type of Entry',
    detailedInformation: '详细信息第三列',
    stateAndOperation: '状态及操作',
    sendingForm: '发送形式',
    itCanOnlyBeDoneByBigCompanies: '只能由大写字母及数字组成',
    theLengthCannotBeChanged: '长度不能大于10',
    lengthCannot: '长度不能超过{val1},只能输入数字英文和特殊字符',
    maximumLength: '最大长度不能超过1500字符',
    serviceSelection: '服务选择',
    pleaseInput: '请输入Commodity',
    serviceSelection2: '服务选择内容',
    detailedInformation2: '详细信息第二列',
    detailedInformation3: '详细信息第二列内容',
    detailedInformation4: '详细信息第一列',
    onlyInput: '只能输入不超过4个大写英文字符',
    cannotInput: '不能输入中文字符',
    required: '必填项，只能输入不超过7 个字符的数字',
    consignees: '收货人的美国报税号',
    canadian:
      '加拿大的入境类型：\n-进口货物（等同于港到港，最终目的地是加拿大，发Emanifest）\n-转运货物去美国（等同于TransitExport,最终目的地在美国，发ACI）\n-留在船上（等同于StayOnBoard，不在加拿大卸货，发ACI）\n-内陆运输（最终目的地是加拿大，发Emanifest）',
    splittingStatus: '拆单状态',
    lockOrderStatus: '锁单状态',
    hasBeenConsolidated: '已被并单，无法撤销所有拆单！',
    pleaseEnterTheLatest: '请输入最多200个非中文字符',
    onlyInput2: '只能输入不超过10个大写英文字符',
    confirmThatItWillComeOff: '确认将{val1}脱离当前提单吗？',
    currentBillOfLading: '当前提单已合并',
    onlinePassengers: '【线上客户发起并单】，',
    consolidationPlease: '并单，请知晓。',
    billingInformation: '打单信息与提单详情匹配度为：',
    overwrite: '是否覆盖收发通打单内容?',
    thisTransceiver: '此收发通内容格式可用作EDI 发送，不建议覆盖',
    minimumCharacters: '最少3字符，最多26字符，不能有数字、中文和特殊字符',
    companyAddress: '公司地址2',
    formatIs: 'CA格式为:LNL NLN N为数字，L为字母',
    formatIs1: 'US格式为:NNNNN, NNNNNNNNN, or NNNNN-NNNN N为数字，L为字母',
    formatIsOr: 'US格式为:NNNNN, NNNNNNNNN, 或 NNNNN-NNNN N为数字，L为字母',
    notPerLine: '每行不得超过{val1}个字符!',
    maximumInput: '最多输入{val1}行!',
    customerBillOfLading: '客商提单信息',
    codePublic: '代码、公司英文名、联系人英文名、联系人英文地址、打单内容',
    matchingDegree: '匹配度',
    total: '共 {val1} 条',
    saveAndSelect: '保存并选择',
    billOfLadingAddress: '提单地址',
  },
  EtdWarning: {
    afterMonths: 'ETD 为6个月后',
    afterMonths1: ' ETD 为6个月后',
    earlierThanToday: 'ETD 早于今日',
  },
};
