export default {
  Index: {
    needToBeDealtWith: '待办',
    schedule: '日程',
    system: '系统',
    booking: '订舱',
    firstInstance: '一审',
    entrust: '委托',
    revoke: '撤销',
    cancelImportant: '取消重要',
    signImportant: '标记重要',
    withdrawalSuccessful: '撤回成功',
    unmark: '取消标记成功',
    markSuccessful: '标记成功',
  },
  CardTitle: {
    chineseSymbols: '{val1}（{val2}）',
  },
  ContentArrangeMessage: {
    initiator: '发起人：{val1}',
  },
  ContentRemarkMessage: {
    clickSend: '点击【发布】更新备注',
    cancel: '取消',
    release: '发布',
    toUpdate: '更新',
  },
  MessageOperations: {
    follow: '关注',
    cancelFollowing: '取消关注',
    revoke: '撤销',
    reply: '回复',
    more: '更多',
    closed: '已取消关注',
    followed: '已关注',
    entrustmentRemarks: '委托备注',
    bookingRemarks: '订舱备注',
    remarksOfTheFirstInstance: '一审备注',
    systemMessages: '系统消息',
    needToBeDealtWith: '待办',
    fileManagement: '+文件管理',
  },
  Config: {
    missingPacking: '漏装',
    modification: '改配',
    schedule: '日程',
    needToBeDealtWith: '待办',
    changeOrder: '改单',
  },
};
