export default {
  DetailForm: {
    offlineConfirmation: '线下确认',
    wenRayModel:
      '文鳐3PL/4PL模式都为线上确认，如遇特殊场景需转线下确认时，勾选此选项',
    pleaseSaveItFirst: '请先保存确认单',
    sent: '已发送，不允许操作',
    currentTariff: '当前资费项：',
    remove: '移出',
    electronicInvoice: '电子发票',
    moveIn: '移入(',
    invoiceType: '发票类型',
    transferableCapital: '可移入资费项：',
    pleaseSelectThe: '请选择需要移入的费用',
    nonElectronicHair: '非电子发票时，寄票地址中收件人地址必填，请先维护',
    mailingAddress: '寄票地址',
    cellPhoneNumber: '手机号: {val1}',
    mailbox: '邮箱: {val1}',
    telephone: '电话: {val1}',
    addressee: '收件人: {val1}',
    address: '地址: {val1}',
    provinceAndCity: '省市区: {val1}/{val2}/{val3}',
    corporateName: '公司名称: {val1}',
    ticketAddress: '寄票地址是否存在',
    cellPhoneNumber2: '手机号: {val1}',
    mailbox2: '邮箱: {val1}',
    telephone2: '电话: {val1}',
    addressee2: '收件人: {val1}',
    address2: '地址: {val1}',
    provinceAndCity2: '省市区: {val1}/{val2}/{val3}',
    corporateName2:
      '公司名称：{val1}\n联系人：{val2}\n电话号码：{val3}\n电子邮箱：{val4}',
    customerConfirmation: '客户确认人',
    pleaseSelectOr: '请选择或输入客户确认人',
    selectCustomer: '选择客户确认人',
    collectionAccountNumber: '收款账号',
    settlementEntity: '结算主体',
    companyTitle: '公司抬头',
    explain: '说明',
    checkCollection:
      '勾选代收代付，在此确认单保存后，会将实际结算公司回填至费用明细',
    pleaseInputOn: '请输入开票说明',
    customerBilling: '客户开票抬头',
    pleaseEnterTheKnot: '请输入结算信息',
    customerConfirmed: '客户已确认',
    bill: '账单(BMS)',
    invoiceApplication: '开票申请',
    pattern: '模式',
    pushPortal: '推送门户确认单',
    confirmationNumber: '确认单号',
    pleaseSelectFirst: '请先选择开票抬头，在点击修改',
    pleaseSelectAKnot: '请选择结算单位！',
    pleaseConfirmTheJump: '请确认跳转前已经保存费用确认单！',
    pleaseSelectAGuest: '请选择客户确认人',
    pleaseSelectSend: '请选发送确认单或勾选线下确认',
    wenRayConfirmed: '文鳐确认单单线上发送后，无法手动确认',
    pleaseChooseToSend: '请选择发送模式',
    saveAndMake: '保存并使用',
    editNew: '{val1}开票信息',
    newSuccessfully: '新建成功',
    domesticMerchants: '国内客商开票抬头不可存在空格，请检查',
    outOfService: '停用',
    default: '默认',
    recipientHand: '收件人手机长度不超过30个字符',
    recipientHand2: '收件人手机',
    recipientCall: '收件人电话长度不超过30个字符',
    addresseesTelegram: '收件人电话',
    recipientPlace: '收件人地址长度不超过100个字符',
    addresseesAddress: '收件人地址',
    recipientLength: '收件人长度不超过100个字符',
    addressee3: '收件人',
    ticketAddress2: '寄票地址长度不超过100个字符',
    pleaseEnterTheLocation: '请输入地址且长度不超过100个字符',
    pleaseEnterYourEmailAddress: '请输入发票抬头且长度不超过100个字符',
    invoiceTitle: '发票抬头',
    pleaseEnterNa: '请输入纳税人识别号且长度不超过100个字符',
    taxpayerAwareness: '纳税人识别号',
    pleaseEnterSilver: '请输入银行账号且长度不超过100个字符',
    bankAccount: '银行账号',
    pleaseEnterSilver2: '请输入银行名称且长度不超过100个字符',
    bankName: '银行名称',
    telephoneLength: '电话长度不超过30个字符',
    generalTaxation: '一般纳税人',
    billingType: '开票类型',
  },
  ExpressModal: {
    sendEveryone: 'ExpressModal 发件人人手机号',
    sendingStaff: '发件人手机号',
    recipientHand: '收件人手机号',
    recipientHand2: 'ExpressModal 收件人手机号',
    maintain: '维护',
    clickTheButton: 'ExpressModal 点击按钮',
    button: 'ExpressModal 按钮',
    success: '成功',
    contactAddress: '联系地址',
    backfillContent: '回填内容',
    backFillingToCustomer: '回填至客商',
    pleaseEnterBit: '请输入11位手机号',
    sendersTelegram: '发件人电话',
    from: '发件人',
    from2: '发件方地址',
    sender: '发件方公司',
    recipientMail: '收件人邮箱',
    destination: '收件方地址',
    provinceAndCity: '省市区',
    receivingParty: '收件方公司',
    sendersLetter: '发件人信息',
    thirdPartyPayment: '第三方付',
    paidByTheReceiver: '收方付',
    recipientsLetter: '收件人信息',
    senderPays: '寄方付',
    pleaseChooseCustomers: '请选择客商',
    expressCategory: '快递类别',
    courierNumber: '快递单号',
    expressDeliveryType: '快递类型',
  },
  Index: {
    newConfirmation: '新增确认单',
    pleaseEnterItFirst: '请先录入资费项',
    expenseConfirmation: '费用确认列表',
    pleaseTransferInCapital: '请移入资费项！',
    currentOrder:"当前订单已锁定代收代付不支持修改",
    wenYaoPush:'文鳐推送',
    whetherToSynchronize:'是否同步将确认单推送文鳐（门户）？'
  },
  Utils: {
    wenRayConfirmed: '文鳐确认结果',
    wenRayConfirmed2: '文鳐确认状态',
    invoiceStatus: '发票状态',
    invoiceNo: '发票号',
    billingStatus: '账单状态',
    billNo: '账单号',
    customerConfirmation: '客户确认日期',
    customerConfirmation2: '客户确认',
    confirmSingleIssue: '确认单发送日期',
    confirmSingleIssue2: '确认单发送',
    expenseConfirmation: '费用确认单号',
    wenRaySettlement: '文鳐结算单位',
    orgName: '结算公司',
    withholdingTaxRatio: '预扣税率',
    currencySystem: '币制',
    company: '单位',
    collect: '收',
    pay: '付',
    yes: '是',
    no: '否',
    reversal: '冲正',
    paymentType: '收付类型',
    generated: '已生成',
    partialGeneration: '部分生成',
    notGenerated: '未生成',
    unconfirmed: '未确认',
    billingCompleted: '开票完成',
    partialBilling: '部分开票',
    applied: '已申请',
    partialApplication: '部分申请',
    notApplied: '未申请',
    open: '是',
    close: '否',
  },
};
