export default {
  Routes: {
    trailerScheduling: '拖车调度列表',
    oneMomentPlease: '请稍等',
    frontEndTransfer: '前端中转页面',
    mailTest: '邮件测试',
    settlementDocumentFee: '结算单-费用',
    detailedStatement: '结算单-详情',
    orderNo: '约号订单',
    shipownerBusiness: '船东业务',
    marineExport: '海运外拼进口',
    marineExport1: '海运外拼出口',
    marineExport2: '海运出口整箱 改单改配详情',
    marineExport3: '海运出口整箱 改单改配申请',
    costAdjustment: '费用调整提交弹出框',
    marineExport4: '海运出口整箱 改单改配',
    marineExport5: '海运出口整箱 BKG详情',
    marineExport6: '海运出口整箱 单证',
    marineExport7: '海运出口整箱 费率模板选择',
    marineExport8: '海运出口整箱 费用确认单',
    marineExport9: '海运出口整箱 舱单',
    marineExport10: '海运出口整箱 订舱',
    marineExport11: '海运出口整箱 费用',
    railwayDomesticTrade: '铁路内贸',
    railwayImport: '铁路进口',
    railwayExport: '铁路出口',
    marineMiscellaneous: '海运件杂货内贸',
    marineMiscellaneous1: '海运件杂货进口',
    marineMiscellaneous2: '海运件杂货出口',
    groundService: '地面服务内贸',
    groundService1: '地面服务出口',
    selfAssemblyBySea: '海运自拼出口',
    oceanFullContainer: '海运整箱内贸',
    oceanFullContainer1: '海运整箱进口',
    marineExport12: '海运出口整箱 报关',
    marineExport13: '海运出口整箱 堆场装箱',
    marineExport14: '海运出口整箱 拖柜',
  },
};
