export default {
  CellRenderer: {
    time: 'YYYY-MM-DD HH时 dddd',
    waterPort: '水港',
    externalVoyage: '外部航次',
    nameOfVessel: '船名',
  },
  Index: {
    fastAddition: '快速新增',
    nameOfVessel: '船名',
    submit: '提交',
    submitEntrust: '提交委托',
    newlyAdded: '新增',
    newMultiAdded: '批量新增',
    pleaseEnterTheLatest: '必填，最多输入1000个字符',
    hscode: 'HSCODE 只可输入数字，请重新输入',
    savedSuccessfully: '保存成功',
    cannotBeEarlierThan: 'DEL ETA不能早于ETD！',
    wrongInput: '输入有误，请校验！',
    onlyInput: '只能输入不超过30个字符',
    onlyInput2: '只能输入不超过150个字符',
    onlyInput3: '只能输入不超过60个英文字符',
    inputLength: '输入长度不允许超过50个字符',
    outsideToday: '今天≤外部船期ETD≤PROFORMA-ETD+',
    externalShippingDate: '外部船期采集范围：',
    saveFailed: '保存失败，DEL ETA必须大于ATD！',
    illegalExistence: '存在非法字符',
    externalVoyage: '外部航次不能为空',
    warningPre: ' 警告：预计开船时间为6个月后',
    warningPre1: ' 警告：预计开船时间早于今日',
    inputNotAllowed: '不允许输入空格',
  },
};
