export default {
  BnCustomEntrustedDetail: {
    declarationList: '报关单列表',
    modeOfTrade: '贸易方式',
    customsDeclarationDetails: '报关单详情',
    collectionAndExemption: '征免',
    totalPrice: '总价',
    legalQuantity: '法定数量',
    finalPurpose: '最终目的国（地区）',
    quantityAndList: '数量及单位',
    tradeName: '商品名称、规格型号',
    commodityNumber: '商品编号',
    revisionTime: '修改时间',
    reviser: '修改人',
    creationTime: '创建时间',
    declarationRemarks: '报关备注',
    customsBroker: '报关员',
    dateOfCommission: '委托日期',
    customsDeclarationCommission: '报关委托编号',
    customsDeclarationCommission2: '报关委托详情',
    lengthCannot: '长度不能超过 500 个字符',
    lengthCannot2: '长度不能超过 20 个字符',
    cannotBeEmpty: '不能为空，长度不能超过 100 个字符',
  },
  BnCustomList: {
    customsDeclarationCommission: '报关委托编号',
    number: 'SO号',
    ofPer: '共{val1}条，每页3条',
  },
  BnCustomsDetail: {
    pleaseSelectOne: '请选择一条{val1}记录',
  },
  BnCustomsEntrustedList: {
    customsDeclarationCommission: '报关委托列表',
    noDelivery: '未派单',
    customsDeclarationStatus: 'EDI报关状态',
    completed: '已完成',
    entrusted: '已委托',
    noCommission: '未委托',
    delegationStatus: '委托状态',
    actualCustomsDeclaration: '实际报关日期',
    actualInspection: '实际报检日期',
    markFinished: '标记已完成',
    markCommissioned: '标记已委托',
    markNotCommissioned: '标记未委托',
    declareAtCustoms: 'EDI报关',
    placeAnOrder: '下单',
    atMost: '最多只能选择一条报关委托记录',
    pleaseChooseOne: '请选择一条报关委托记录',
    statusChange: '状态更改成功！',
    pleaseSelectTo: '请选择至少一条报关委托记录',
    deletionFailed: '删除失败，请稍候重试！',
    successfullyDeleted: '删除成功！',
    successfullyRejected: '拒绝成功！',
    systemDetection:
      '系统检测到您的报关计划{val1}的所有报关单均已上传附件，该报关计划是否标记【已完成】？',
    ofPer: '共{val1}条，每页3条',
  },
  Config: {
    taxCollection: '税费征收情况',
    markCode: '标记唛码及备注',
    manufacturer: '生产厂家',
    containerNumber: '集装箱号',
    packageType: '包装种类',
    netWeight: '净重(KGS)',
    contractAgreement: '合同协议号',
    incidental: '杂费',
    premium: '保费',
    transactionMethod: '成交方式',
    approvalNumber: '批准文号',
    domesticSourceOfGoods: '境内货源地',
    portOfDestination: '指运港',
    arrivalCountry: '运抵国',
    licenseKey: '许可证号',
    exceptionalRelief: '例外减免',
    internalTentative: '内部暂定',
    freeTradeAgreement: '自贸协议',
    nationalApprovalExemption: '国批减免',
    airMaterialExemption: '航材减免',
    charityForPovertyAlleviation: '扶贫慈善',
    disasterReliefDonation: '救灾捐赠',
    ownFunds: '自有资金',
    incentivePrograms: '鼓励项目',
    commonwealCollection: '公益收藏',
    winningTheLoan: '贷款中标',
    loanProject: '贷款项目',
    onshoreOil: '陆地石油',
    offshoreOil: '海上石油',
    explorationAndDevelopment: '勘探开发',
    foreignEnterprise: '外资企业',
    sinoForeignCooperation: '中外合作',
    sinoForeignJointVenture: '中外合资',
    hongKongAndMacao: '港澳OPA',
    borderSmallAmount: '边境小额',
    feedProcessing: '进料加工',
    processingWithSuppliedMaterials: '来料加工',
    processingEquipment: '加工设备',
    product: 'ITA产品 ',
    newDisplay: '新型显示器件 ',
    integratedCircuit: '集成电路 ',
    domesticEquipment: '内销设备 ',
    oceanGoingShip: '远洋船舶 ',
    vehicleCharacteristics: '整车特征 ',
    localization: '国产化',
    pelagicFishery: '远洋渔业',
    disabled: '残疾人',
    infrastructure: '基础设施',
    majorTechnology: '重大技术装备',
    majorProjects: '重大项目',
    technicalTransformation: '技术改造',
    scienceAndEducationSupplies: '科教用品',
    otherRegions: '其他地区',
    bondedArea: '保税区',
    specificArea: '特定区域',
    otherStatutory: '其他法定',
    gratuitousAid: '无偿援助',
    partsLevy: '零部件征税',
    vehicleTax: '整车征税',
    generalTaxation: '一般征税',
    natureOfTaxExemption: '征免性质',
    formOfSettlementOfExchange: '结汇方式',
    deliveryNumbers: '提运单号',
    meansOfTransport: '运输工具名称',
    exportProcessing: '出口加工区',
    bondedPortArea: '保税港区',
    logisticsPark: '物流园区',
    logisticsCentre: '物流中心',
    specialBorder: '边境特殊海关作业区',
    fullTransport: '全部运输方式',
    otherTransportation: '其它运输',
    bondedWarehouse: '保税仓库',
    mailTransportation: '邮件运输',
    transportAviation: '航空运输',
    roadTransport: '公路运输',
    waterTransportation: '水路运输',
    superviseWarehouse: '监管仓库',
    nonBondedZone: '非保税区',
    typeOfShipping: '运输方式',
    declarationDate: '申报日期',
    exportDate: '出口日期',
    recordNumber: '备案号',
    exportPort: '出口口岸',
    preRecorded: '预录入编号',
    postcode: '邮编',
    unitAddress: '单位地址',
    dateOfCompletion: '填制日期',
    entryUnit: '录入单位',
    entryClerk: '录入员',
    maximumBitSize: '最多3位小数',
  },
  Constants: {
    toBeReceived: '待接收',
    received: '已接收',
  },
};
