export default {
  BookingSendEdiModal: {
    sendManually: '手动发送',
    sendAtTheSameTime: '同时发送邮件',
    shippingCompanyCustomerService: '船司客服：',
    customerServiceEmail: '客服邮箱',
    shippingRoutes: '船司航线',
    shippingDepartment: '船司',
    shippingCompanyCustomerService2: '船司客服邮箱：',
    shippingNo: '运编号：',
    xinyunNo: '新运编号',
    originalShipmentNo: '原运编号',
    sendingMethod: '发送方式：',
    settlementAgent: '结算代理',
    sendObject: '发送对象：',
    sendOut: 'EDI发送',
    currentOperation: '当前运编号已经发送过EDI,请核实.或者请使用最新运编号发送',
    pleaseEnterANew: '请输入新运编号',
  },
  Config: {
    spontaneous: 'AMS/ACI 自发',
    issuedOnBehalfOfSee: 'AMS/ACI 代发，详情见保函',
    real: 'AMS/ACI 真实',
    informationBar: 'AMS/ACI 信息栏',
    exhibition: '展示 Booking Agent',
    whenSending: '发送EDI-SO时，会替代订舱计划港口信息中的订舱-POD信息',
    special: '特殊POD',
    customersThemselves: '客户自己',
    serviceNumber: 'YML服务号',
    salesName: '销售姓名',
    salesCode: '销售代码',
    shippingCompanySales: '船公司销售代码',
    nvocc: '无船承运人代码',
    suitcaseCalibration: 'COS提箱校验码',
  },
  Index: {
    supplementaryFields: 'EDI补充字段',
    shippingDepartmentCustomerService: '船司客服',
    shippingDepartmentCustomerService2: '船司客服邮箱',
    sendingMethod: '发送方式',
    sendTo: '发送对象',
  },
};
