export default {
  CopyFeeModal: {
    list: '{val1}列表',
    confirmReplication: '确认复制',
    updateHeader: '更新抬头-委托客户',
    originalValueIntroduction: '原值引入',
    pleaseSelectAReference: '请选择引入方式',
    introductionMode: '引入方式',
    historicalOrders: '历史订单号',
    pleaseSelectCalendar: '请选择历史订单',
    planToDealWith: '计划应付',
    planReceivable: '计划应收',
  },
  FeeDetail: {
    methodShould: 'doDel方法， 应付费用, 运费',
    methodShould2: 'doDel方法， 应付费用, 成本',
    methodShould3: 'doDel方法， 应付费用',
    methodReceivable: 'doDel方法, 应收费用',
    requestInterface: '请求接口',
    afterModification: ' 修改之后提示保存',
    entryCompleted: '录入完成按钮',
    testAdd: '测试新增接口onAddFeeRow',
    feeDeletion: '费用删除',
    zigongCity: '自贡市天力工具材料有限责任公司',
    zhouTeng: '周腾',
    changeOrder: '换单',
    towardsTheFuture: '充向未来',
    shenzhenCity: '深圳市充向未来科技有限公司',
    tianjinTianyou: '天津天有利公司(简称)',
    tianjinTianyou2: '天津天有利公司',
    freightForwardingOperation: '货代操作系统1集团总公司（简称）1',
    airFreight: '空运费',
    testSelection: '测试选择费用名称逻辑',
    theEditorCalled: '编辑了打回的费用，请先重新提交或者刷新页面！',
    feeDetails: '费用详情',
    pleaseChooseOne: '请选择一条费用数据进行复制！',
    existingInsured: '存在已保存的费用，是否确认删除？',
    existingIssued: '存在已发送的费用，无法删除',
    includeLock: '包含锁定的费用不允许删除',
    pleaseSelectAtLeast: '请至少选择一条{val1}费用进行删除！',
  },
  FeeDetailDrawer: {
    listOfDocuments: '单据列表',
    creationDate: '创建日期',
    relatedAmount: '关联金额',
    documentStatus: '单据状态',
    documentNumber: '单据编号',
    documentType: '单据类型',
    operationDepartment: '操作部门',
    salesDepartment: '销售部门',
    masterOrderNo: '主单号',
    businessOrderNo: '业务单号',
  },
  FeeDetailModel: {
    equivalentStandard: '折合本位币',
  },
  FeeDetailPresenter: {
    independentSettlement: '独立结算无法勾选内结',
  },
  FeeDetailService: {
    testReplication: '测试复制应收到应付',
    testInterface: '测试copyPlanPayList接口',
    pleaseCheckTheWords: '请检查字段',
    testInterface2: '测试copyPayList接口',
    testInterface3: '测试copyRecList接口',
    yeQichen: '叶其琛',
  },
  FeeHeadInfo: {
    displayAdjustment: '调整',
    displayReversal: '冲正',
    displayNormal: '普通',
    adjustedGross: '调整后毛利',
    equivalent: '【折合{val1}: -】',
    totalGrossProfit: '总计毛利',
    noDataAvailable: '暂无数据！',
    chineseSymbols: '【{val1}: -】',
    chineseSymbols2: '【',
    equivalent2: '折合USD',
    equivalent3: '折合',
    displayTariff: '显示资费：',
  },
  FeeOperations: {
    synchronizationPlan: '同步计划费用',
    reasonsForLoss: '亏损原因',
    reasonsForLossInfo: '亏损分类说明',
    close: '关闭',
    determine:"确定",
    cancel:"取消",
    shortcutOperation: '快捷操作',
    adjustWenRay: '调整文鳐结算单位',
    adjustmentSettlement: '调整结算单位',
    rectification: '冲正',
    batchChangeTax: '批量修改税率',
    select: '请选择',
    input: '请输入亏损说明',
  },
  FunctionButton: {
    paymentApplication: '付款申请',
    pleaseCheckNone: '请勾选未请款的费用操作',
    checkedFee: '勾选的费用{val1}已请款，请查看',
    currentPage: '当前页面有修改请先保存',
    isThePopUpWindowCorrect: '弹窗是否存在',
    nothing: '什么都没选',
    fastInternalKnot: '快速内结按钮',
    settlementUnit: '结算单位调整前后相同，无法调整',
    modifyRemarks: '修改备注',
    feeOfChoice: '选择的费用包含调整临时费用，无法操作',
    includeSubOrders: '包含子单费用，不可冲正，请到子单进行操作',
    selectedFees: '选择的费用包含冲正费用，无法操作',
    positiveOnly: '冲正仅适用于锁定的费用，请重新勾选',
    adjustmentSettlement: '调整结算单位仅适用于非锁定的费用，请重新勾选',
    internalKnotAutomatic: '内结自动生成的子费用不能使用该功能',
    pleaseDontTalkToMe: '请不要同时勾选内结与非内结的费用',
    enterFinanceFlow: '已进入财务流程的资费不可冲正，请做负数费用解决',
    chooseAndMention: '选择并提交',
    requiredTips: '必选提示',
    cancelPopUp: '取消弹窗',
    iChoseToGoInside: '选择了内结项目',
    lockSelected: '选择了锁定费用',
    noteHealth: '注意：生成应收后请关注是否需要调整应收发票类型',
    generateAR: '生成应收内结',
    modifiedSuccessfully: '修改成功！',
    unselected: '勾选了未审核订单',
    checkFee: '勾选费用已审核，无需重复操作',
    checkedChecked: '勾选了已审核订单',
    tickPrompt: '勾选提示',
    saveTips: '保存提示',
    revokeApproval: '撤销审核按钮',
    checkFee2: '勾选费用未审核，无需重复操作!',
    cancellationOfAudit: '撤销审核',
    confirmAll: '确认所有应收费用',
    expenseConfirmation: '费用确认按钮',
    wenLeiExpenses: '文鳐费用确认按钮',
    generativeRay: '生成文鳐确认单',
    operationSucceeded: '操作成功,已生成{val1}条确认单，单号：{val2}',
    noCompliance: '无符合条件的费用，无需操作',
    generateConfirmation: '生成确认单',
    confirmOperation: '确认操作代理费用',
    confirmationOfEntrustment: '确认委托人费用',
    completionOfInternalAudit: '内审完成按钮',
    thereIsAnErrorItem: '有错误项，无法完成内审，请修改',
    internalAudit: '内审',
    internalAuditCompleted: '内审完成',
    continueInternalAudit: '继续内审',
    requiredBeforeInternalAudit: '内审前需操作完成，请先进行操作完成动作!',
    auditOpinion: '审核意见',
    internalAuditRejection:'内审拒绝',
    submittedSuccessfully: '提交成功！',
    international: '是否国际业务',
    fastInternalFixation: '快速内结',
    isItNecessary: '是否需要航管录入海运费？',
    unwanted: '不需要，录入已完成',
    yesYes: '需要，通知航管',
    costEntry: '成本录入完成',
    entered: '已录入完成',
    inputCompleted: '录入完成',
    operationTime: '操作时间:',
    operator: '操作人:',
    notificationSucceeded: '通知成功',
    requestSucceeded: '请求成功',
    includeCost: '包含成本tab',
    includingFreight: '包含运费tab',
    includingFreight2: '包含运费和成本tab',
    principalSubSimpleInterest: '主子单利润',
    simpleInterestOfWork: '工作单利润',
    untaxedProfit: '含税利润',
    noTaxPayable: '含税应付',
    nonTaxableReceivables: '含税应收',
    untaxedProfitWithoutTax: '未税利润（不含税）',
    noTaxPayableWithoutTax: '未税应付（不含税）',
    nonTaxableReceivablesWithoutTax: '未税应收（不含税）',
    wuYuchao: 'wycsh(吴俞超sh)',
    wuYuchao2: 'wycjt(吴俞超jt)',
    generalElectronics: '普通电子发票',
    profitView: '利润查看',
    insurance: '保险',
    universalRapidTransit: '环世捷运',
    shanghaiHuanshi: '上海环世捷运物流有限公司',
    annualInspection: '5年年检',
    shanghaiHuanshi2: '上海环世物流（集团）有限公司',
    baseCurrency: '本位币({val1})',
    portalOverseas: '门户海外代理测试1',
    wenhuiTechnology: '文慧科技有限公司',
    operationFee: '操作费',
    generalTicket: '普票',
    vatGeneral: '增值税普通发票0%',
    profitSharing: '利润分成利润',
    byCompany: '按公司统计',
    statisticalProfit: '统计利润包含BC单费用、多税率拆分子单利润',
    statisticalProfit2: '统计利润包含多税率拆分子单利润',
    statisticsByTicket: '按票统计',
    sendCheck: '发送核对通知',
    sendOut: 'SA发送',
    theUserIsNot: '该用户未配置邮箱发送信息，请前往用户信息-邮件配置进行配置',
    continue: '继续',
    pleaseOpenItFirst: '请先打开确认单详情',
    splitButton: '拆分按钮, 校验服务项',
    splitButton2: '拆分按钮, 选了子单',
    splitButton3: '拆分按钮, 选了运费',
    splitButton4: '拆分按钮, 选择一个费用',
    splitButton5: '拆分按钮, 修改前报错',
    taxPayable: '应付税率',
    taxRateReceivable: '应收税率',
    services: 'DEL服务项',
    services2: 'POR服务项',
    workOrder: '工作单',
    joinTo: '加入到已拆单',
    newOrder: '新增订单',
    splitMode: '拆分方式',
    splitCosts: '拆分费用订单',
    pleaseSelectAtLeast: '请至少选择一个子单',
    pleaseChooseAtLeast: '请至少选择一个服务项！',
    beforeSplitting: '拆分前',
    taxRate: '税率',
    invoiceType: '发票类型',
    batchChangeTax: '批量修改税率',
    cannotExist: '存在无法使用当前税率的费用',
    chineseSymbols: '、',
    chapterIiBankAssets: '第{val1}行资费不适用于当前税率，请重新选择',
    notSelectable: '不可选择已锁定费用，请先解锁',
    pleaseSelectFirst: '请先选择选中费用的结算单位及服务环节',
    notAtTheSameTime: '不可同时选择应收应付进行批量修改税率',
    pleaseSelectFee: '请选择费用进行批量修改税率',
  },
  MergeFeeBtn: {
    syncToMeter: '同步至计划',
    planningCosts: '计划费用',
    actualCost: '实际费用',
    costItems: '费用项目',
    associationStatus: '关联状态',
    currentPageLetter: '当前页信息有修改，请先保存！',
    notAssociated: '未关联',
    associated: '已关联',
  },
  TableComponents: {
    equivalentTo: '折合：',
    subtotalOriginal: '小计：原币：',
    totalOriginal: '合计：原币：',
    allSettlement: '全部结算公司',
  },
  TagTabs: {
    wenRayExpenses: '文鳐费用确认单',
    expenseConfirmation: '费用确认单',
    feeList: '费用列表',
  },
  __tests__: {
    fastTest: '测试快速内结按钮是否存在',
    fastTesting: '测试快速内结按钮',
    splitButton: '拆分按钮',
    testWhether: '测试selectedKeys是否被清空',
  },
  Constants: {
    pleaseDontTick: '请不要勾选内结费用!',
    pleaseDontTick2: '请不要勾选锁定费用!',
    pleaseSaveFirst: '请先保存费用!',
    pleaseDontTick3: '请不要勾选子单!',
    pleaseDontTick4: '请不要勾选运费！',
    pleaseCheckShould: '请勾选应收、成本或者运费！',
    pleaseCheckTheBox: '请勾选运费！',
    pleaseCheckAs: '请勾选成本！',
    pleaseCheckShould2: '请勾选应收、成本！',
    profitSharing: '利润分成',
    newCollection: '新增揽货代理费用',
    newOperation: '新增操作代理费用',
    newTrailer: '新增拖车行费用',
    newBoatman: '新增船公司费用',
    newStorage: '新增仓储公司费用',
    newCustomsDeclaration: '新增报关行费用',
    already: '已',
    stay: '待',
    ministry: '部',
    not: '未',
    writeOffCompleted: '核销完成',
    partialWriteOff: '部分核销',
    notWrittenOff: '未核销',
    approved: '已审批',
    partialApproval: '部分审批',
    partialSettlement: '部分结清',
    settled: '已结清',
    uncleared: '未结清',
    partialRegistration: '部分登记',
    registered: '已登记',
    unregistered: '未登记',
    invoiced: '已开票',
    notInvoiced: '未开票',
    notified: '已通知',
    noNotice: '未通知',
    reconciled: '已对账',
    noReconciliation: '未对账',
    reviewed: '已审核',
    notReviewed: '未审核',
    existingAudited: '存在已审核的费用，不能',
    existingDisassembled: '存在已拆分的费用，不能',
    theExistenceIsConfirmed: '存在已确认的费用，不能',
    existenceHasEntered: '存在已进入财务流程的费用，不能',
    split: '拆分',
  },
  FeeEditStrategy: {
    pleaseSelect: '请选择应付费用！',
    editedTheTune: '编辑了调整被打回的费用，请刷新页面或重新提交后在操作',
    ningboInternational: '宁波125国际物流有限公司',
    includeSettlement: 'WyDcFeeEditStrategy addRec 包含结算单位',
    includeSettlement2: 'wyFeeEditStrategy addRec 包含结算单位',
    includeSettlement3: 'defaultFeeEditStrategy addRec 包含结算单位',
    logistics: 'XXX物流',
    newName: 'G1000073新名称',
    includeSettlement4: 'wyDcFeeEditStrategy addTemplateFee 包含结算单位',
    includeSettlement5: 'wyFeeEditStrategy addTemplateFee 包含结算单位',
    includeSettlement6: 'defaultFeeEditStrategy addTemplateFee 包含结算单位',
    asianShipping: '亚海航运',
    shanghaiWenlei: '上海文鳐',
    cost: '{val1}费用',
    notApplicableTo:
      '{val1}, 不适用于当前业务单业务类型，请取消相应的费用勾选，在点击确定',
    pleaseSelectShould: '请选择应收费用！',
  },
  Rule: {
    subSingleLocking: '子单锁定',
    serverLock: '服务端锁定',
    thePrevious: '上一个',
    differentBusiness: '不同业务主体锁定',
    newSettlement: '新增-结算单位',
    allowEditing: '允许编辑',
    matchField: '匹配字段',
    matchingRules: '匹配规则',
    expenseEditing: '费用编辑规则',
    locking: '锁定',
    innerKnotGeneration: '内结生成费用',
    notLocked: '未锁定',
    costAllocation: '费用配置',
    savedSuccessfully: '保存成功!',
    whole: '全部',
    unknownGauge: '未知的规则',
    pairNotFound: '未找到对应编辑规则,请联系管理员',
    customerCare: '客户自理',
  },
  Store: {
    fastInternalFixation: '快速内结Action',
    onlySelected: 'has 只选择了运费',
    onlySelected2: 'has 只选择了成本',
    xiaXiaoShanghai: '上海夏晓锋',
    wenhuiTechnology: '文慧科技',
    oceanFreight: '海运费',
    lockButton: '锁定按钮',
  },
  TableRender: {
    nonTaxExempt: ' 非免税',
    dutyFree: ' 免税',
    taxExemptNonExempt: '{val1}',
    income: '收入',
    pleaseCheckTheWord: '请检查字段编辑规则',
    quantityCannot: '数量不能为0',
    noMoney: '币别不能为空',
    settlementUnit: '结算单位不能为空',
    invoiceType2: '发票类型不能为空',
    actionBar: '操作栏',
    clearingCompany: '结算公司不能为空',
    unitPriceCannot: '单价不能为0',
    unitPriceCannot2: '单价不能为空',
    serviceLink: '服务环节不能为空',
    billingUnit2: '计费单位不能为空',
    expenseName: 'tableRenderHelper feeitem 费用名称',
    invoiceType: 'tableRenderHelper invoiceTypeId 发票类型',
    operation: 'tableRenderHelper opFixedRight 操作',
    billingUnit: 'tableRenderHelper unit 计费单位',
    taxRate: '税率 readonly additionalrate',
    taxRate1: '税率 input additionalrate',
    quantity: '数量 readonly count',
    quantity1: '数量 input count',
    currency: '币别 readonly ctnno',
    currency1: '币别 input ctnno',
    currency2: '币别 readonly currency',
    currency3: '币别 input currency',
    settlementUnit1: '结算单位 input customername',
    expenseName1: '费用名称 render form',
    expenseName2: '费用名称 render readonly',
    invoiceType1: '发票类型 内结只显示相同费率发票',
    clearingCompany1: '结算公司 input orgName',
    unitPrice: '单价 readonly price',
    unitPrice1: '单价 input price',
    quantity2: '数量 readonly remark',
    quantityPoint: '数量 input remark，点击切换',
    quantity4: '数量 input remark',
    serviceLink1: '服务环节 render readonly',
    actualSettlement: '实际结算公司 readonly settlementOrgName',
    actualSettlement1: '实际结算公司 input settlementOrgName',
    billingUnit1: '计费单位 readonly unitName',
    settlementUnit2: '结算单位 readonly wyCustomerName',
    settlementUnit3: '结算单位 input wyCustomerName',
  },
  Tables: {
    newExpenses: '新增费用',
    copyToShould: '复制到应收',
    copyHistory: '复制历史费用',
    addFees: '添加费用成功',
    clearSort: '清空排序',
    clearFilter: '清空筛选',
    partialConfirmation: '部分确认',
    copyToShould2: '复制到应付',
    copyToProfit: '复制到利润分成',
    copyToShipment: '复制到运费',
    copyToAssembly: '复制到成本',
    line: '{val1}第{val2}行: {val3}',
    quantityCannot: '数量不能为空或0，已设为默认值1',
    pairNotFound: '未找到对应的费用',
  },
  Util: {
    confirmExpenses: '确认{val1}{val2}费用',
    unknown: '未知',
    grossProfitRate: '毛利率',
    equivalent: '折合{val1}',
  },
  Utils: {
    fixedValue: '固定值',
    testLock: '测试锁定',
    subOrderFee: '子单费用',
    nonCurrentFee: '非当前费用创建所属业务主体',
    exchangeRateCannot: '汇率不能为空',
    feeName: '费用名称不能为空',
  },
  FeeAddForCustomer: {
    freightCharges: '运费费用新增',
    costExpense: '成本费用新增',
    expensesReceivable: '应收费用新增',
  },
  FeeClientLock: {
    current: '是否当前干系人所属业务主体',
  },
  FieldEdit: {
    feeUnlocked: '费用未锁定锁定',
    costLocking: '费用锁定',
    internalSettlementFee: '内结子费用可编辑',
    noEditing: '没有编辑权限',
  },
  TableRenderHelper: {
    expenseTaxRate: '费用税率',
    readOnlyInvoice: '只读发票类型',
    invoiceStatus: 'tableRenderHelper invoiceStatus 发票状态',
    invoiceNo: 'tableRenderHelper invoiceStatus 发票号',
    settlementUnit: 'tableRenderHelper shortName 结算单位简称',
  },
  SaveInfoModal: {
    feeTitle:"费用",
    tariffAdjustment: '资费调整',
  },
};
