export default {
  FormConfig: {
    approvalProcess: '审批流程',
    informationTips: '信息提示框',
    approval: '审批id',
    reason: '原因id',
    tariffAdjustment:
      '/gm2-fms-rest/rest/selectOp/otherData?type=资费调整原因分类',
    reasonsForAdjustment: '调整原因分类',
    tariffAdjustment2: '资费调整说明',
    attachmentDownload: '附件下载url',
    enclosure: '附件url',
    nameOfAttachment: '附件名称',
    accidentReport: '事故报告',
    businessLoss: '/gm2-fms-rest/rest/selectOp/otherData?type=业务亏损原因分类',
    reasonsForLossTwo: '二级分类',
    reasonsForLossOne: '一级分类',
    remark: '备注',
    info: '提示',
    handleWay: '处理方式',
    statementOfLoss: '亏损说明',
    reasonsForLossTwoMessage: '请选择二级分类',
    reasonsForLossOneMessage: '请选择一级分类',
  },
  Index: {
    approvalProcess: '审批流程',
    theBusinessSheet: '该业务单已内审，如需继续请填写资费调整说明后提交审批',
    tariffAdjustment: '资费调整提交后将进入审批流程，审批通过后费用正式生效',
    pleaseSelectApproval: '请选择审批流以及审批人',
  },
  Util: {
    pleaseSelectApproval: '请选择审批人',
    fullName: '姓名',
    jobNumber: '工号',
    canOrSign: '(可或签)',
    tariffAdjustment: '2资费调整申请',
    reasonsForLoss: '1.亏损原因',
  },
};
