export default {
  FilterService: {
    directCustomers: '自揽直客',
    chinaDay: 'CNJ（中国/日本航线）',
    commonGoods: '普货',
    juhanEnterprise: '聚涵企业',
    export: '出口',
    fclBySea: '海运整箱',
    tradeTerms: '贸易条款',
    consignee: '收货人',
    shipper: '发货人',
    shipside: '码头',
    solicitationMethod: '揽货方式',
    country: '国家',
    advancePayment: 'MBL预到付: FREIGHT PREPAID',
    routeMedium: '航线: CNJ（中国/日本航线）',
    billingUnit: '计费单位: 20GP',
    validFrom: '有效期:自然日--2021-07-08',
    portOfDeparture: '起运港',
    generalGoods: '货类: 普货',
    validityAdvance: '有效期:预计离港日--2021-07-31',
    validityAdvance2: '有效期:预计到港日--2021-07-31',
    portOfDestination: '目的港: TOKYO',
    entrustedUnit: '委托单位: 聚涵企业',
    carrier: '承运人',
    importAndExportStandard: '进出口标识',
    businessType: '业务类型: 海运整箱',
    termOfValidity: '有效期:{val1}--{val2}',
    arrivalDay: '进港日',
    customsBroker: '报关行',
    expectedArrival: '预计到港日',
    fleet: '车队',
    expectedDeparture: '预计离港日',
    warehouse: '仓库',
    naturalDay: '自然日',
    station: '场站',
    actualDeparture: '实际离岗日',
    terminal: '航站',
    wharf: '码头',
    shippingAgent: '船代',
    overseasAgency: '海外代理',
    bookingAgent: '订舱代理',
    forwardingUnit: '发货单位',
    ctnNo: '箱号',
    sealNo: '封号',
    ctnType: '箱型',
    vgm: '件毛体',
    existContainer: '集装箱数据匹配',
  },
  Index: {
    rateTemplate: '费率模板选择',
    expensesPayable: '应付费用方案',
    expensesReceivable: '应收费用方案',
    pleaseSaveItFirst: '请先保存业务单',
    chooseOther: '选择其他方案',
    quickIntroduction: '快速引入方案',
    currentBusiness: '当前业务仅匹配到一条费用方案，是否直接引入？',
    tips: '提示',
  },
  Utils: {
    shippingAgent: '船代',
    overseasAgency: '海外代理',
    bookingAgent: '订舱代理',
    forwardingUnit: '发货单位',
    chinaUniversity: 'CJR（中国大陆长江内贸航线）',
    domesticTrade: '内贸',
    piece: '件',
    generalChemicalIndustry: '一般化工品',
    fee: 'F费1',
    individualLevel: '个人级',
    departmentLevel: '部门级',
    companyLevel: '公司级',
  },
};
