export default {
  BnFileBatchAdd: {
    pleaseInputText: '请输入文件号',
    documentNumber: '文件号字符过长',
    pleaseSelectTheText: '请选择文件类型',
    selectFile: '选择文件：',
    batchAddition: '批量添加文件',
    chineseSymbols: 'MB。',
    onAFile: '个文件上传，单个文件最大',
    singleMost: '单次最多支持选择',
    fileUpload: '{val1} 文件上传失败！',
    single: 'H单',
    single2: 'M单',
    fileType: '文件类型不能为空！',
    mustUpload: '必须上传文件',
  },
  BnFileHistoryList: {
    historicalVersion: '历史版本',
    download: '下载',
    filingTime: '归档时间',
    filer: '归档人',
    sourceOfDocuments: '文件来源',
    fileSize: '文件大小',
    fileType: '文件类型',
    fileName: '文件名称',
    total: '共 {val1} 条',
  },
  BnFileLayout: {
    filingOfDocuments: '文件归档',
  },
  BnFileList: {
    noteText: '注意：文件对哪些岗位可见需在文件类型基础资料配置',
    documentNumber: '文件号',
    fileName: '文件名称',
    filerOnly: '仅归档人可修改或删除文件',
    fileCannot: '文件不能超过50个',
    pleaseSelectOne: '请选择一个文件',
    addFile: '添加文件',
    batchAddition: '批量添加',
    pushToTheDoor: '推向门户',
    batchDownload: '批量下载',
    filingOfDocuments: '文件归档列表',
    total: '共 {val1} 条',
  },
  BnFileTrackList: {
    trackingSteps: '追踪步骤',
    documentFollowUp: '文件跟进列表',
    onYourPage: '您页面上存在内容修改，您确定要切换到其它文件吗？',
    sendABill: '寄单',
    operatingInstructions: '操作说明',
    completionStatus: '完成状态',
    pedagogicalOperation: '操作描述',
    operationSteps: '操作步骤',
    fileStatus: '文件状态',
    mailingTask: '寄单任务号',
    sendGet: '发送/获取对象',
    documentNumber: '文件号',
    filerOnly: '仅归档人可删除文件',
    operationFailed: '操作失败，文件已寄单，不能删除',
    atLeast: '至少需要选择一个文件寄单',
    youCanOnlyChoose: '只能选择未寄单的文件',
    total: '共 {val1} 条',
  },
  BnFileUpload: {
    chineseSymbols: '/  : * " < > | ？',
    onlyUpper: '只支持上传PDF，Word，Excel，图片，邮件 文件类型 压缩文件。',
    selectFile: '选择文件',
    modificationOfDocuments: '修改文件',
    fileUpload: '文件上传失败！',
  },
  EFile: {
    toAdd: '去新增',
    noDataAvailable: '暂无数据',
    singleAgency: 'M单代理单',
    pleaseSaveFirst: '请先保存当前内容，再进行操作！',
    documentFollowUp: '文件跟进',
    noteOfMailing: '寄单备注',
    deliveryTime: '寄送时间',
    mailingInformation: '寄单信息容器',
    mailingInformation2: '寄单信息',
    mailingStatus: '寄单状态',
    releaseRejection: '放单拒绝时间',
    releasePass: '放单通过时间',
    rejectComments: '拒绝备注',
    throughRemarks: '通过备注',
    releaseApproval: '放单审核人',
    applicationRemarks: '申请备注',
    applicationTime: '申请时间',
    applicant: '申请人',
    releaseInformation: '放单信息容器',
    releaseInformation2: '放单信息',
    orderTakingTime: '取单时间',
    noBill: '未取单',
    fetchedOrder: '已取单',
    orderFetchingStatus: '取单状态',
    retrievalInformation: '取单信息容器',
    retrievalInformation2: '取单信息',
    documentComments: '文件备注',
    relatedBillOfLading: '关联提单号',
    fileInformation: '文件信息容器',
    fileInformation2: '文件信息',
    releasedOrder: '已放单',
    notReleased: '未放单',
    chineseSymbols: '寄单详情',
  },
  ExpressModal: {
    spellIn: '拼入',
    fileList: '文件列表',
    printing: '打印',
    electronicMailingList: '电子寄单',
    mailingStatus: '寄单状态：',
    mailingTask: '寄单任务号：',
    pleaseFillInTheReceipt: '请填写收件人邮箱！',
    atLeastAdd: '至少添加一个文件！',
  },
};
