export default {
  AdSearchCondition: {
    accountType: '账户类型',
    settlementType: '结算类型',
    ownBank: '己方银行',
    expenditure: '支出',
    delivery: '外送',
    takeItFromYourself: '自取',
    retained: '留存',
    mail: '邮寄',
    howToSendTickets: '寄票方式',
    advancePayment: '预收款',
    writeOffMode: '核销模式',
    exported: '已导出',
    notExported: '未导出',
    paymentStatus: '请款状态',
    bigExpenses: '支出大',
    bigIncome: '收入大',
    reconciliationType: '对账类型',
    multiCurrency: '多币别',
    firstFlight: '头程航班/航次',
    departureTime: '离港时间',
    templateDeletion: '模板删除失败！',
    templateSaving: '模板保存失败！',
    pleaseInputModule: '请输入模板名',
  },
  AdSearchConditionRuleCheck: {
    pleaseInputCustomers: '请输入客户名称搜索',
    customerName: '客户名称',
    pleaseEnterTheShip: '请输入船公司中文、英文',
    pleaseEnterTheFlightNumber: '请输入航线',
    pleaseInputTheService: '请输入服务模块',
    serviceModule: '服务模块',
    departureTime: '离港时间',
    templateDeletion: '模板删除失败！',
    templateSaving: '模板保存失败！',
    pleaseInputModule: '请输入模板名',
    wholeTicket: '整票',
  },
  BaseDataComponet: {
    writeOffItems: '核销项目',
    accountingDimension: '核算维度-其他',
    exportBySea: '海运出口',
  },
  Common: {
    compulsorySettlement: '强制结清',
    internalContacts: '内部往来',
    advanceCollectionAndAccountAdjustment: '预收调账',
    jobNo: '工作单号',
    bankProcedures: '银行手续费大于等于回款金额，取消继续',
    bankProcedures2: '银行手续费大于等于回款金额，是否继续？',
  },
  PermissionControl: {
    noRightToRestrictVisits: '无权限访问！',
  },
  Select: {
    noMatchingKnot: '无匹配结果',
  },
};
