export default {
  BasicDataConstant: {
    other: '其它',
    freezing: '冷冻',
    danger: '危险',
    overrun: '超限',
    ordinary: '普通',
  },
  GoodsDetailDialog: {
    cargoInformation: '货物信息',
  },
  GoodsDetail: {
    cargoInformation: '货物信息',
    englishName: '英文品名',
    shippingMark: '唛头',
    high: '高(cm)',
    wide: '宽(cm)',
    long: '长(cm)',
    more: '更多',
    commodityClassification: '商品分类',
    chineseName: '中文品名',
    typeOfGoods: '货物类型修改成功，请点击保存!',
    operationFailed: '操作失败，请稍后重试',
  },
  GoodsListDetailDialog: {
    listOfGoods: '货物列表',
  },
  listOfGoods: '货物列表',
  refresh: '刷新',
  operationFailed: '操作失败，请稍候重试！',
  customColumns: '自定义列保存成功！',
  details: '详情',
  HSCodeList: {
    pleaseInput: '请输入 HS Code',
    customsNo: '海关编号',
    pleaseChooseOne: '请选择一条记录！',
    pleaseInput2: '请输入HS Code',
  },
  OtherSpecialGoods: {
    otherSpecials: '其他特货类型',
    typeOfGoods: '货物类型',
  },
  savedSuccessfully: '保存成功，装箱信息内货物信息未同步，需保存或刷新页面',
  operationFailed2: '操作失败，请稍后重试',
  pleaseChooseOne: '请选择一条记录！',
  successfullyDeleted: '删除成功',
  successfullyDeleted2: '删除成功，装箱信息内货物信息未同步，需保存或刷新页面',
  SpecialDetail: {
    outOfGaugeGoods: '超限货',
    frozenGoods: '冷冻货',
    dangerousGoods: '危险品',
    pleaseEnterTheLatest: '请输入最多500个非中文字符',
    specialRemarks: '特货备注',
    transfiniteHeight: '超限-高',
    overrunRight: '超限-右',
    overrunLeft: '超限-左',
    afterOverrun: '超限-后',
    beforeOverrun: '超限-前',
    foot: '英尺',
    rice: '米',
    dimensionUnit: '尺寸单位',
    ventilationSheet: '通风量单位',
    ventilationRate: '通风量',
    maximumTemperature: '最高温度',
    minimumTemperature: '最低温度',
    setTheTemperature: '设置温度',
    fahrenheit: '华氏',
    centigrade: '摄氏',
    temperatureUnit: '温度单位',
    emergencyContact: '紧急联系电话',
    emergencyContact2: '紧急联系人',
    medicalFirstAid: '医疗急救指南',
    seriousPollution: '严重污染',
    thereIsPollution: '有污染',
    pollutionFree: '无污染',
    waterTransportPollution: '水运污染',
    emergencyMeasure: '应急措施号',
    minimumRisk: '最小危险',
    generalHazard: '一般危险',
    theMostDangerous: '最危险',
    packagingGroup: '包装组别',
    flashPointUnit: '闪点单位',
    flashPoint: '闪点',
    internationalDangerousCode: '国际危码',
    hazardCodePage: '危规页码',
    level: '级别',
  },
  SpecialDetailDialog: {
    specialGoods: '特殊货物',
  },
};
