export default {
  Index: {
    fromClipboard: '从剪贴板粘贴数据',
    assignment: '赋值',
    importMode: '导入方式：',
    rowStartGuide: '行开始导入，上面的行不使用',
    fromTheFirst: '从第',
    pastePlateGuide: '粘贴板导入',
    storageNotAllowed: '不允许存在重复的列头',
    mustSelect: '必须选择一列为箱型',
    pleaseCopyFirst: '请先复制数据',
    doNotUseThis: '不使用此列',
    pleaseEnterTheCombination: '请输入合法的数字',
    totalWeight: 'VGM总重量',
    emptyWeight: '空箱重',
    weighingMethod: '称重方法',
    volume: '体积',
    grossWeight: '毛重',
    packagingType: '包装类型不能输入中文',
    packingType: '包装类型',
    pleaseEnterTheCombination2: '请输入合法的件数',
    number: '件数',
    caseNumberLength: '箱号长度不能超过11位，只能输入英文、数字和英文字符',
  },
};
