export default {
  CommonHelper: {
    loadingFailed: '加载失败，请稍候重试!',
    noBackstage: '后台没有返回错误信息!',
    templateName: '模板名称已存在，请重新输入',
  },
  BasicDataConstant: {
    noInvoice: '不开发票',
    vatGeneral: '增值税普通电子发票',
    incompleteInvoice: '未开票完成',
    voucher: '凭证',
    notGenerated: '未生成凭证',
    writeOff: '核销',
    unprinted: '未打印',
    partialPayment: '部分付款',
    partialAcceptance: '部分受理',
    paid: '已付款',
    toBePaid: '待付款',
    pending: '待受理',
    requestFunds: '请款',
    toVoid: '作废',
    receiptReceived: '已收账单',
    reserved: '已订舱',
    inProcess: '处理中',
    noBooking: '未订舱',
    checkOrder:
      '勾选【订舱】、【代订舱】、【拖柜】服务项的业务，集装箱列表不能没有集装箱',
    containerSchool: '集装箱校验',
    excluding: '2、不含有订舱服务的，不为0并且所有费用的税率必须相同。',
    includingSubscription: '1、含有订舱服务时，所有费用的税率应该为0或免税。\n',
    verificationService: '校验业务的服务是否有“订舱”服务，\n',
    expenseTaxRate: '费用税率校验',
    ifSo: '如果有，校验不通过',
    inspectionPlan:
      '检查计划费用中费用名称是否设置了设置了费用分类为退佣（包括一级分类、二级分类、三级分类），',
    specialExpenses: '特殊费用项校验',
    verificationService2: '校验业务中实际费用利润是否等于计划费用利润',
    profitVerification: '利润校验',
    whenAndAllPass: '当1和2都通过时，费用记账汇率校验通过',
    iInBusiness: '2、业务中所有的记账汇率时是否相同，相同为通过\n',
    comparisonBasis:
      '1、比对基础资料-企业基础资料-浮动汇率中对应的记账汇率，相同为通过\n',
    accordingToEach: '根据每笔费用的财务日期校验费用的记账汇率\n',
    recordingRate: '记账汇率校验',
    calibrationCost:
      '校验费用中的费用名称是否与基础资料-费用税率中的费用名称一致',
    feeName: '费用名称校验',
    forOperation:
      '3、为操作站时，校验收款列表中的海运费或空运费的结算单位是否为销售公司，且销售站的海运费金额是否等于操作站的海运费金额',
    forSales:
      '2、为销售站时，校验付款列表中的海运费或空运费的结算单位是否为操作公司，且销售站的海运费金额是否等于操作站的海运费金额\n',
    verificationYes: '1、校验是否发生费用协同\n',
    cooperationFee: '协同单费用校验',
    calibrationFee:
      '校验费用中应收费用列表和应付费用列表中的结算单位是否与客商资料里面对应公司的全称不匹配',
    settlementUnit: '结算单位校验',
    checkAndUnload: '校验卸货港与航线的对应关系是否与基础资料港口维护的一致性',
    portAndNavigation: '港口与航线对应关系校验',
    checkBillOfLading:
      '校验SI提单中的【提单类型】、【提单号】是否有值（勾选【订舱】/【代订舱】同时业务已放舱）',
    typeOfBillOfLading: '提单类型校验',
    checkIn:
      '2、校验在SI只存在一个MBL的前提下，SI这个MBL的MBL号与操作详情的MBL号保持一致（勾选【订舱】/【代订舱】同时业务已放舱）',
    verificationWithdrawal:
      '1、校验SI提单中的【实际开船时间】与操作详情【实际开船时间】一致性（勾选【订舱】/【代订舱】同时业务已放舱）\n',
    andOperationDetails: 'SI与操作详情校验',
    checkContainer:
      '校验集装箱TAB中集装箱列表箱号是否有值（海运整箱出口勾选【订舱】/【代订舱】/【拖柜】时）',
    boxNumberVerification: '箱号校验',
    checkSubscription:
      '8、勾选订舱、代订舱服务时，【实际开船时间】不能早于【截关时间】',
    checkSubscription2:
      '7、勾选订舱、代订舱服务时，【预计开船时间】不能早于【截关时间】\n',
    checkSubscription3: '6、勾选订舱、代订舱服务时，【截关时间】需要有值\n',
    checkBarge: '5、勾选驳船服务时，【驳船实际开船时间】需要有值\n',
    checkAndDrag: '4、勾选拖柜服务时，【预计装箱时间】需要有值\n',
    estimated: '3、【预计开船时间】需要有值\n',
    actual: '2、【实际开船时间】需要有值\n',
    business: '1、【业务日期】需要有值\n',
    timeVerification: '时间校验',
    checkTheLatest:
      '8、校验最终目的地有值的情况下，最终目的地在基础资料中是否存在',
    checkNavigation: '7、校验航线有值的情况下，航线在基础资料中是否存在\n',
    calibrationAndUnloading:
      '6、校验卸货港有值的情况下，卸货港在基础资料中是否存在\n',
    calibrationEquipment:
      '5、校验装货港有值的情况下，装货港在基础资料中是否存在\n',
    checkTheLatest2: '4、校验最终目的地有值（勾选【订舱】/【代订舱】时）\n',
    checkNavigation2: '3、校验航线有值（勾选【订舱】/【代订舱】时）\n',
    calibrationAndUnloading2:
      '2、校验卸货港有值（勾选【订舱】/【代订舱】时）\n',
    calibrationEquipment2: '1、校验装货港有值（勾选【订舱】/【代订舱】时）\n',
    portCalibration: '港口校验',
    verificationOperation:
      '校验操作详情的箱型箱量、SO的箱型箱量、集装箱的箱型箱量是否一致（海运整箱出口勾选【订舱】/【代订舱】/【拖柜】时）',
    boxTypeAndQuantity: '箱型箱量校验',
    checkOverseas:
      '校验海外代理在客商中是否存在（勾选【目的港换单】/【DDU】/【DDP】时）',
    overseasAgency: '海外代理校验',
    checkDelivery: '校验发货单位在客商中是否存在',
    forwardingUnit: '发货单位校验',
    calibrationBoatman:
      '校验船公司在客商中是否存在（勾选【订舱】/【代订舱】时）',
    shippingCompanySchool: '船公司校验',
    checkBooking: '校验订舱代理在客商中是否存在（勾选【订舱】/【代订舱】时）',
    bookingAgent: '订舱代理校验',
    verification: '2、校验【操作】有值',
    verification2: '1、校验【销售】有值（协同单除外）\n',
    postVerification: '岗位校验',
    verificationDelegation: '校验委托单位在客商中是否存在',
    client: '委托单位校验',
    actual2: '2、【实际发车时间】需要有值',
    verification3: '1、校验【起运站】、【目的站】有值（勾选【订舱】时）',
    siteVerification: '站点校验',
    checkingAndBooking: '校验订舱代理在客商中是否存在（勾选【订舱】时）',
    checkLoading: '校验装货港与航线的对应关系是否与基础资料港口维护的一致性',
    actual3: '2、【实际到港时间】需要有值',
    checkNavigation3: '6、校验航线有值的情况下，航线在基础资料中是否存在',
    calibrationAndUnloading3:
      '5、校验卸货港有值的情况下，卸货港在基础资料中是否存在\n',
    calibrationEquipment3:
      '4、校验装货港有值的情况下，装货港在基础资料中是否存在\n',
    checkNavigation4: '3、校验航线有值\n',
    calibrationAndUnloading4: '2、校验卸货港有值\n',
    calibrationEquipment4: '1、校验装货港有值\n',
    advanceCharge: '预付款',
    businessGuarantee: '业务担保',
    oceanRoute: '近洋航线',
    creditLine: '信用额度内',
    seeWaterList: '见水单',
    receivableReceived: '应收已收',
    voucherPreparationAndSettlement: '制单结算重量',
    billingByVoucherPreparation: '制单计费重量',
    productionVolume: '制单体积',
    grossWeightOfSheetMaking: '制单毛重',
    numberOfUnits: '制单件数',
    weightSettlement: '交重结算重量',
    paymentByWeight: '交重计费重量',
    crossWeightVolume: '交重体积',
    crossWeightGrossWeight: '交重毛重',
    weightPaid: '交重件数',
    weighingAndCharging: '过磅计费重量',
    weighingVolume: '过磅体积',
    grossWeight: '过磅毛重',
    weighingPieces: '过磅件数',
    estimatedBilling: '预计计费重量',
    estimatedVolume: '预计体积',
    estimatedGrossWeight: '预计毛重',
    estimatedNumberOfPieces: '预计件数',
    weightVolume: 'W/M(重量/体积)',
    value: '货值',
    ticket: '票',
    box: '箱',
    shanghaiTemplate: '上海模板',
    nanjingFormwork: '南京模板',
    ningboTemplate: '宁波模板',
    tianjinWaidai: '天津外代模板',
    defaultTemplate: '默认模版',
    out: '出HB/L',
    out2: '出MB/L',
    billOfDeposit: '押单',
    noCharge: '未押单',
    tradeDocumentation: '贸易单证',
    letterOfGuarantee: '保函',
    billOfLading: '提单',
    collected: '已收取',
    toBeCollected: '待收取',
    canSendASingle: '可寄单',
    collectionCompleted: '取单完成',
    dispatchCompleted: '派单完成',
    orderCanBeSent: '可派单',
    passTheOrder: '放单通过',
    pending2: '待处理',
    pendingApplication: '待申请',
    goodsReleased: '已放货',
    inDischarge: '电放中',
    goodsToBeReleased: '待放货',
    declare: '申报',
    loadArrangement: '排载',
    masterWaybill: '主单运单',
    paperless: '无纸化',
    paperlessContainer: '无纸化箱单',
    separateDelivery: '分单交运',
    mainOrderDelivery: '主单交运',
    separateManifest: '分单舱单',
    masterManifest: '主单舱单',
    transportation: '交运',
    market: '市场',
    business2: '业务',
    stockOutPlan: '出仓计划',
    deliveryOfGoods: '货物交接签收单',
    warehousingPlan: '进仓计划',
    warehouseEntryNotice: '进仓通知',
    warehouseOutRecord: '出仓记录',
    warehouseEntryRecord: '进仓记录',
    exportDeclaration: '出口报关确认函',
    reinsurancePolicy: '分单',
    mainOrder: '主单COPY',
    neutralBillOfLading: '中性提单',
    mixedLoadList: '混载清单',
    operationPlan: '操作计划',
    documentaryBillOfLading: '托单/提单',
    operationSheet: '操作面单',
    longTengXiagang: '隆腾下港单',
    generalDelivery: '普货提货表',
    abnormal: '异常',
    accountDetails: '台账详情',
    allowSbToActAlone: '放单',
    deliveryOfGoods2: '放货',
    takeDeliveryOfGoods: '提货',
    custom: '自定义',
    original: '原始',
    waitingForNotice: '等待通知',
    seaWaybill: '海运单',
    electricDischarge: '电放',
    original2: '正本',
    incorrectBillOfLading: '提单未确认',
    cancellationOfBillOfLading: '取消提单确认',
    confirmationOfBillOfLading: '提单确认完成',
    detailedList: 'VGM清单',
    manifestOutput: ' 舱单输出',
    order: '订单',
    collaborativeResults: '协同结果',
    packingInYard: '堆场装箱',
    underAnalysis: '解析中...',
    noTrustLetter: '无托书',
    groupCollaboration: '集团协同',
    newBusiness: '业务新增',
    freightRate: '运价',
    orderAddition: '订单新增',
    gateway: '门户',
    internalEntrustment: '内部委托',
    entrust: 'Coload委托',
    onlineDelegation: '在线委托',
    generalEntrustment: '一般委托',
    released: '已放行',
    toBeDeclared: '待报关',
    theBusinessIsOver: '业务已完成',
    unfinishedBusiness: '业务未完成',
    firstInstanceAudit: '一审审核',
    fclBySea: '海运整箱占舱',
    fclBySea2: '海运整箱出口',
  },
  CommonFunc: {
    notePage: '注意：{val1}第{val2}条费用的 数量 与详情不一致！',
  },
  SeaUtil: {
    notifierIncluding: '通知人含有中文、中文标点、全角字符!\n',
    consigneeIncluding: '收货人含有中文、中文标点、全角字符!\n',
    shipperIncluding: '发货人含有中文、中文标点、全角字符!\n',
  },
  Rules: {
    theGreatestImpossibility: '最大不能超过',
    pleaseEnterTheWholeNumber: '请输入整数',
    pleaseEnterAnInteger: '请输入整数，范围为 0~99',
    characters: ' 个字符',
    lengthCannot: '长度不能超过 ',
    cannotBeEmpty: '不能为空，且',
    mailboxFormat: '邮箱格式不正确，且长度不能超过 100 个字符',
    lengthCannot2: '长度不能超过 60 个字符',
    lengthCannot3: '长度不能超过 400 个字符',
    lengthCannot4: '长度不能超过 200 个字符',
    lengthCannot5: '长度不能超过 1000 个字符',
    lengthCannot6: '长度不能超过 100 个字符',
    lengthCannot7: '长度不能超过 10 个字符',
    lengthCannot8: '长度不能超过 3500 个字符',
    lengthCannot9: '长度不能超过 2000 个字符',
    lengthCannot10: '长度不能超过 1750 个字符',
    lengthCannot11: '长度不能超过 600 个字符',
    cannotExceed: '不能超过 10 个字符',
    onlyInput: '只能输入英文和英文符号',
    lengthCannot12: '长度不能超过 150 个字符',
    lengthCannot13: '长度不能超过 9 个字符',
    lengthCannot14: '长度不能超过 4000 个字符',
    onlyInput2: '只能输入数字',
    cannotBeEmpty2: '不能为空，且长度不能超过 30 个字符',
    cannotBeEmpty3: '不能为空，且长度不能超过 120 个字符',
    lengthCannot15: '长度不能超过 5 个字符',
    cannotBeEmpty4: '不能为空，且长度不能超过 60 个字符',
    cannotBeEmpty5: '不能为空，且长度不能超过 10 个字符',
    cannotBeEmpty6: '不能为空，且长度不能超过 50 个字符',
    lengthCannot16: '长度不能超过 128 个字符',
    lengthCannot17: '长度不能超过 120 个字符',
    pleaseEnterTheCombination: '请输入合法的航程',
    pleaseEnterTheCombination2: '请输入合法的天数',
    pleaseEnterTo: '请输入1到99的正整数',
    lengthCannot18: '长度不能超过 1500 个字符',
    lengthCannot19: '长度不能超过 8 个字符',
    lengthCannot20: '长度不能超过 7 个字符',
    cannotBeEmpty7: '不能为空且长度不能超过 1000 个字符',
    boxTypeCannot: '箱型不能为空',
    lengthCannot21: '长度不能超过 16 个字符',
    lengthCannot22: '长度不能超过 250 个字符',
    lengthCannot23: '长度不能超过 800 个字符',
    lengthCannot24: '长度不能超过 15 个字符',
    sealLength: '封号长度不能超过30',
    caseNumberLength: '箱号长度不能超过11',
    lengthCannot25: '长度不能超过 900 个字符',
    cannotBeEmpty8: '不能为空且长度不能超过 500 个字符',
    onlyInput3: '只能输入英文',
    cannotBeEmpty9: '不能为空，长度不能超过 10 个字符',
    decimalPlaces: '小数位数不能超过2位',
    decimalPlaces2: '小数位数不能超过1位',
    decimalPlaces3: '小数位数不能超过3位',
    cannotContain: '不能含有中文、中文标点、全角字符！',
  },
};
