export default {
  Container_dynamics: {
    tare: '皮重：',
    number: '件数：',
    boxType: '箱型：',
    driversPhone: '司机电话：',
    driver: '司机：',
    licensePlateNumber: '车牌号：',
    processingTime: 'EIR办理时间',
    emptyLocation: 'EIR提空地点：',
    actualShort: '实际提空地点：',
    emptyContainer: '提空箱时间：',
    emptyTheBox: '放箱/提空',
    leaveTheDoorPoint: '离开门点时间：',
    packingCompleted: '装箱完成时间：',
    startOfPacking: '装箱开始时间',
    reachTheGatePoint: '到达门点时间',
    doorPointPacking: '门点装箱',
    actualOutOfWarehouse: '实际出仓时间：',
    actualWarehousing: '实际进仓时间',
    departurePortWarehouse: '起运港-仓库',
    confirmationTime: 'VGM确认时间',
    declarationTime: 'VGM申报时间',
    actualArrival: 'DEL 实际到港时间',
    arrivalInformation: '进港信息',
    tallyRelease: '理货放行',
    nationalInspectionRelease: '国检放行',
    dockRelease: '码头放行时间：',
    customsClearance: '海关放行时间',
    customsInspection: '海关查验时间',
    customsDeclaration: '海关申报时间',
    departurePortRelease: '起运港-放行信息',
    actualSailing: '实际开航时间',
    shipmentTime: '装船时间：',
    loadingAndSailing: 'POL 装船/开航',
    transshipmentShipment: '中转 装船/开航',
    vesselNameAndVoyage: '船名/航次：',
    timeOfShipment: '装船时间',
    unloadingTime: 'POD 卸船时间',
    arrivalTime: '到港时间',
    transitPort: '中转港：',
    portOfDestinationRelease: '目的港-放行信息',
    returnTime: '还箱时间',
    actualReceipt: '实际签收时间：',
    actualDeparture: 'DEL 实际出港时间',
    pickUpTime: 'DEL 提货时间',
    actualArrival2: 'POD 实际到港时间',
    unloadingTime2: '卸船时间',
    descendingOrder: '降序',
    ascendingOrder: '升序',
    actualSignIn: '实际签收时间',
    actualDelivery: '实际出仓时间',
    terminalRelease: '码头放行时间',
    actualArrival3: '实际进港时间',
    leaveTheGate: '离开门点时间',
    packingComplete: '装箱完成时间',
    whenEmpty: '提空箱时间',
    sortingDimension: '排序维度',
    shipment: '-装船',
    portToBeTransferred: '待中转港卸船',
    shipUnloading: '-卸船',
    boxReturned: '已还箱',
    returnBox: '待还箱',
    delivered: '已送达',
    toBeServed: '待送达',
    outOfPort: '已出港',
    waitingForDeparture: '待出港',
    unloadingAtDestinationPort: '目的港卸船',
    portOfDestination: '待目的港卸船',
    transshipmentPortLoading: '中转港-装船',
    waitingPort: '待中转港装船',
    shipped: '已装船',
    toBeShipped: '待装船',
    customsReleased: '海关已放行',
    customsToBeReleased: '海关待放行',
    customsHaveChecked: '海关已查验',
    customsToBeInvestigated: '海关待查验',
    confirmed: 'VGM已确认',
    toBeConfirmed: 'VGM待确认',
    alreadyInPort: '已进港',
    waitingForArrival: '待进港',
    getToTheGate: '到达门点',
    whenWeGetToTheFactory: '待到厂',
    emptyContainer2: '提空箱',
    caseToBePickedUp: '待提箱',
  },
  Index: {
    boxDynamics: '箱动态',
    shippingInformation: '船期信息',
  },
  Logistics_info: {
    boxReturned: '已还箱',
    returnBox: '待还箱',
    signedIn: '已签收',
    toBeSigned: '待签收',
    outOfPort: '已出港',
    waitingForDeparture: '待出港',
    arrivedInHongKong: '已到港',
    expectedArrival: '预计到港',
    sld: '已开航',
    expectedToSail: '预计开航',
    customsClearance: '海关放行',
    customsToBeReleased: '海关待放行',
    alreadyInPort: '已进港',
    waitingForArrival: '待进港',
    boxed: '已装箱',
    toBeBoxed: '待装箱',
    emptyContainer: '提空箱',
    caseToBePickedUp: '待提箱',
    gatePoint: '门点',
    customs: '海关',
    logisticsTracking: '物流跟踪进度',
  },
  Order_tracking: {
    single: 'M单:',
    single2: 'H单:',
  },
  Sailing_info: {
    placeOfReturn: '还重地点：',
    emptyLocation: '提空地点：',
    closingTime: '截关时间：',
    cutOffTime: '截VGM时间：',
    cutOffTime2: '截单时间：',
    closingTime2: '截港时间：',
    openingTime: '开港时间：',
    shippingAgency: '船舶代理：',
    nameAndVoyage: '船名航次：',
    shippingCompany: '船公司：',
    actualDeparture: '实际离泊时间：',
    actualBerthing: '实际靠泊时间：',
    plannedDeparture: '计划离泊时间：',
    plannedBerthing: '计划靠泊时间：',
    nameOfDepartingVessel: '离港船名航次：',
    portOfCall: '挂靠港：',
    berthingWharf: '靠泊码头：',
    fromHongkongPost: '起运港信息：',
    chineseSymbols: 'ETA：',
    chineseSymbols2: 'ATA：',
    portOfCall2: '挂靠港',
    chineseSymbols3: 'ETD：',
    chineseSymbols4: 'ATD：',
  },
};
