export default {
  BnManifestInfo: {
    manifestImport: '舱单导入',
    cancelManifest: '取消舱单完成',
    manifestComplete: '舱单完成',
    mainOrder: '主单',
    pleaseCheckOne: '请勾选一条要拆分的舱单！',
    onlyCheck: '只能勾选一条要拆分的舱单！',
    thisManifestIs: '此舱单是底层节点，不能继续拆分！',
    tooManySplits: '拆分的BKG NO太长了！',
    pleaseSaveItFirst: '请先保存',
    onYourPage: '您页面上存在内容修改，您确定要切换到其它舱单吗？',
    manifestOpen: '舱单未完成',
    manifestStatus: '舱单状态',
    operationFailed: '操作失败，请稍候重试',
    pleaseSelectOnly: '请仅选择一条记录',
    pleaseSelectTo: '请选择至少一条记录',
  },
  BnManifestSplit: {
    numberingRules: '编号规则',
    splitQuantity: '拆分数量',
    operationFailed: '操作失败，请稍候重试',
    pleaseInputTheDisassemblyCode: '请输入拆分数量',
    pleaseChooseToEdit: '请选择编号规则',
  },
  BookingReceipt: {
    noPleaseFirst: '无BKG NO，请先维护至少一条BKG NO',
    sameAsBooking: '从订舱同步',
    typeOfGoods: '货物类型:',
    boxTypeAndQuantity: '箱型箱量:',
    bookingReceipt: '配舱回单列表',
    onlyInput: '只能输入不超过5000个字符',
    cargoInformation: '货物信息容器',
    cargoInformation2: '货物信息内容',
    transceiverCapacity: '收发通容器',
    transceiverInternal: '收发通内容第二列',
    transceiverInternal2: '收发通内容第一列',
    basicInformation: '基础信息',
  },
  PreManifest: {
    leadSealType: '铅封类别',
    fengZhiren: '封志人',
    cartonCondition: '装箱状态',
    electronicSeal: '电子封志',
    mechanicalSeal: '机械封志',
    lclMan: '拼箱人',
    inspectionAndQuarantine: '检验检疫',
    pleaseSelectOne: '请选择一条集装箱',
    partialContainer: '部分集装箱未与集装箱列表匹配，请手动选择',
    onlyInput: '只能输入最多3位小数',
    onlyInput2: '只能输入不超过18位的数字',
    required: '必填项，请输入合法的体积',
    required2: '必填项，请输入合法的毛重',
    maximumInput: '最多输入6位数字',
    productNumber: '品号',
    import: 'Excel导入',
    preDistributionVolume: '预配货量',
    bookingVolume: '订舱货量',
    total: '合计：',
    containerCome: '集装箱来源',
    tare: '皮重',
    boxTypeAndQuantity: '箱型箱量：{val1}',
    fromMasterManifest: '从主舱单同步',
    ourCompanyCutOffTheCustoms: '我司截关时间:',
    nameAndVoyage: '船名航次:',
    bookingBoxType: '订舱箱型箱量:',
    preAllocatedManifest: '预配舱单',
    remarksContainer: '备注容器',
    remarks: '备注内容',
    containerLetter: '集装箱信息合计内容',
    containerLetter2: '集装箱信息合计',
    cargoInformation: '货物信息合计内容',
    cargoInformation2: '货物信息合计容器',
    cargoInformation3: '货物信息合计',
    transceiverInternal: '收发通内容',
    transceiver: '收发通',
    packingDetails: '装箱明细',
    packingDetails2: '装箱明细容器',
    status: 'EDI状态：',
    notifiers: '通知人的联系人信息（电话/Email/传真）至少填写一个',
    consignees:
      '收货人的联系人填写时，联系人的联系方式（电话/Email/传真）至少填写一个',
    consignees2: '收货人的联系人信息（电话/Email/传真）至少填写一个',
    shippers: '发货人的联系人信息（电话/Email/传真）至少填写一个',
  },
  Components: {
    draft: '草 稿',
    newDocument: '新单证',
  },
  ManifestDetail: {
    systemAutomation: '系统自动生成',
    totalTicketStatistics: '总票统计数据-',
    statisticsByBox: '按箱统计数据---（系统自动合成）',
    provinceCode: '省份代码',
    enterpriseCode: 'AEO企业代码',
    city: '城市',
    province: '省份',
    copyReceipt: '复制收货人信息',
    specificContact: '具体联系人',
    state: 'EDI状态:',
    totalGrossWeight: '总毛重',
    packagingUnit: '包装单位',
    areYouSureYouWantToDoIt: '确定要做手动修改吗?',
    cannotInput: '不能输入中文',
    lengthCannot: '长度不能超过{val1}',
    detailedProductName: '明细品名中的HS CODE',
    submitted: '提交的data',
    confirmImport: '确定导入吗？',
    noteMustPack: '(注：须包含表头一起复制)',
    mediumBatchRepeat: '中批量复制好信息后，粘贴至下列文本框',
    pleaseWriteInYour: '请在您的',
    detailedProductName2: '明细品名及数据',
    selectGoods: '选择货物',
    callContainer: '调用集装箱',
    thisOperation: '本次操作会覆盖当前舱单中明细品名数据，确定吗？',
    currentPage: '当前页面有修改，请先保存',
    lengthCannot2: '长度不能超过{val1},只能输入数字英文和特殊字符',
    categoryRisk: '类别(危)',
    dangerous: 'UNCode(危)',
    pleaseEnterTheNumber: '请输入数字，最大不能超过8位整数',
    onlyCheck: '只能勾选一条要复制的明细！',
    confirmToReply: '确认要复制这条明细吗？',
    associatedVoteSharing: '关联分票',
    pleaseUploadOr: '请上传xlsx或xls文件',
    importManifest: '导入舱单',
    uploadFile: '上传文件格式',
    selectImport: '选择导入模板',
    downloadDefault: '下载默认模板',
    addYourNumber: '3.将您的数据输入在excel文件中，然后上传该excel',
    redMeter: '2.红色表头表示该项为必输项，浅蓝色表头含有批注，请阅读后输入;',
    downloadTemplate: '1.下载Excel模版后，请按照模版说明进行操作;',
    uploadFile2: '上传文件说明',
    importFailed: '导入失败',
    pleasePassOnTheMessage: '请上传文件！',
    informationList: 'VGM信息列表',
    lengthCannot3: '长度不能超过{val1},只能输入数字英文和特殊字符',
    weighingTime: '称重时间',
    liabilityCompany: 'VGM责任公司',
    address: 'VGM地址',
    mailbox: 'VGM邮箱',
    telephone: 'VGM电话',
    weighingPlace: 'VGM称重地点',
    personLiable: 'VGM责任人',
    weight: 'VGM重量',
    pleaseSelectASet: '请选择集装箱进行导入',
    pleaseCorrectTheRed: '请修正红色框内信息！',
  },
  Root: {
    bookingReceipt: '配舱回单',
  },
};
