export default {
  Components: {
    cancelCompletion: '取消完成',
    actualArrival: '实际到港时间',
    actualSailing: '实际开船时间',
    estimatedStock: '预计备货时间',
    bargeActual: '驳船实际开船时间',
    cutOffTimeTheory: '截VGM时间说明',
    ourCompanyCutTime: '我司截VGM时间',
    closingTime: '截关时间说明',
    ourCompanyCutOffTheCustoms: '我司截关时间',
    closingTime2: '截港时间说明',
    ourCompanyInterceptsHongKong: '我司截港时间',
    cutOffTime: '截单时间说明',
    ourCompanyCutOffTheBill: '我司截单时间',
    shippingInformation: '海运信息跟踪',
    shippingInformation2: '海运信息跟踪第三行',
    bookingConfirmation: '订舱确认后动作',
    shippingInformation3: '海运信息跟踪第二行',
    arrivalTime: '进港时间',
    pickUpInformation: '提货信息',
    orderSupplement: '订单补录',
    goodTime: '货好时间',
    entrustmentInformation: '委托信息',
    keyInformation: '关键信息',
    saveFailed: '保存失败，DEL ETA必须大于ATD',
  },
  Util: {
    time: 'YYYY-MM-DD HH时',
  },
};
