export default {
  AddBookingOrderModal: {
    onlyLatticeIsSupported: ' 仅支持 {val1} 格式文件且文件小于{val2}M',
    pleaseChooseACarrier: '请选择托书！',
    pleaseChooseToSend: '请选择发货单位！',
    uploadOfTrustLetter: '托书上传',
    upload: '上传',
    uploadFailed: '上传失败',
    pleaseUploadIt: '请上传托书',
    within: ' 内',
    uploadFile: '上传文件类型不在 ',
    uploadFile2: '上传文件超过 ',
    areYouSureYouWantToDelete: '确认要删除选中的记录吗？',
    contactLocation: '联系人地址',
  },
  BookingOrderList: {
    anAnalysisOfEntrustment: '托书解析对比',
    bookInformation: '托书信息列表>',
    uploadAgain: '重新上传',
    reAnalysis: '重新解析&nbsp; |&nbsp;',
    numberOfPackages: '件数/包装',
    deletionFailed: '删除失败',
    accessToTrustBooks: '获取托书列表失败，请稍后再试！',
  },
  Info: {
    port: '港口',
    selectDelegate: '选择委托-运输条款',
    areYouSureYouWantToDelete: '确定要删除此箱型记录吗？',
    multiProductName: '多品名',
    multipleNotifiers: '多通知人',
    orderDetails: '订单详情内容',
    anAnalysisOfEntrustment: '托书解析内容',
    originalText: '托书原文件',
    referenceNo: '托书编号',
    detailsOfEntrustment: '托书详情内容',
    basicData: '基础资料匹配',
    forCtn: '赋值集装箱',
    cannotBeEmpty: '不能为空!',
    pleaseChoose: '请选择！',
    valueOfTheCompany: '本公司值',
    saveFailed: '保存失败！',
    mappingValue: '映射值',
    dataType: '资料类型',
  },
};
