export default {
  BasicDataConstant: {
    summaryReconciliation: '汇总对账单',
    detailedReconciliation: '明细对账单',
    bill: '账单',
    boxGuarantee: '押箱保函',
    releaseApplication: '放单申请',
    telexReleaseGuarantee: '电放保函',
    multipleVotes: '多票',
    singleTicket: '单票',
    declarationForm: '报关单',
    customsDeclarationCommission: '报关委托',
    packingRecord: '装箱记录',
    outOfWarehouseVerification: '出仓核实单',
    outOfWarehouseNotice: '出仓通知书',
    warehouseEntryVerification: '进仓核实单',
    warehouseEntryNotice: '进仓通知书',
    packingCommission: '装箱委托书',
    deliveryNotice: '送货通知',
    dispatchList: '派车单',
    cupboardPaper: '提柜纸',
    heavyCabinetPaper: '重柜纸',
    packingList: '装箱单',
    shipCertificate: 'HBL船证',
    shipCertificateTradePromotion: 'HBL船证贸促会加签',
    certificateOfOrigin: '产地证',
    freightInsurance: '货运险业务倒签保函',
    insurancePolicy: '保险单',
    otherGuarantees: '其他保函',
    noBoardingPass: '未上船证明',
    letterOfGuarantee: 'SEA WAYBILL 保函',
    missingLetterOfGuarantee: '漏装保函',
    separateAndMergeOrders: '分单并单保函',
    changeOfBillOfLading: '提单更改保函',
    billOfLading: '提单COPY件',
    confirmationPiece: 'MBL确认件',
    confirmationPiece2: 'HBL确认件',
    shippingCompany: '船公司BOOKING',
    peers: '同行BOOKING',
    bookingGuarantee: '订舱保函',
    trustLetter: '托书',
  },
  OutPutDialog: {
    output: '输出',
  },
};
