export default {
  Index: {
    information: 'PO信息',
    list: 'PO列表',
    upload: '上传',
    chineseSymbols: '/  : * " < > | ？',
    onlyUpper: '只支持上传PDF，Word，Excel，图片，邮件 文件类型 压缩文件。',
    enclosure: '附件',
    purpose: '用途',
    textureOfMaterial: '材质',
    volume: '体积',
    grossWeight: '毛重',
    packingType: '包装类型',
    number: '件数',
    commodityCategory: '商品类别',
    typeOfGoods: '货物类型',
    commodityCode: '商品编码',
    onlyInput: '只能输入非中文字符',
    customsCode: '海关编码',
    englishName: '英文名称',
    onlyInput1: '只能输入非英文字符',
    chineseName: '中文名称',
    onlyInput2: '只能输入数字英文',
    commodityBatch: '商品批次号',
    onlyInput3: '只能输入整数',
    lineNumber: '行号',
    tradeOrder: '贸易订单号',
  },
};
