export default {
  BKGListSearch: {
    searchCriteria: '搜索条件',
    placeOfDelivery: '交货地点: {val1}',
    placeOfDelivery2: '交货地点',
    finalPurpose: '最终目的地: {val1}',
    finalPurpose2: '最终目的地',
    bargeDeparture: '驳船起运港: {val1}',
    bargeDeparture2: '驳船起运港',
    shipowner: '船东: {val1}',
    shipowner2: '船东',
    query: '查询',
    phaseAlreadyExists: '已存在相同的搜索条件',
    conditionScreening: '条件筛选',
    accordingToTheConditions: '条件按',
    closingTime: '截港时间',
    sailingTime: '开船时间',
    contractNo: 'BKG NO, 合约号',
    allKindsOfNumbers: '各类编号',
  },
  Index: {
    confirmConnection: '确认关联',
    productName: '品名',
    remarksOfShipowner: '船东备注',
    closingTime: '截港时间',
    sailingTime: '开船时间',
    closingTime2: '截关时间',
    nameOfVessel: '大船船名航次',
    finalPurpose: '最终目的地',
    portOfDestination: '目的港',
    transitPort: '中转港',
    loadingPort: '装货港',
    bargeDeparture: '驳船起运港',
    contractNo: '合约号',
    associationSuccessful: '关联成功！',
    pleaseSelectOne: '请选择一个BKG！',
  },
};
