export default {
  Field: {
    notAtMost: '最多不能超过{val1}字符',
    choice: '选择',
    input: '输入',
    pleaseEnterYourChoice: '请{val1}{val2}',
  },
  Index: {
    recentMaintenance: '最近维护时间',
    recentMaintenance2: '最近维护人',
    whenDisabled: '禁用后，该数据全集团不可使用',
    whenEnabled: '启用后，该数据全集团可使用',
    disable: '禁用',
    enable: '启用',
    state: '状态',
    remarks: '备注',
    shipCallSign: '船舶呼号',
    number: 'IMO号',
    englishName: '英文名称',
    chineseName: '中文名称',
    operationSuccessful: '操作成功',
    preservation: '保存',
    rejectEntrust:"拒绝委托",
    newlyBuild: '新建',
    modify: '修改',
    modifyNew: '{val1}船舶',
    cannotEnter: '不能输入中文或者圆角标点',
    inTwoCharacters: '俩字符中间只允许输入一个空格',
  },
};
