export default {
  BnCtnList: {
    onlyInput: '只能输入不超过10位的数字, 最多3位小数',
    onlyInput2: '只能输入不超过12位的数字, 最多3位小数',
    weightPerCase: '单箱货重',
    pleaseEnterTheCombination: '请输入合法的箱量',
  },
  BnSoEdit: {
    originalDocument: 'BKG原文件',
    testSave: '测试保存',
    display: '显示',
    markRelease: '标记放舱给客户',
    doYouWantToBid: '确定要标记吗？',
    cancelRelease: '取消放舱给客户',
    areYouSureYouWantToTakeIt: '确定要取消标记吗？',
    systemDetection:
      '系统检测到所有SO均已放舱给客户，订舱状态是否自动标记【放舱给客户】？',
    success: '成功！',
    unmark: '取消标记放舱给客户',
    successfulCoverage: '覆盖成功！',
    savedSuccessfully: '保存成功！',
    boxTypeAndQuantity: '箱型箱量不能为空！',
    informationEntry: '信息录入有误，无法保存！',
    details: '{val1}-SO详情',
    pleaseSaveItFirst: '请先保存！',
  },
  BnSoLinkMains: {
    selectBooking: '选择订舱-运输条款',
    whenTheManifestIsIntercepted: '截舱单时间',
    closingDate: '截关日期',
    bargeForecast: '驳船预计开船时间',
  },
  BookingSoDetailDialog: {
    see: '查看BKG',
  },
  BnSoUploadDialog: {
    businessType: '业务类型不得为空',
    singleMaximum: '单次最多支持选择{val1}个文件上传，单个文件最大{val2}MB。',
  },
  BookingSoList: {
    relation: '关联BKG',
    pleaseProceedFirst: '请先进行保存',
    reAnalysis: '重新解析&nbsp;|&nbsp;',
    areYouSureYouWantToTake: '确定要取消关联SO吗？',
    beDivorcedFrom: '脱离&nbsp;|&nbsp;',
    areYouSureYouWantToTakeItOff: '确定要脱离关联SO吗？',
    toUpdate: '更新&nbsp;|&nbsp;',
    disassociate: '取消关联SO成功！',
    disassociate2: '解除关联SO成功！',
    releaseCabinToPassengers: '放舱给客户',
    analysisSuccess: '解析成功',
    underAnalysis: '解析中',
    parsingFailed: '解析失败',
    resolutionException: '解析异常',
    parsingState: '解析状态',
    listSubscribed: 'BKG列表 已订/总数：',
  },
  CustomerSelectDialog: {
    cannotBeEmpty: '不能为空',
    sourceOfGoods: '货物来源',
    cannotBeEmpty2: '不能为空，且长度不能超过 100 个字符',
    chooseFormal: '选择正式客商',
  },
  PublicSoList: {
    ofPer: '共{val1}条，每页15条',
  },
  ScopeCtnList: {
    pleaseEnterNo: '请输入不超过3位的正整数',
  },
  SoPortInfo: {
    onlyInput: '只能输入不超过10个的英文字符',
    unableToRemoveFrom: '  无法从SoPortInfo中获取',
  },
  VesselVoyage: {
    selectedVoyage: '选航次',
    internalVoyage: '内部航次',
    voyageLength: '航次长度不能超过 30 个字符',
    lengthCannot: '长度不能超过 50 个字符',
  },
  PropsHelper: {
    cannotBeEmpty: '{val1}不得为空',
    cannotBeEmpty2: '{val1}不得为空',
  },
};
