export default {
  Constants: {
    sourceOfGoods: '货物来源',
    booking: '订舱-POD',
    entrust: '委托-POD',
    booking1: '订舱-POL',
    entrust1: '委托-POL',
    booking2: '订舱-POR',
    entrust2: '委托-POR',
    booking3: '订舱-DEL',
    entrust3: '委托-DEL',
    booking4: '订舱-DEL ETA',
    booking5: '订舱-ETD',
    entrust4: '委托-ETD',
    customerReferenceNumber: '客户参考号',
    client: '委托单位',
    overseasAgency: '海外代理',
    bookingReceipt: '订舱-收货人',
    consignmentReceipt: '委托-收货人',
    bookingShipping: '订舱-发货人',
    consignmentShipment: '委托-发货人',
    bookingWaybill: '订舱-运单方式',
    consignmentWaybill: '委托-运单方式',
    bookingFreight: '订舱-运费条款',
    entrustedFreight: '委托-运费条款',
    tradeTerms: '贸易条款',
    bookingFlight: '订舱-航班',
    bookingAirline: '订舱-航空公司',
    entrustedAirlines: '委托-航空公司',
    bookingAgent: '订舱代理',
  },
};
