export default {
  Index: {
    specialGoods: '特殊货物',
    outOfGaugeGoods: '超限货',
  },
  Schema: {
    specialRemarks: '特货备注',
    transfiniteHeight: '超限-高',
    transfiniteRight: '超限-右',
    transfiniteLeft: '超限-左',
    afterOverrun: '超限-后',
    beforeOverrun: '超限-前',
    pleaseSelectRuler: '请选择尺寸单位',
    dimensionUnit: '尺寸单位',
    heightCannotBe: '高不能为空',
    high: '高',
    widthCannotBe: '宽不能为空',
    wide: '宽',
    lengthCannotBe: '长不能为空',
    long: '长',
    lengthCannot1: '长度不能超过 7 个字符',
    pleaseEnterTheCombination: '请输入合法的数字',
    afterDecimalPoint: '小数点后不能超过{val1}位',
  },
};
