export default {
  Column: {
    high: '高(cm)',
    wide: '宽(cm)',
    long: '长(cm)',
    volume: '体积(CBM)',
    grossWeight: '毛重(KGS)',
    packagingChange: '包装改变时count',
    complex: '复数',
    singular: '单数',
    packing: '包装',
    number: '件数',
    englishName: '英文品名',
    chineseName: '中文品名',
    serialNumber: '序号',
    high1: '高(cm)',
    wide1: '宽(cm)',
    long1: '长(cm)',
    volumeCannot: '体积不能为空',
    volume2: '体积(CBM)',
    grossWeightCannot: '毛重不能为空',
    grossWeight2: '毛重(KGS)',
    pleaseSelectAPackage: '请选择包装',
    complex1: '复数',
    singular1: '单数',
    select: '请选择',
    packing1: '包装',
    theNumberOfPiecesCannotBe: '件数不能为空',
    number1: '件数',
    noInputAllowed: '不允许输入中文字符',
    englishName1: '英文品名不能为空',
    englishName2: '英文品名',
    chineseName1: '中文品名不能为空',
    chineseName2: '中文品名',
  },
  GoodSideInfo: {
    weightClass: '重量等级:',
    heavyBubbleDifference: '重泡差:',
    cargoType: '货型:',
    foamWeightRatio: '泡重比:',
    billingWeight: '计费重量:',
    weightClass1: '重量等级',
    heavyBubbleDifference1: '重泡差',
    cargoType1: '货型',
    foamWeightRatio1: '泡重比',
    billingWeight1: '计费重量',
  },
  Index: {
    totalNumberOfPieces:
      '总件数: {val1} 件 总毛重: {val2}KGS 总体积: {val3} CBM',
  },
  AlertTip: {
    pleaseNoteThat: '请注意，预计货物与实际货物有偏差',
  },
  ActualGoodsTable: {
    delete: '删除',
    copy: '复制',
    newlyAdded: '新增',
    actualGoods: '实际货物信息',
    copyEstimate: '复制预计',
    noActualNumber: '无实际数据！',
    noEstimate: '无预计数据！',
  },
  BookingGoodsTable: {
    bookingCargo: '订舱货物信息',
  },
  EntrustGoodsTable: {
    estimatedGoods: '预计货物信息',
  },
  VoucherGoodsTable: {
    voucherGoods: '制单货物信息',
    copyActual: '复制实际',
  },
};
