export default {
  Column: {
    high: '高(cm)',
    wide: '宽(cm)',
    long: '长(cm)',
    volumeCannot: '体积不能为空',
    volume1: '体积(CBM)',
    grossWeightCannot: '毛重不能为空',
    grossWeight1: '毛重(KGS)',
    pleaseSelectAPackage: '请选择包装',
    complex: '复数',
    singular: '单数',
    select: '请选择',
    packing: '包装',
    theNumberOfPiecesCannotBe: '件数不能为空',
    number: '件数',
    noInputAllowed: '不允许输入中文字符',
    englishProductName: '英文品名不能为空',
    englishName: '英文品名',
    chineseName: '中文品名不能为空',
    chineseName1: '中文品名',
    serialNumber: '序号',
  },
  Index: {
    weightClass: '重量等级',
    heavyBubbleDifference: '重泡差',
    cargoType: '货型',
    foamWeightRatio: '泡重比',
    billingWeight: '计费重量',
    totalVolume: 'KGS 总体积:',
    totalGrossWeightOfPieces: '件 总毛重:',
    total2: '总件数:',
    copy: '复制',
    newlyAdded: '新增',
    cargoInformation: '货物信息',
    copyVoucher: '复制制单',
    listOfGoods: '货物列表数据不能超过{val1}条',
    noOddNumber: '无制单数据！',
  },
};
