export default {
  BookingFields: {
    selectTransportation: '选择运输条款',
    agreementGoods: '协议货品名',
  },
  CancelTeamWorkMessage: {
    transferToFee: '转至费用页面',
    deleteFees: '删除费用',
  },
  SiCancelInfoDialog: {
    applyForModification: '申请修改原因:',
    applicationTime: '申请时间:',
    applicant: '申请人:',
    applicant2: '申请方:',
    passTheApplication: '通过申请',
    amendmentOfBillOfLading: '提单修改申请',
  },
  TeamOrderRefuseDialog: {
    pleaseEnterReject: '请输入拒绝理由，最多1000个字符',
    reasonsForRejection: '拒绝原因',
    thisActionWill: '此操作会取消本订单，并删除本订单所有费用，确定吗？',
    informationTips: '信息提示',
    collaborativeRejection: '协同拒绝',
    collaborativeRejection2: '协同拒绝成功',
  },
  TeamWorkCancelDialog: {
    pleaseEnterWithdrawal: '请输入撤回原因，最多1000个字符',
    reasonsForWithdrawal: '撤回原因',
    noteAssociation: '注意：协同撤回需要协同方确认',
    thisActionWill:
      '此操作会取消对应协同订单，并删除协同订单的所有费用，确定吗？',
    collaborativeWithdrawal: '协同撤回',
  },
  TeamWorkDetail: {
    bookingResults: '订舱结果',
  },
  TeamWorkDetailBooking: {
    overlayToPrimary: '覆盖到主单',
    salesStation: '销售站（主）',
    bookingStatus: '订舱状态：',
    bookingStation: '订舱站（子）',
    determineCoverage: '确定覆盖至主单并保存？',
  },
  TeamWorkDialog: {
    collaborativeDistribution: '协同分配',
  },
  TeamWorkExamineTable: {
    regroup: '重新协同',
    empty: '清空',
    edit: '编辑',
    orderNumber: '订单号',
    collaborativeState: '协同状态',
    staff: '员工',
    personnel: '人员',
    businessAffairs: '商务',
    post: '岗位',
    toExamine: '审核',
    collaborationItem: '协同项',
    assignCompany: '指派公司',
    withdrawn: '已撤回',
    coordinated: '已协同',
    noCollaboration: '未协同',
  },
  TeamWorkHistoryTable: {
    collaborationDetails: '协同明细（订单号）',
    collaborationDetails2: '协同明细（岗位、人员）',
    chineseSymbols: '、',
    collaborationDetails3: '协同明细（协同项）',
    collaborationDetails4: '协同明细（指派公司）',
    collaborativeRejection: '协同拒绝原因',
    collaborativeWithdrawal: '协同撤回原因',
    operationTime: '操作时间',
    operators: '操作人所属公司',
    operator: '操作人',
  },
  TeamWorkList: {
    history: '历史',
    noteCooperation:
      '注意：协同撤回需要协同方确认，否则无法撤回（审核协同除外)',
    coordination: '协同',
    clickAdd: '+ 点击添加',
    collaborationItemNotAvailable: '协同项不能重复选择！',
    inputError: '输入错误请检查！',
    onlyAddIsSupported: '只支持添加4条数据！',
    withdrawalOfConfirmation: '撤回确认中',
    required: '必填',
    post: '岗位',
    postPersonnel: '岗位人员',
    collaborationItem: '协同项',
    assignCompany: '指派公司',
    regroup: '重新协同成功',
    rejected: '已拒绝',
    withdrawn: '已撤回',
    coordinated: '已协同',
    noCollaboration: '未协同',
  },
  TeamWorkRefuseMesDialog: {
    reasonsForWithdrawal: '撤回原因：',
    coInitiation:
      '协同发起方申请协同撤回，本订单会取消，并删除所有费用，是否接受撤回？',
    accept: '接受',
  },
  Index: {
    pleaseCheckTheService: '请勾选服务项',
  },
};
