export default {
  BnContainerCollapse: {
    clickToCollapse: '点击收起',
    clickToExpand: '点击展开',
  },
  BasicDataConstant: {
    statement: '结算单',
    customer: '客户SOC',
    circumstantialWorld: '环世SOC',
  },
  BnContainerEditList: {
    unsaved: '(未保存的数据将被忽略)',
    containerTrain: '集装箱列表存在内容修改，您确定离开吗？',
    leave: '离开',
    saveAndLeave: '保存并离开',
    belonging: '所属SO',
    operation: 'BKG操作',
    viewTheGoods: '查看货物',
    noNeed: '没有需要合计的集装箱！',
    coverage: '覆盖范围：该订单号所有集装箱',
    beSureToMeetTheRequirements: '确定要合计吗？',
    totalGoods: '合计货物信息将覆盖原有的集装箱件毛体数据',
    areYouSureYouWantToTakeRoot: '确定要根据协同主业务快速填充箱封号吗？',
    listOfGoods: '货物列表存在内容修改，您确定要切换到其它集装箱吗？',
    systemDetection:
      '系统检测到拖车计划{val1}的所有集装箱已有箱号，该拖车计划是否标记【运输完成】？',
    currentContent: '当前内容未修改',
    currentContainer: '当前集装箱关联货物{val1}累加后超过10位数，请重新输入!',
    volume: '体积，',
    weight: '重量，',
    number: '件数，',
    repeat: ' {val1}重复！',
    caseNo: '箱号：({val1})',
    pleaseCheckTheSelection: '请勾选集装箱',
    generateContainer: '生成集装箱',
    accordingToTheOperation: '根据操作详情',
    accordingTo: '根据BKG',
    totalGoods2: '合计货物信息',
    comparativeCompliance: '比对/从SI合计',
    batchMaintenance: '批量维护',
    accordingToSubOrder: '根据子单汇总',
    containerAlready: '集装箱 已完成',
    cancelSynchronization: '取消同步',
    confirmFromOrder: '确认从订舱同步集装箱信息？',
    operationFailed: '操作失败！请刷新后重试。',
    pleaseDeleteManually: '请手动删除已有的集装箱！',
    wrong: '出错了！',
    pleaseSelectTheOneYouWant: '请选择要删除的集装箱！',
    thisTime: '（本次操作会同时删除各计划内的该集装箱）',
    theContainer:
      '该集装箱已关联到【拖柜】/【仓储】/【报关】/【SI】/【舱单】计划中，确认删除吗？',
    ofPer: '共{val1}条，每页5条',
    container: '注意，集装箱箱号格式不规范',
  },
  BnContainerGoodsEditList: {
    fullFreightTrain: '全货物列表',
    cargoLoading: '货物装载列表',
    pleaseChooseOne: '请选择一个集装箱！',
    areYouSureYouWantToMove: '确定要移除货物吗？',
    containerLetter: '集装箱信息加载失败，请稍候重试！',
    nameOfGoods: '货名',
    weight: '重量(KGS)',
    associatedVoteSharing: '关联分票 ',
  },
  BnContainerList: {
    selfProvidedBox: '自备箱',
    cargoBox: '货主箱',
    shipownersBox: '船东箱',
    declared: '已申报',
    undeclared: '未申报',
    day: '{val1} 天',
    ofPer: '共{val1}条，每页5条',
  },
  CompareHBLTotalModal: {
    fromSynchronization: '从SI同步',
    containerRatio: '集装箱比对结果',
    theComparisonIsConsistent: '比对一致！',
    totalOfDocuments: 'H单合计',
  },
  ElectronicBox: {
    areYouSureYouWantToDelete: '确定删除？',
    pleaseChooseToRemove: '请选择拆分规则',
    electronicBoxList: '电子箱单',
    thereAreUnsaved: '有未保存的信息，确认将丢失您的修改信息',
    batchDelete: '批量删除',
    areYouSureYouWantToDelete2: '确定要删除吗?',
    areYouSureYouWantToReject: '确定要拒绝吗?',
    batchSelection: '批量选择集装箱',
    oneKeySharing: '一键均分',
    delete: '丨删除',
    selectionSet: '丨选择集装箱',
  },
  ImportCtn: {
    containerGuide: '集装箱导入模板',
    uploadedText: '4.上传的文件大小不能超过3M',
    importContainer: '导入集装箱时会覆盖原集装箱数据，是否覆盖？',
    numberOfContainers: '集装箱数据匹配',
    setDetected: '检测到集装箱数据如下：',
    confirmImport:
      '确认导入，系统将按以下顺序依次覆盖当前页面的集装箱箱封号数据',
    externalData: '外部数据导入',
    executing: '正在执行，请稍候...',
    importContainer2: '导入集装箱',
    clipboardGuide: '剪贴板导入',
    import: 'EXCEL导入',
    importSucceeded: '导入成功',
  },
  RelateSoDialog: {
    bigShipClosing: '大船截关日期',
    ofPer: '共{val1}条，每页5条',
  },
  SplitSubOrderBtn: {
    orderByCabinet: '按柜分单',
    separateCabinetsByOrder: '按单分柜',
    splitMode: '拆分模式',
    distributionSubOrder: '分配子单集装箱',
    selectSubOrder: '选择子单',
    caseNoSeal: '箱号丨封号丨箱型',
    pleaseEnterTheOrder: '请输入订单号查询',
    subOrderNo: '子单号',
  },
  VGMBatchDetailDialog: {
    maintenanceSuccessful: '维护成功！',
    emptyWeight: '空箱重',
  },
  CellRenderer: {
    areYouSureYouWantToTakeItOff: '确定要脱离关联的SO吗？',
    pleaseSelectBox: '请选择箱型',
    caseNumberAndOutside: '箱号与外部数据不匹配',
    released: '已放行',
    chineseSymbols: '未放行',
    exit: '退关',
    cancelRelease: '取消放行',
    refusalOfRelease: '拒绝放行',
    toBeReleased: '待放行',
  },
  Container: {
    noteFree: '免用备注',
    heapFreeRemarks: '免堆备注',
    applicationPurpose: '申请目的港 free time',
    weighingAddress: '称重地址',
    declare: 'VGM申报',
    totalWeight: 'VGM总重',
    weighingMethod: 'VGM称重方法',
    lclOrNot: '是否拼箱',
    electronicPacking: '电子装箱单',
    unpackingLocation: '拆箱地点',
    packingDate: '装箱日期',
    sealingBox: '封箱',
    boxOwner: '箱主',
    boxTypeRequired: '箱型必填！',
    weight: '重量',
    containerBody: '集装箱体积不等于多品名体积之和',
    containerGross: '集装箱毛重不等于多品名毛重之和',
    containerParts: '集装箱件数不等于多品名件数之和',
    systemDetection:
      '系统检测到拖车计划{val1}的所有集装箱已有箱号，该拖车计划是否标记【运输完成】？',
    sumPreservation: '求和保存',
    continueToSave: '继续保存',
    verificationInformation: '验证信息',
    gatePoint: '{val1}门点',
    date: '{val1}日期',
    pleaseSelectTheOneYouWant: '请选择要关联的数据！',
    setToBeAssociated: '待关联集装箱列表',
  },
  List: {
    client: '委托单位联系人',
    trailerService: '拖柜服务',
    orderNumber: '订单号、箱号、拖柜计划号、BKG号',
    templateDeletion: '模板删除成功！',
    templateSaving: '模板保存成功！',
    dispatchACar: '派车',
    successfulCarDispatch: '派车成功！',
    ofPer: '共{val1}条，每页{val2}条',
  },
  TruckTrack: {
    vehiclePositioning: '车辆定位',
    pleaseEnterVehicle: '请输入车牌号',
  },
};
